const $ = s => document.querySelector(s), esc = x => String(x ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statuses = {draft:'Черновик',approved:'Утверждено',active:'В работе',submitted:'Сдано · нужна проверка ИИ',pending_teacher:'Ожидает преподавателя',reviewed:'Проверено преподавателем'};
let meta, page='learn', session=null, task=null, review=null, busy=false, editorDirty=false, recognition=null, micSource=false, micTicket=0;
const token = $('meta[name=ui-token]').content;
const remembered = key => localStorage.getItem('practice:'+key) || '';
const remember = (key,value) => localStorage.setItem('practice:'+key,value);
function notice(text,error=false){$('#notice').hidden=!text;$('#notice').textContent=text;$('#notice').className=error?'error':'';}
async function api(action,payload={}){const r=await fetch('/api',{method:'POST',headers:{'Content-Type':'application/json','X-UI-Token':token},body:JSON.stringify({action,payload})});const data=await r.json();if(!r.ok)throw Error(data.error||'Не удалось выполнить действие');return data.result;}
async function run(text,fn){if(busy)return;stopMic();busy=true;notice(text);$('#content').inert=true;$('.sidebar').inert=true;document.body.setAttribute('aria-busy','true');try{await fn();if($('#notice').textContent===text)notice('');}catch(e){notice(e.message,true);}finally{busy=false;$('#content').inert=false;$('.sidebar').inert=false;document.body.setAttribute('aria-busy','false');}}
function badge(status){return `<span class="badge ${['approved','reviewed'].includes(status)?'good':''}">${esc(statuses[status])}</span>`;}
function input(label,name,value='',type='text'){return `<label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" value="${esc(value)}" required>`;}
function area(label,name,value='',attrs=''){return `<label for="${name}">${label}</label><textarea id="${name}" name="${name}" ${attrs}>${esc(value)}</textarea>`;}
const empty = text => `<div class="empty">${text}</div>`;
function history(rows){return rows.map(r=>`<div class="bubble ${r.role==='dispatcher'?'dispatcher':''}"><b>${({caller:'Заявитель',dispatcher:'Диспетчер',service:'Служба',system:'Событие'})[r.role]} · ${r.id}</b>${esc(r.text)}${r.delivery&&r.delivery!=='full'?`<small class="error-text">Доставлено службе: ${esc(r.delivered||'ничего')}</small>`:''}</div>`).join('');}
function cardDraft(s){try{return {...s.card,...JSON.parse(remembered('card:'+s.id)||'{}')};}catch{return s.card;}}
async function saveCard(){if(!session||session.status!=='active')return;session=await api('save_card',{id:session.id,card:cardDraft(session)});localStorage.removeItem('practice:card:'+session.id);if($('#save-status'))$('#save-status').textContent='Сохранено';}
async function navigate(next){if(editorDirty&&!confirm('Изменения задания не сохранены. Выйти без сохранения?'))return;await saveCard();editorDirty=false;task=null;review=null;session=null;page=next;$('.nav.active')?.classList.remove('active');$(`[data-page=${page}]`).classList.add('active');$('#heading').textContent={learn:'Обучение',tasks:'Карточки заданий',works:'Проверка работ'}[page];if(page==='learn')await learnHome();if(page==='tasks')await taskHome();if(page==='works')await workHome();}
async function learnHome(){meta=await api('home');const name=remembered('student');const sessions=name?await api('sessions',{student:name}):[];$('#content').innerHTML=`<div class="card intro"><div class="row between"><div><h2>Практика начинается со звонка</h2><p>Уточняйте сведения у заявителя и заполняйте карточку. После сдачи работу проверят ИИ и преподаватель.</p></div><div><span class="number">${meta.count}</span><div class="muted">карточек доступно</div></div></div></div><div class="grid"><section class="card"><h2>Новое упражнение</h2><p class="muted">${meta.count===1?'Будет выдана ваша единственная утверждённая карточка.':'Задание выбирается из утверждённых карточек выбранного учебного варианта.'}</p><form id="start-form">${workflowOptions('learn-workflow',remembered('workflow')||'caller')}${input('Имя обучающегося','student-name',name)}<div class="actions"><button ${!meta.count?'disabled':''}>Начать обучение</button><button type="button" class="secondary" data-cmd="refresh-sessions">Мои работы</button></div></form>${!meta.count?'<p class="muted">Сначала создайте и утвердите задание в разделе «Карточки заданий».</p>':''}</section><section class="card"><h2>Ваши работы</h2>${sessions.length?sessions.map(s=>`<div class="list-item"><div><h3>${esc(s.title)}</h3><p>${esc(meta.levels[s.level])} · ${esc(statuses[s.status])}</p></div><button class="secondary" data-cmd="open-session" data-id="${s.id}">${s.status==='active'?'Продолжить':'Посмотреть'}</button></div>`).join(''):empty('Введите своё имя и нажмите «Мои работы».')}</section></div>`;}
function renderSession(){const s=session;const active=s.status==='active';const values=cardDraft(s);$('#content').innerHTML=`<div class="row between" style="margin-bottom:18px"><div><button class="ghost" data-cmd="back-learn">← К моим работам</button><h2>${esc(s.title)}</h2><span class="muted">${esc(s.student)} · ${esc(meta.levels[s.level])}</span></div>${badge(s.status)}</div>${!active?`<section class="card intro"><h2>${s.result?'Решение преподавателя':'Работа сдана'}</h2>${s.result?`<p><b>Оценка: ${s.result.grade}</b> · ${esc(s.result.teacher)}</p><p>${esc(s.result.conclusion)}</p><details><summary>Комментарии по полям</summary>${Object.entries(s.result.fields).map(([k,v])=>`<p><b>${esc(meta.fields[k]||meta.action_labels[k])}:</b> ${esc(v.comment)}</p>`).join('')}</details>`:'<p>Ожидайте окончательного решения преподавателя. Предварительное заключение ИИ доступно ему в разделе проверки работ.</p>'}</section>`:''}<div class="grid"><section class="card"><div class="row between"><h2>Разговор с заявителем</h2><span class="pill">${active?'На линии':'Завершён'}</span></div><div class="chat" id="chat">${history(s.history)}</div>${s.hints.length?`<div class="hint"><b>Подсказка</b><br>${esc(s.hints.at(-1).text)}</div>`:''}${active?`<form id="question-form">${area('Ваш вопрос','question','','maxlength="2000" required placeholder="Например: внутри кто-нибудь остался?"')}<p class="muted" id="mic-status">Можно написать или продиктовать вопрос. Проверьте текст перед отправкой.</p><div class="actions"><button>Спросить</button><button class="secondary" type="button" data-cmd="mic">🎙 Микрофон</button><button class="secondary" type="button" data-cmd="hint" ${s.level==='hard'?'disabled title="На сложном уровне подсказки отключены"':''}>Подсказка</button></div></form>`:''}</section><section class="card"><div class="row between"><h2>Карточка вызова</h2><span class="saved" id="save-status">${remembered('card:'+s.id)?'Есть несохранённые записи':'Сохранено'}</span></div><p class="muted">Заполняйте самостоятельно, только со слов заявителя.</p><div id="card-fields">${Object.entries(meta.fields).map(([k,label])=>area(label,'card-'+k,values[k],`data-card="${k}" maxlength="2000" ${active?'':'disabled'}`)).join('')}</div>${active?'<div class="actions"><button class="secondary" data-cmd="save-card">Сохранить карточку</button><button data-cmd="submit">Сдать работу</button></div><p class="muted">После сдачи изменить ответы нельзя.</p>':''}</section></div>`;decorateSession();$('#chat').scrollTop=$('#chat').scrollHeight;}
async function taskHome(){const tasks=await api('tasks');$('#content').innerHTML=`<div class="grid"><section class="card"><h2>Создать задание</h2><p class="muted">ИИ подготовит сценарий и эталон. Проверьте их перед выдачей обучающемуся.</p><form id="create-form">${workflowOptions('create-workflow')}${area('Тема или ситуация','topic','','required placeholder="Например: пожар в гараже, заявитель не знает, вышел ли человек"')}<label for="level">Сложность</label><select id="level">${Object.entries(meta.levels).map(([k,v])=>`<option value="${k}" ${k==='medium'?'selected':''}>${v}</option>`).join('')}</select><div class="actions"><button>Создать с GigaChat</button><button type="button" class="secondary" data-cmd="sample">Готовый пример</button></div></form></section><section class="card"><div class="row between"><h2>Ваши карточки</h2><span class="badge">${tasks.length}</span></div>${tasks.length?tasks.map(t=>`<div class="list-item"><div><h3>${esc(t.title)}</h3><p>${esc(meta.levels[t.level])} · ${esc(statuses[t.status])}</p></div><button class="secondary" data-cmd="open-task" data-id="${t.id}">${t.status==='draft'?'Проверить':'Открыть'}</button></div>`).join(''):empty('Карточек пока нет. Начните с готового примера.')}</section></div>`;}
function renderTask(){const readonly=task.status==='approved';$('#content').innerHTML=`<div class="wide"><div class="row between"><button class="ghost" data-cmd="back-tasks">← Все карточки</button>${badge(task.status)}</div><section class="card" style="margin-top:16px"><h2>${readonly?'Утверждённое задание':'Проверьте задание и эталон'}</h2><p class="muted">Эти сведения доступны преподавателю. Обучающийся получит только разговор и пустую карточку.</p><fieldset ${readonly?'disabled':''} style="border:0;padding:0;margin:0" id="task-editor">${input('Название','task-title',task.title)}${area('Первая реплика заявителя','task-opening',task.opening)}${area('Характер и поведение заявителя','task-persona',task.persona)}${Object.entries(meta.fields).map(([k,label])=>`<details ${k==='address'?'open':''}><summary>${label}</summary><div class="cols">${area('Факт сценария',k+'-truth',task.fields[k].truth)}${area('Что знает заявитель',k+'-known',task.fields[k].known)}${area('Эталон заполнения',k+'-expected',task.fields[k].expected)}${area('Критерий проверки',k+'-criterion',task.fields[k].criterion)}</div>${input('Вес критерия (1–10)',k+'-weight',task.fields[k].weight,'number')}</details>`).join('')}</fieldset>${readonly?`<p class="hint">Утвердил: ${esc(task.approved_by)}. Карточка доступна в разделе «Обучение».</p>`:`${input('Имя преподавателя','teacher-name',remembered('teacher'))}<div class="actions"><button class="secondary" data-cmd="save-task">Сохранить черновик</button><button data-cmd="approve">Утвердить и выдать в обучение</button></div>`}</section></div>`;decorateTask();editorDirty=false;}
async function saveTask(){const fields={};for(const k of Object.keys(meta.fields)){fields[k]={};for(const p of ['truth','known','expected','criterion','weight'])fields[k][p]=p==='weight'?Number($('#'+k+'-'+p).value):$('#'+k+'-'+p).value;}task=await api('save_task',{id:task.id,title:$('#task-title').value,opening:$('#task-opening').value,persona:$('#task-persona').value,fields,...collectDDS()});editorDirty=false;}
async function workHome(){const works=await api('works');$('#content').innerHTML=`<section class="card"><h2>Сданные работы</h2><p class="muted">ИИ делает предварительный разбор. Замечания и итоговую оценку утверждаете вы.</p>${works.length?works.map(w=>`<div class="list-item"><div><h3>${esc(w.title)}</h3><p>${esc(w.student)} · ${esc(statuses[w.status])}</p></div><button class="secondary" data-cmd="open-work" data-id="${w.id}">Рассмотреть</button></div>`).join(''):empty('Обучающиеся ещё не сдали работы. Утверждённые задания находятся в разделе «Карточки заданий».')}</section>`;}
function renderReview(){const s=review,a=s.assessment;$('#content').innerHTML=`<div class="wide"><button class="ghost" data-cmd="back-works">← Все работы</button><section class="card" style="margin-top:16px"><div class="row between"><h2>${esc(s.task.title)}</h2>${badge(s.status)}</div><p>${esc(s.student)} · ${esc(meta.levels[s.task.level])} · Подсказок: ${s.hints.length}</p><details><summary>Разговор и использованные подсказки</summary>${history(s.history)}${s.hints.map(h=>`<div class="hint">${esc(h.text)}</div>`).join('')}</details></section>${!a?'<section class="card"><h2>Нужна предварительная проверка ИИ</h2><p>Карточка ученика сохранена. Запустите проверку, чтобы получить разбор для рассмотрения.</p><button data-cmd="assess">Проверить с GigaChat</button></section>':`<section class="card"><h2>Предварительное заключение ИИ</h2><p>${esc(a.summary)}</p>${Object.entries(reviewLabels()).map(([k,label])=>{const f=a.fields[k];return `<div class="field-review"><h3>${label} <span class="pill">${esc(meta.verdicts[f.verdict])}</span></h3><div class="cols"><div><b>Обучающийся</b><p>${esc(s.card[k]||(k.startsWith('action_')?'См. разговор и события связи':'Не заполнено'))}</p></div><div><b>Утверждённый эталон</b><p>${esc((s.task.fields[k]||s.task.actions[k]).expected)}</p></div></div><p class="muted">Критерий: ${esc((s.task.fields[k]||s.task.actions[k]).criterion)}</p><p>${esc(f.comment)}</p><p>${esc(f.clarification)}</p>${f.evidence.map(c=>`<div class="quote">Реплика ${c.turn_id}: «${esc(c.quote)}»</div>`).join('')}${f.citation_warning?'<p class="error-text">ИИ привёл неподтверждённую цитату. Замечание требует ручной проверки.</p>':''}${s.status==='reviewed'?`<p><b>Преподаватель:</b> ${esc(s.teacher_decision.fields[k].comment)}</p>`:`<label for="decision-${k}">Ваше решение</label><select id="decision-${k}" data-decision="${k}"><option value="">Выберите решение</option><option value="agree">Согласен с замечанием ИИ</option><option value="reject">Отклонить замечание</option><option value="edit">Исправить замечание</option></select>${area('Комментарий обучающемуся','comment-'+k,'')}`}</div>`;}).join('')}</section>${s.status==='reviewed'?`<section class="card intro"><h2>Оценка: ${s.teacher_decision.grade}</h2><p>${esc(s.teacher_decision.conclusion)}</p><p class="muted">${esc(s.teacher_decision.teacher)}</p></section>`:`<section class="card"><h2>Итог преподавателя</h2><div class="cols">${input('Имя преподавателя','teacher-name',remembered('teacher'))}<div><label for="grade">Ваша оценка</label><select id="grade"><option value="">Выберите</option>${[2,3,4,5].map(n=>`<option>${n}</option>`).join('')}</select></div></div>${area('Итоговый комментарий','conclusion')}<div class="actions"><button data-cmd="finalize">Опубликовать итог для обучающегося</button></div></section>`}`}</div>`;}
function stopMic(){micTicket++;recognition?.abort();recognition=null;}
async function mic(){const C=window.SpeechRecognition||window.webkitSpeechRecognition;if(!C){notice('Этот браузер не поддерживает распознавание. Используйте Chrome / Edge или текстовый ввод.',true);return;}if(recognition){stopMic();return;}const ticket=++micTicket;try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});stream.getTracks().forEach(t=>t.stop());if(ticket!==micTicket||!$('#question'))return;recognition=new C();recognition.lang='ru-RU';recognition.interimResults=true;recognition.onresult=e=>{if(ticket!==micTicket)return;if($('#question'))$('#question').value=Array.from(e.results).map(r=>r[0].transcript).join(' ');micSource=true;};let failed=false;recognition.onerror=e=>{failed=true;notice(e.error==='not-allowed'?'Разрешите микрофон в настройках сайта.':'Распознавание недоступно: '+e.error+'. Можно написать вопрос вручную.',true);};recognition.onend=()=>{recognition=null;if($('#mic-status'))$('#mic-status').textContent=failed?'Попробуйте снова или введите вопрос текстом.':'Проверьте распознанный текст и нажмите «Спросить».';};$('#mic-status').textContent='Слушаю… Нажмите «Микрофон» ещё раз, чтобы остановить.';recognition.start();}catch(e){notice('Не удалось включить микрофон. Разрешите доступ в браузере и проверьте подключение устройства.',true);}}
async function maybeHint(){if(session.level==='easy'){session=await api('hint',{id:session.id});renderSession();}}
document.addEventListener('input',e=>{if(e.target.dataset.card&&session){const values=cardDraft(session);values[e.target.dataset.card]=e.target.value;remember('card:'+session.id,JSON.stringify(values));$('#save-status').textContent='Есть несохранённые записи';}if(e.target.closest('#task-editor'))editorDirty=true;});
document.addEventListener('change',e=>{if(e.target.id==='next-channel'){const mode=e.target.value;run('Настраиваю учебную связь…',async()=>{await saveCard();session=await api('channel',{id:session.id,mode});renderSession();});return;}const k=e.target.dataset.decision;if(k&&review){$('#comment-'+k).value=e.target.value==='agree'?review.assessment.fields[k].comment:'';}});
document.addEventListener('submit',e=>{e.preventDefault();const id=e.target.id;if(id==='start-form'){const name=$('#student-name').value.trim();remember('student',name);const workflow=$('#learn-workflow').value;remember('workflow',workflow);run('Открываю задание…',async()=>{session=await api('start',{student:name,workflow});renderSession();await maybeHint();});}if(id==='create-form'){const topic=$('#topic').value,level=$('#level').value,workflow=$('#create-workflow').value;run('GigaChat создаёт сценарий и эталон. Это может занять около минуты…',async()=>{task=await api('create',{topic,level,workflow});renderTask();});}if(id==='question-form'){const question=$('#question').value.trim(),source=micSource?'voice':'text';if(!question)return;run('Заявитель отвечает…',async()=>{await saveCard();session=await api('ask',{id:session.id,question,source});micSource=false;renderSession();await maybeHint();});}});
document.addEventListener('click',e=>{const el=e.target.closest('button');if(!el||busy)return;if(el.dataset.page){run('Открываю раздел…',()=>navigate(el.dataset.page));return;}const cmd=el.dataset.cmd,id=el.dataset.id;if(!cmd)return;if(cmd==='mic'){mic();return;}
run('Выполняю…',async()=>{
 if(cmd==='refresh-sessions'){remember('student',$('#student-name').value.trim());await learnHome();}
 if(cmd==='connect-service'){await saveCard();session=await api('connect',{id:session.id});renderSession();}
 if(cmd==='end-service'){await saveCard();session=await api('channel',{id:session.id,mode:'hangup'});renderSession();}
 if(cmd==='open-session'){session=await api('student',{id});renderSession();}
 if(cmd==='back-learn')await navigate('learn');
 if(cmd==='back-tasks')await navigate('tasks');
 if(cmd==='back-works')await navigate('works');
 if(cmd==='sample'){task=await api('create',{sample:true,level:$('#level').value,workflow:$('#create-workflow').value});renderTask();}
 if(cmd==='open-task'){task=(await api('tasks')).find(t=>t.id===id);renderTask();}
 if(cmd==='save-task'){await saveTask();notice('Черновик сохранён.');}
 if(cmd==='approve'){const teacher=$('#teacher-name').value.trim();if(!teacher)throw Error('Введите имя преподавателя.');await saveTask();task=await api('approve',{id:task.id,teacher});remember('teacher',teacher);renderTask();notice('Карточка утверждена и доступна в разделе «Обучение».');}
 if(cmd==='save-card'){await saveCard();notice('Карточка сохранена.');}
 if(cmd==='hint'){await saveCard();session=await api('hint',{id:session.id});renderSession();}
 if(cmd==='submit'){if(!confirm('Сдать работу? После сдачи изменить карточку нельзя.'))return;session=await api('submit',{id:session.id,card:cardDraft(session)});localStorage.removeItem('practice:card:'+session.id);renderSession();notice('Работа сдана. ИИ готовит заключение для преподавателя…');try{await api('assess',{id:session.id});session=await api('student',{id:session.id});renderSession();notice('Работа передана преподавателю.');}catch(err){notice('Работа сохранена и сдана. Проверка ИИ не завершена: '+err.message+' Преподаватель может повторить её в разделе проверки.',true);}}
 if(cmd==='open-work'){review=await api('review',{id});renderReview();}
 if(cmd==='assess'){notice('ИИ проверяет работу…');await api('assess',{id:review.id});review=await api('review',{id:review.id});renderReview();notice('Заключение готово. Проверьте замечания и вынесите своё решение.');}
 if(cmd==='finalize'){const decisions={};for(const k of Object.keys(reviewLabels()))decisions[k]={decision:$('#decision-'+k).value,comment:$('#comment-'+k).value.trim()};const teacher=$('#teacher-name').value.trim();await api('finalize',{id:review.id,teacher,grade:Number($('#grade').value),conclusion:$('#conclusion').value.trim(),decisions});remember('teacher',teacher);review=await api('review',{id:review.id});renderReview();notice('Итог преподавателя опубликован для обучающегося.');}
});});
window.addEventListener('beforeunload',e=>{stopMic();if(editorDirty||busy){e.preventDefault();e.returnValue='';}});
run('Загружаю сохранённые карточки…',async()=>{meta=await api('home');await learnHome();});
