'use strict';
const {svg,escape:esc}=window.TeacherShell;
let overview={sessions:[],tasks:[]},loadError='',routeTicket=0;
const statuses={active:'В процессе',submitted:'На проверке',pending_teacher:'На проверке',reviewed:'Проверена'};
const workflowLabel=k=>k==='dds'?'Диспетчер ДДС':'Оператор 112';
const dateShort=s=>s?new Date(s).toLocaleDateString('ru-RU'):'—';
async function fetchOverview(){
 const response=await fetch('/api',{method:'POST',headers:{'Content-Type':'application/json','X-UI-Token':document.querySelector('meta[name=ui-token]').content},body:JSON.stringify({action:'teacher_overview'})});
 const data=await response.json();if(!response.ok)throw Error(data.error||'Не удалось загрузить тренировки.');return data.result;
}
function table(rows,emptyText,blank=true){return `<div class="teacher-table-wrap"><table class="teacher-table"><thead><tr><th scope="col">Дата</th><th scope="col">Название</th><th scope="col">Сценарий</th><th scope="col">Обучающийся</th><th scope="col">Результат</th></tr></thead><tbody>${rows.map(s=>`<tr><td>${esc(dateShort(s.created_at))}</td><td><a href="/training#${s.status==='active'?'learn':'works'}">${esc(s.title)}</a></td><td>${workflowLabel(s.workflow)}</td><td>${esc(s.student)}</td><td>${s.grade!=null?esc(s.grade)+' / 5':esc(statuses[s.status]||'—')}</td></tr>`).join('')||`<tr class="empty-row"><td colspan="5">${esc(emptyText)}</td></tr>`}${blank?Array.from({length:Math.max(0,4-Math.max(1,rows.length))},()=>'<tr class="blank-row" aria-hidden="true"><td colspan="5"></td></tr>').join(''):''}</tbody></table></div>`;}
function home(){return `<section class="teacher-hero"><p class="teacher-eyebrow">Панель преподавателя</p><h1>УПРАВЛЯЙТЕ<br>ОБУЧЕНИЕМ</h1></section><section class="teacher-actions" aria-label="Быстрые действия">${[
 ['plus','Создать<br>тренировку','/training#learn','primary'],['file','Выбрать<br>сценарий','/teacher#scenarios',''],['users','Назначить<br>обучающихся','/teacher#students',''],['chart','Посмотреть<br>результаты','/teacher#results','']
 ].map(([icon,label,url,cl])=>`<a class="teacher-tile ${cl}" href="${url}">${svg(icon)}<span class="tile-label">${label}</span><span class="tile-arrow">${svg('arrow')}</span></a>`).join('')}</section><section><div class="teacher-section-heading"><h2>Последние тренировки</h2><span class="rule"></span><a href="/teacher#trainings">Все тренировки ${svg('arrow')}</a></div>${table(overview.sessions.slice(0,4),'Тренировок пока нет. Начните с подготовки карточек или создайте тренировку.')}</section>`;}
function scenarios(){return `<p class="teacher-eyebrow">Панель преподавателя</p><h1 class="teacher-title">Сценарии</h1><p class="teacher-description">Учебные сценарии из прежнего прототипа. Новые карточки происшествий создаются и утверждаются в отдельном разделе.</p><div class="teacher-toolbar"><a class="teacher-dark" href="/cards">Создать карточки</a><a class="teacher-button" href="/training#tasks">Открыть учебные сценарии</a></div><div class="teacher-panels">${overview.tasks.map(t=>`<article class="teacher-panel"><span class="teacher-tag">${t.status==='approved'?'Утверждён':'Черновик'}</span><h2 style="margin-top:18px">${esc(t.title)}</h2><p>${workflowLabel(t.workflow)} · ${esc({easy:'Лёгкий',medium:'Средний',hard:'Сложный'}[t.level]||t.level)}</p><a class="teacher-button" href="/training#tasks">Открыть список сценариев →</a></article>`).join('')||'<article class="teacher-panel"><h2>Пока нет сценариев</h2><p>Начните с создания и утверждения карточек происшествий.</p><a href="/cards" class="teacher-button">К карточкам →</a></article>'}</div>`;}
function students(){const counts=new Map();overview.sessions.forEach(s=>counts.set(s.student,(counts.get(s.student)||0)+1));return `<p class="teacher-eyebrow">Панель преподавателя</p><h1 class="teacher-title">Обучающиеся</h1><p class="teacher-description">Здесь отображаются участники сохранённых тренировок. Назначение групп и доступ через учётные записи пока не подключены.</p><a class="teacher-button" href="/training#learn">Открыть учебный прототип →</a><div class="teacher-panels" style="margin-top:25px">${[...counts].map(([name,count])=>`<article class="teacher-panel"><h2>${esc(name)}</h2><p>Тренировок: ${count}</p></article>`).join('')||'<article class="teacher-panel"><h2>Список пока пуст</h2><p>Участники появятся после создания тренировок в учебном прототипе.</p></article>'}</div>`;}
function settings(){return `<p class="teacher-eyebrow">Панель преподавателя</p><h1 class="teacher-title">Настройки</h1><form id="profile-form" class="teacher-form"><label for="profile-input">Имя преподавателя</label><input id="profile-input" maxlength="160" required value="${esc(TeacherShell.profile()==='Преподаватель'?'':TeacherShell.profile())}" placeholder="Фамилия и инициалы"><p>Имя отображается в шапке панели на этом устройстве. При утверждении карточки имя преподавателя указывается отдельно.</p><button class="teacher-dark">Сохранить</button><p id="profile-status" role="status"></p></form>`;}
function render(){
 const route=location.hash.slice(1)||'home',target=document.getElementById('teacher-content');let body='';
 if(route==='home')body=home();
 else if(route==='trainings')body=`<p class="teacher-eyebrow">Панель преподавателя</p><h1 class="teacher-title">Тренировки</h1><div class="teacher-toolbar"><a href="/training#learn" class="teacher-dark">Создать тренировку</a><a href="/cards" class="teacher-button">Подготовить карточки</a></div>${table(overview.sessions,'Сохранённых тренировок пока нет.',false)}`;
 else if(route==='scenarios')body=scenarios();
 else if(route==='students')body=students();
 else if(route==='results')body=`<p class="teacher-eyebrow">Панель преподавателя</p><h1 class="teacher-title">Результаты</h1><p class="teacher-description">Оценки, подтверждённые преподавателем, показаны по шкале 2–5. Работы без окончательного решения отмечены «На проверке».</p><div class="teacher-toolbar"><a class="teacher-dark" href="/training#works">Открыть проверку работ</a></div>${table(overview.sessions.filter(s=>s.status!=='active'),'Сданных работ пока нет.',false)}`;
 else if(route==='messages')body='<p class="teacher-eyebrow">Панель преподавателя</p><h1 class="teacher-title">Сообщения</h1><article class="teacher-panel"><h2>Сообщений пока нет</h2><p>Обмен сообщениями с обучающимися пока не подключён. Замечания к карточке можно оставить при её утверждении.</p><a class="teacher-button" href="/cards">Перейти к карточкам →</a></article>';
 else if(route==='settings')body=settings();
 else {location.hash='home';return;}
 target.innerHTML=(loadError?`<p class="teacher-error">${esc(loadError)} <button id="reload-overview" class="teacher-button">Повторить</button></p>`:'')+body;
 TeacherShell.update();document.title=(route==='home'?'Панель преподавателя':{trainings:'Тренировки',scenarios:'Сценарии',students:'Обучающиеся',results:'Результаты',messages:'Сообщения',settings:'Настройки'}[route])+' · ИИ для проекта';
 document.getElementById('profile-form')?.addEventListener('submit',e=>{e.preventDefault();const name=document.getElementById('profile-input').value.trim();if(!name)return;try{localStorage.setItem('giik.teacher.profile.v1',JSON.stringify({name}));TeacherShell.update();document.getElementById('profile-status').textContent='Имя сохранено.';}catch{document.getElementById('profile-status').textContent='Браузер не смог сохранить имя.';}});
 document.getElementById('reload-overview')?.addEventListener('click',load);
 document.body.dataset.teacherReady='true';
}
async function load(){const ticket=++routeTicket;try{const data=await fetchOverview();if(ticket!==routeTicket)return;overview=data;loadError='';}catch(e){if(ticket!==routeTicket)return;loadError='Не удалось загрузить сохранённые тренировки. Карточки доступны через меню.';}render();}
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});
render();load();
