---
title: "Внутренние термины"
subtitle: "Дополнительные термины используемые в «Учебном ПО для подготовки оператора ДДС»"
author:
  - "Малютин О.С."
date: today
lang: ru
format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    theme: cosmo
    mermaid:
      theme: neutral

---

# Термины

| Термин | Определение |
|-----------------------|-------------------------------------------------|
| Учебный сценарий | Набор учебных задач выполняемых в соответствии с темой занятий |
| Тема занятий | Тематика учебного занятия определяющая какие задания выполняются в рамках конкрретного сценаррия |
| Учебная задача | Единичное задание, которое поставлено в рамках учебного занятия. Включает исходные данные (строку сообщения) и эталонное значение заполненной карточки |
| Диспозиция | Исходные данные – сообщение завителя+возможные формрализованные данные (адрес и т.д.) |
| Карточка-112 | Карточка события в которой отражаются все его основные сведения в соответствии с интерфейсом системы 112 (телефоны, ФИО заявителя, адрес, группа события и его признаки и т.д.) |
| Эталон (Эталонный ответ, Эталонная карточка) | Обрразец того, как должна быть заполнена `Карточка-112`, исходя из `диспозиции`. |
| Обучающийся | Лицо проходящее обучение в системе |
| Тренировка | Одно учебное занятие в рамках которого отрабатывается один или несколько учебных сценариев и в которрой участвет несколько обучающихся |
| Учебный симулятор | Разрабатываемое Учебное программное обеспечение для подготовки оператора ДДС города Москвы с использованием искусственного интеллекта |
| Пользователь | Пользователь `Учебного симулятора` |
|  |  |
|  |  |