# Что нужно для отчета по Хакатону

## Репозиторий проекта

*Ссылка на публичный Git-репозиторий*. Убедитесь, что репозиторий открыт для просмотра или предоставлен гостевой доступ. В корне обязательно добавьте README.md с инструкцией по локальному запуску.

- [ ] Загрузить исходный код итогового решения в репозиторий на SourceCraft

https://sourcecraft.dev/lct-hackaton-2026/case-09-112-dispatcher-simulator-team-1


## Документация

*Документация*
- ссылка на описание архитектуры, 
- стек, 
- инструкцию по развертыванию, 
- API или пояснительную записку (Google Docs, Notion, PDF на диске или файл в самом репозитории).




## Презентация

> Ссылка на слайды проекта (PDF на облачном диске, Яндекс.Диске, Google Slides и т.д.).


### Техническая суть решения:

- База данных: **PostgreSQL** Можно использовать как удаленный так и локальный сервер БД
- Фронтенд: 
- Бэкенд:
- Взаимодействие между фронтендом и бэкендом: REST API
- LLM: Можно использовать как удаленные сервисы LLM, так и локально развернутые. Допустимы к использованию OpenAI-совместимые ррешения, а также отечественные - GigaChat
- Использование локальной карты на основе открытых данных OSM и библиотеки MapLibre






## Прототип

> Ссылка на развернутый и работающий сервис (веб-интерфейс, стенд, тестовый сервер или бот). 

**Варианты:**

1. Развернуть где-то на *сайте*.
2. Выложить *portable version*






# Дополнительные материалы

> любые вспомогательные файлы (ссылка на видеодемонстрацию/скринкаст, датасеты, схемы архитектуры, Figma-макеты).


## Видео



# Важно!

**Железное правило** стоп-кода: что делать СТРОГО НЕЛЬЗЯ

После наступления дедлайна сдачи (стоп-кода) наступает этап экспертной оценки. С этого момента:

⛔️ Строго запрещено коммитить и пушить новый код в сданные ветки репозиториев.
⛔️ Строго запрещено редактировать презентации, документацию и файлы по ссылкам (история правок в Google Docs, даты изменения файлов на дисках и история коммитов в Git логируются).
⛔️ Строго запрещено обновлять сайт / прод-стенд прототипа, накатывать новые релизы или менять функционал.

Нарушение этого правила влечет автоматическую дисквалификацию команды. Оценка проводится строго по тому состоянию проекта, которое было зафиксировано на момент дедлайна. Эксперты проверяют таймштампы файлов и коммитов.





