import {useEffect,useMemo,useState} from 'react';
import {api} from './api.js';
import {adminLogout,adminName,adminSignedIn,ADMIN_USERS,readAdminAccount,seedAdminUser} from './admin-auth.js';

const PLAN_STORAGE='giik.training-plans.v1', CARD_STORAGE='giik.card-workshop.v1';
const menu=[['home','⌂','Главная'],['users','♙','Пользователи'],['trainings','◇','Тренировки'],['scenarios','▱','Сценарии'],['cards','▤','Карточки'],['results','▥','Результаты'],['monitoring','▣','Мониторинг'],['system','⚙','Управление системой'],['settings','☼','Настройки']];
const statusLabel={queued:'Ожидает предыдущую',active:'Активна',submitted:'На проверке',pending_teacher:'На проверке',reviewed:'Завершена'};
const fmt=v=>{if(!v)return '—';try{return new Date(v).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'});}catch{return v;}};
const loadJSON=(key,fallback)=>{try{const v=JSON.parse(localStorage.getItem(key)||'null');return v??fallback;}catch{return fallback;}};
const saveUsers=list=>localStorage.setItem(ADMIN_USERS,JSON.stringify(list));
function useAdminData(){
 const [data,setData]=useState({sessions:[],tasks:[],scenarios:[],trainings:[],error:'',loading:true});
 const refresh=async()=>{try{const [d,scenarios,trainings]=await Promise.all([api('teacher_dashboard'),api('scenario_list'),api('training_list')]);setData({...d,scenarios,trainings,error:'',loading:false});}catch(e){setData(x=>({...x,error:e.message,loading:false}));}};
 useEffect(()=>{refresh();const t=setInterval(()=>{if(!document.hidden)refresh();},20000);return()=>clearInterval(t);},[]);
 return [data,refresh];
}
function derived(data){
 const workshop=loadJSON(CARD_STORAGE,{cards:[]}),plans=data.scenarios||[],account=readAdminAccount();
 let users=loadJSON(ADMIN_USERS,[]);if(!Array.isArray(users))users=[];
 const seen=new Set(users.map(x=>x.name));
 const add=(name,role)=>{if(!name||seen.has(name))return;seen.add(name);users.push({id:crypto.randomUUID(),name,login:name.toLowerCase().replace(/[^a-zа-я0-9]+/gi,'.').replace(/^\.|\.$/g,''),role,status:'Активен',last_login:'',permissions:role==='Преподаватель'?['trainings','scenarios','cards','results']:['training']});};
 data.sessions.forEach(s=>add(s.student,'Обучающийся'));data.sessions.forEach(s=>add(s.training?.teacher,'Преподаватель')); if(account)add(account.name,'Администратор');
 saveUsers(users);
 const groups=new Map();data.sessions.forEach(s=>{const id=s.training?.plan_id||s.training?.title||s.task_id||s.id;if(!groups.has(id))groups.set(id,{id,title:s.training?.title||s.title,teacher:s.training?.teacher||'—',group:s.training?.group||'—',mode:s.training?.mode==='testing'?'Тестирование':'Обучение',sessions:[],created_at:s.created_at});groups.get(id).sessions.push(s);});
 const trainings=[...data.trainings.map(t=>({...t,teacher:t.teacher,group:t.group,mode:t.mode==='testing'?'Тестирование':'Обучение',students:t.participants.length,created_at:t.created_at,sessions:data.sessions.filter(s=>s.training?.training_id===t.id),status:({prepared:'Подготовлена',active:'Активна',completed:'Завершена'})[t.status]})),...([...groups.values()].filter(g=>!data.trainings.some(t=>t.id===g.id)).map(t=>({...t,status:t.sessions.every(s=>s.status==='reviewed')?'Завершена':t.sessions.some(s=>s.status==='active')?'Активна':'Назначена',students:new Set(t.sessions.map(s=>s.student)).size})))];
 return {users,cards:Array.isArray(workshop.cards)?workshop.cards:[],scenarios:Array.isArray(plans)?plans:[],trainings};
}
function Dot({tone='green'}){return <span className={'admin-dot '+tone}/>;}
function Drawer({title,onClose,children}){return <div className="admin-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><aside className="admin-drawer" role="dialog" aria-modal="true" aria-label={title}><header className="admin-drawer-head"><h2>{title}</h2><button onClick={onClose} aria-label="Закрыть">×</button></header>{children}</aside></div>;}
function Modal({title,onClose,children}){return <div className="admin-modal-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section className="admin-modal"><header><h3>{title}</h3><button onClick={onClose}>×</button></header>{children}</section></div>;}
function Tabs({items,value,onChange}){return <nav className="admin-tabs">{items.map(x=><button key={x[0]} className={value===x[0]?'active':''} onClick={()=>onChange(x[0])}>{x[1]}</button>)}</nav>;}
function Toolbar({search,setSearch,children}){return <div className="admin-toolbar"><label className="admin-search">⌕<input placeholder="Поиск" value={search} onChange={e=>setSearch(e.target.value)}/></label>{children}</div>;}
function Empty({text='Данных пока нет'}){return <div className="admin-empty">{text}</div>;}

function UsersDrawer({model,onClose}){
 const [tab,setTab]=useState('users'),[search,setSearch]=useState(''),[role,setRole]=useState(''),[selected,setSelected]=useState(model.users[0]?.id||''),[users,setUsers]=useState(model.users),[add,setAdd]=useState(false);
 const list=users.filter(u=>(!search||(u.name+' '+u.login).toLowerCase().includes(search.toLowerCase()))&&(!role||u.role===role));const current=users.find(u=>u.id===selected)||list[0];
 const update=patch=>{const next=users.map(u=>u.id===current.id?{...u,...patch}:u);setUsers(next);saveUsers(next);};
 return <Drawer title="Пользователи и доступ" onClose={onClose}><Tabs value={tab} onChange={setTab} items={[["users","Пользователи"],["roles","Роли"],["audit","Аудит"]]}/>{tab==='users'?<><Toolbar search={search} setSearch={setSearch}><select value={role} onChange={e=>setRole(e.target.value)}><option value="">Все роли</option><option>Администратор</option><option>Преподаватель</option><option>Обучающийся</option></select><button className="admin-primary" onClick={()=>setAdd(true)}>Добавить пользователя</button></Toolbar><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>ФИО</th><th>Логин</th><th>Роль</th><th>Статус</th><th>Последний вход</th></tr></thead><tbody>{list.map(u=><tr key={u.id} className={u.id===current?.id?'selected':''} onClick={()=>setSelected(u.id)}><td>{u.name}</td><td>{u.login||'—'}</td><td>{u.role}</td><td><Dot tone={u.status==='Заблокирован'?'red':'green'}/>{u.status}</td><td>{fmt(u.last_login)}</td></tr>)}</tbody></table></div>{current&&<div className="admin-detail-grid"><section><h3>Основная информация</h3><label>ФИО<input value={current.name} onChange={e=>update({name:e.target.value})}/></label><label>Логин<input value={current.login||''} onChange={e=>update({login:e.target.value})}/></label><label>Роль<select value={current.role} onChange={e=>update({role:e.target.value})}><option>Администратор</option><option>Преподаватель</option><option>Обучающийся</option></select></label><div className="admin-inline-actions"><button onClick={()=>update({status:current.status==='Заблокирован'?'Активен':'Заблокирован'})}>{current.status==='Заблокирован'?'Разблокировать':'Заблокировать'}</button><button className="danger" disabled={current.role==='Администратор'} onClick={()=>{const next=users.filter(x=>x.id!==current.id);setUsers(next);saveUsers(next);setSelected(next[0]?.id||'');}}>Удалить</button></div></section><section><h3>Права доступа</h3>{['trainings','scenarios','cards','results','users','monitoring'].map(p=><label className="admin-check" key={p}><input type="checkbox" checked={(current.permissions||[]).includes(p)} onChange={e=>update({permissions:e.target.checked?[...(current.permissions||[]),p]:(current.permissions||[]).filter(x=>x!==p)})}/><span>{{trainings:'Управление тренировками',scenarios:'Доступ к сценариям',cards:'Работа с карточками',results:'Просмотр результатов',users:'Управление пользователями',monitoring:'Мониторинг системы'}[p]}</span></label>)}</section><section><h3>Последние действия</h3><p><Dot/> Учётная запись активна</p><p className="admin-muted">Последний вход: {fmt(current.last_login)}</p><p className="admin-muted">Изменения сохраняются локально.</p></section></div>}</>:tab==='roles'?<RoleMatrix/>:<AuditList/>}{add&&<AddUser onClose={()=>setAdd(false)} onAdd={u=>{const next=[...users,u];setUsers(next);saveUsers(next);setSelected(u.id);setAdd(false);}}/>}</Drawer>;
}
function AddUser({onClose,onAdd}){const [name,setName]=useState(''),[login,setLogin]=useState(''),[role,setRole]=useState('Обучающийся');return <Modal title="Добавить пользователя" onClose={onClose}><div className="admin-form"><label>ФИО<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Логин<input value={login} onChange={e=>setLogin(e.target.value)}/></label><label>Роль<select value={role} onChange={e=>setRole(e.target.value)}><option>Обучающийся</option><option>Преподаватель</option><option>Администратор</option></select></label><button className="admin-primary" disabled={!name.trim()||!login.trim()} onClick={()=>onAdd({id:crypto.randomUUID(),name:name.trim(),login:login.trim(),role,status:'Активен',last_login:'',permissions:role==='Администратор'?['users','trainings','scenarios','cards','results','monitoring','system','settings']:[]})}>Создать пользователя</button></div></Modal>}
function RoleMatrix(){return <div className="admin-info-cards"><section><h3>Администратор</h3><p>Полный доступ: пользователи, контент, результаты, мониторинг и настройки.</p></section><section><h3>Преподаватель</h3><p>Создание сценариев и карточек, назначение тренировок и проверка результатов.</p></section><section><h3>Обучающийся</h3><p>Доступ только к назначенным тренировкам и собственным результатам.</p></section></div>}
function AuditList(){return <div className="admin-events"><p>Журнал действий пользователей подключается вместе с серверной авторизацией команды. Демонстрационные события здесь не показываются.</p></div>}

function TrainingsDrawer({model,onClose}){const [search,setSearch]=useState(''),[selected,setSelected]=useState(''),[detail,setDetail]=useState(null);const list=model.trainings.filter(t=>!search||t.title.toLowerCase().includes(search.toLowerCase()));const current=model.trainings.find(t=>t.id===selected)||list[0];return <Drawer title="Тренировки" onClose={onClose}><Tabs value="all" onChange={()=>{}} items={[["all","Все"],["active","Активные"],["done","Завершенные"]]}/><Toolbar search={search} setSearch={setSearch}><button className="admin-primary" onClick={()=>location.assign('/teacher#create-training')}>Создать тренировку</button></Toolbar><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Название</th><th>Преподаватель</th><th>Обучающиеся</th><th>Режим</th><th>Статус</th></tr></thead><tbody>{list.map(t=><tr key={t.id} onClick={()=>setSelected(t.id)} className={t.id===current?.id?'selected':''}><td>{t.title}</td><td>{t.teacher}</td><td>{t.students}</td><td>{t.mode}</td><td><Dot tone={t.status==='Активна'?'green':'gray'}/>{t.status}</td></tr>)}</tbody></table></div>{current?<div className="admin-three"><section><h3>Параметры тренировки</h3><p><b>Название</b><span>{current.title}</span></p><p><b>Группа</b><span>{current.group}</span></p><p><b>Режим</b><span>{current.mode}</span></p><p><b>Статус</b><span>{current.status}</span></p><button onClick={()=>setDetail(current)}>Открыть</button></section><section><h3>Назначенные участники ({current.students})</h3>{[...new Set(current.sessions.map(s=>s.student))].slice(0,9).map(x=><p key={x}>♙ {x}</p>)}</section><section><h3>Ход выполнения</h3><p>Активно: {current.sessions.filter(s=>s.status==='active').length}</p><p>На проверке: {current.sessions.filter(s=>['submitted','pending_teacher'].includes(s.status)).length}</p><p>Завершено: {current.sessions.filter(s=>s.status==='reviewed').length}</p></section></div>:<Empty/>}{detail&&<Modal title={detail.title} onClose={()=>setDetail(null)}><p>{detail.sessions.length} учебных работ.</p><div className="admin-mini-list">{detail.sessions.map(s=><p key={s.id}><span>{s.student}</span><b>{statusLabel[s.status]||s.status}</b></p>)}</div></Modal>}</Drawer>}

function ScenariosDrawer({model,onClose}){const [search,setSearch]=useState(''),[selected,setSelected]=useState('');const list=model.scenarios.filter(x=>!search||(x.title||'').toLowerCase().includes(search.toLowerCase()));const current=model.scenarios.find(x=>x.id===selected)||list[0];return <Drawer title="Сценарии" onClose={onClose}><Tabs value="scenarios" onChange={()=>{}} items={[["scenarios","Сценарии"],["categories","Категории"],["groups","Группы событий"]]}/><Toolbar search={search} setSearch={setSearch}><button className="admin-primary" onClick={()=>location.assign('/teacher#create-training')}>Добавить сценарий</button></Toolbar><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Название</th><th>Категория</th><th>Карточек</th><th>Режим</th><th>Обновлён</th></tr></thead><tbody>{list.map(x=><tr key={x.id} onClick={()=>setSelected(x.id)} className={x.id===current?.id?'selected':''}><td>{x.title||'Без названия'}</td><td>{x.category||'—'}</td><td>{x.task_ids?.length||0}</td><td>{x.mode==='testing'?'Тестирование':'Обучение'}</td><td>{fmt(x.updated_at||x.created_at)}</td></tr>)}</tbody></table></div>{current?<div className="admin-three"><section><h3>Основные параметры</h3><p><b>Название</b><span>{current.title}</span></p><p><b>Карточек</b><span>{current.task_ids?.length||0}</span></p><p><b>Группа</b><span>{current.group||'—'}</span></p><p><b>Локация</b><span>{current.location||'—'}</span></p></section><section><h3>Состав сценария</h3><p>{(current.assignment_task_ids||current.task_ids||[]).length} карточек выбрано для назначения.</p><p className="admin-muted">Каталог сценария хранится отдельно от конкретного запуска.</p></section><section><h3>Версия и изменения</h3><p><Dot/> Актуальная локальная версия</p><p className="admin-muted">Повторное назначение не изменяет исходный каталог.</p></section></div>:<Empty text="Сценарии пока не созданы"/>}</Drawer>}

function CardsDrawer({model,onClose}){const [search,setSearch]=useState(''),[selected,setSelected]=useState('');const list=model.cards.filter(c=>!search||(c.number+' '+c.content?.title).toLowerCase().includes(search.toLowerCase()));const current=model.cards.find(c=>c.id===selected)||list[0];return <Drawer title="Карточки происшествий" onClose={onClose}><Tabs value="cards" onChange={()=>{}} items={[["cards","Карточки"],["review","Проверка"],["archive","Архив"]]}/><Toolbar search={search} setSearch={setSearch}><button className="admin-primary" onClick={()=>location.assign('/cards')}>Открыть мастерскую</button></Toolbar><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>№ карточки</th><th>Название</th><th>Статус</th><th>Источник</th><th>Дата</th></tr></thead><tbody>{list.map(c=><tr key={c.id} className={c.id===current?.id?'selected':''} onClick={()=>setSelected(c.id)}><td>{c.number}</td><td>{c.content?.title}</td><td><Dot tone={c.status==='approved'?'green':'blue'}/>{c.status==='approved'?'Проверена':'Черновик'}</td><td>{['ai','gigachat'].includes(c.provenance?.source)?'ИИ':'Вручную'}</td><td>{fmt(c.updated_at)}</td></tr>)}</tbody></table></div>{current?<div className="admin-three"><section><h3>Сведения по карточке</h3><p><b>№</b><span>{current.number}</span></p><p><b>Тип</b><span>{current.content?.title}</span></p><p><b>Статус</b><span>{current.status}</span></p></section><section><h3>Классификация</h3><p>Кодов: {current.content?.class_ids?.length||0}</p><p>Служб: {current.content?.services?.length||0}</p><p>Главная служба: {current.content?.main_service||'—'}</p></section><section><h3>Последние действия</h3>{(current.history||[]).slice(-4).reverse().map((h,i)=><p key={i}><Dot tone="blue"/>{h.text}<small>{fmt(h.at)}</small></p>)}</section></div>:<Empty text="Карточки пока не созданы"/>}</Drawer>}

function ResultsDrawer({data,onClose}){const [tab,setTab]=useState('students'),[search,setSearch]=useState('');const rows=data.sessions.filter(s=>['submitted','pending_teacher','reviewed'].includes(s.status)&&(!search||(s.student+' '+s.title).toLowerCase().includes(search.toLowerCase())));const graded=rows.filter(x=>x.grade!=null),avg=graded.length?(graded.reduce((a,b)=>a+b.grade,0)/graded.length).toFixed(1):'—';return <Drawer title="Результаты" onClose={onClose}><Tabs value={tab} onChange={setTab} items={[["students","По обучающимся"],["trainings","По тренировкам"],["analytics","Аналитика"]]}/><Toolbar search={search} setSearch={setSearch}><button className="admin-primary" onClick={()=>location.assign('/teacher#results')}>Открыть проверку</button></Toolbar>{tab!=='analytics'?<><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Обучающийся</th><th>Тренировка</th><th>Результат</th><th>Статус</th><th>Дата</th></tr></thead><tbody>{rows.map(s=><tr key={s.id}><td>{s.student}</td><td>{s.title}</td><td>{s.grade?`${s.grade} / 5`:'—'}</td><td>{statusLabel[s.status]||s.status}</td><td>{fmt(s.updated_at||s.created_at)}</td></tr>)}</tbody></table></div><div className="admin-three"><section><h3>Сводка</h3><p><b>Всего работ</b><span>{rows.length}</span></p><p><b>Проверено</b><span>{graded.length}</span></p><p><b>Средняя оценка</b><span>{avg}</span></p></section><section><h3>Типовые состояния</h3><p><Dot tone="green"/> Завершено: {rows.filter(x=>x.status==='reviewed').length}</p><p><Dot tone="orange"/> Требует проверки: {rows.filter(x=>x.status!=='reviewed').length}</p></section><section><h3>Рекомендации ИИ</h3><p>Используйте предварительную проверку в панели преподавателя, а итоговое решение подтверждайте вручную.</p></section></div></>:<Analytics rows={rows}/>}</Drawer>}
function Analytics({rows}){const grouped=[...new Map(rows.map(x=>[x.student,[]]))];rows.forEach(x=>grouped.find(([k])=>k===x.student)?.[1].push(x));return <div className="admin-analytics"><h3>Сводка по обучающимся</h3>{grouped.map(([name,list])=><div key={name}><b>{name}</b><span>{list.length} работ</span><progress value={list.filter(x=>x.status==='reviewed').length} max={Math.max(1,list.length)}/></div>)}</div>}

function MonitoringDrawer({data,onClose}){const [tab,setTab]=useState('ai'),[checked,setChecked]=useState({state:'unchecked',message:'Не проверен'});const check=async()=>{setChecked({state:'checking',message:'Проверка…'});try{const result=await api('ai_status');setChecked({state:result.state||'available',message:result.message||'API отвечает'});}catch(e){setChecked({state:'error',message:e.message});}};const tone=checked.state==='available'?'green':checked.state==='error'?'red':'gray';return <Drawer title="Мониторинг" onClose={onClose}><Tabs value={tab} onChange={setTab} items={[["components","Компоненты"],["ai","ИИ"],["events","События"]]}/>{tab==='components'?<div className="admin-monitor-list">{[['Локальный сервер',data.error?'Ошибка':'Доступен'],['ИИ-модуль',checked.state==='available'?'Доступен':checked.state==='error'?'Ошибка':checked.state==='configured'?'Настроен':'Не проверен'],['Хранилище карточек','Не проверено'],['Учебные сессии',data.error?'Ошибка':'Данные получены'],['Интерфейс','Открыт']].map(([a,b])=><p key={a}><span>{a}</span><b><Dot tone={b==='Нормально'||b==='Доступен'?'green':b==='Ошибка'?'red':'gray'}/>{b}</b></p>)}</div>:tab==='ai'?<><section className="admin-llm-card"><header><h3>ИИ-сервис</h3><span><Dot tone={tone}/> подключение настраивается локальным ключом</span></header><div className="admin-llm-row"><div><b>Внешний ИИ</b><small>API-подключение</small></div><div><b>Статус</b><span><Dot tone={tone}/>{checked.state==='available'?'API отвечает':checked.state==='configured'?'Настроен':checked.state==='error'?'Ошибка':checked.message}</span></div><button disabled={checked.state==='checking'} onClick={check}>Проверить ИИ</button></div>{['available','configured','error'].includes(checked.state)&&<p className="admin-note">{checked.message}</p>}</section><section className="admin-llm-card"><h3>Параметры подключения</h3><p>Ключ ИИ хранится в <code>config.local.json</code> на текущем компьютере и не включён в передаваемый ZIP.</p><p>Выберите провайдера, API-ключ и модель через <code>CHANGE_AI_KEY.cmd</code>, затем перезапустите приложение. Для GigaChat при ошибке сертификата используйте <code>PREPARE_AI_CONNECTION.cmd</code>.</p><button onClick={()=>alert('Откройте CHANGE_AI_KEY.cmd в папке программы, выберите провайдера и введите API-ключ. Сохраните настройки и перезапустите приложение.')}>Как изменить ключ</button></section></>:<div className="admin-events"><p><Dot tone="blue"/><strong>Мониторинг открыт</strong><span>сейчас</span></p><p><Dot/><strong>Сервер интерфейса отвечает</strong><span>сейчас</span></p></div>}</Drawer>}

function SystemDrawer({model,onClose}){const [confirm,setConfirm]=useState(false);return <Drawer title="Управление системой" onClose={onClose}><div className="admin-system-grid"><section><h3>Состояние данных</h3><p><b>Пользователей</b><span>{model.users.length}</span></p><p><b>Сценариев</b><span>{model.scenarios.length}</span></p><p><b>Карточек</b><span>{model.cards.length}</span></p><p><b>Тренировок</b><span>{model.trainings.length}</span></p></section><section><h3>Обслуживание</h3><button onClick={()=>location.reload()}>Обновить интерфейс</button><button onClick={()=>setConfirm(true)}>Очистить локальный кэш интерфейса</button><button onClick={()=>alert('Используйте RESTART.cmd из папки программы.')}>Перезапустить сервер</button></section><section><h3>Экспорт</h3><button onClick={()=>{const blob=new Blob([JSON.stringify({users:model.users,scenarios:model.scenarios,cards:model.cards},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='admin-export.json';a.click();}}>Экспорт локальных данных</button></section></div>{confirm&&<Modal title="Очистить только кэш интерфейса?" onClose={()=>setConfirm(false)}><p>Учебные карточки и сценарии останутся. Будут очищены только временные настройки административных таблиц.</p><button className="admin-primary" onClick={()=>{sessionStorage.clear();location.assign('/admin-login');}}>Продолжить</button></Modal>}</Drawer>}

function SettingsDrawer({onClose}){const [tab,setTab]=useState('general'),[name,setName]=useState(localStorage.getItem('giik.system.name')||'ИИ-тренажёр 112'),[notice,setNotice]=useState('');return <Drawer title="Настройки" onClose={onClose}><Tabs value={tab} onChange={setTab} items={[["general","Общие"],["security","Безопасность"],["integrations","Интеграции"],["notifications","Уведомления"]]}/>{tab==='general'?<div className="admin-settings"><label>Название системы<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Часовой пояс<select><option>Системный часовой пояс</option><option>UTC+3 Москва</option><option>UTC+7 Красноярск</option></select></label><label>Язык интерфейса<select><option>Русский</option></select></label><label>Формат даты<select><option>ДД.ММ.ГГГГ</option></select></label><button className="admin-primary admin-wide" onClick={()=>{localStorage.setItem('giik.system.name',name);setNotice('Настройки сохранены.');}}>Сохранить изменения</button>{notice&&<p className="admin-note">{notice}</p>}</div>:<ToggleSettings tab={tab}/>}</Drawer>}
function ToggleSettings({tab}){return <div className="admin-toggle-list"><p>Настройки безопасности, базы данных и системных уведомлений подключаются к серверу команды. Локальные переключатели не меняют работу системы.</p></div>}

function Dashboard({data,model,onOpen}){
 const warnings=(data.error?1:0)+(model.cards.some(c=>c.status!=='approved')?1:0), reviewed=data.sessions.filter(s=>s.status==='reviewed').length;
 return <main className="admin-main"><h1>Главная администратора</h1><p className="admin-subtitle">Сводка по объектам приложения</p><div className="admin-kpis">{[['users','Пользователи',model.users.length],['scenarios','Учебные сценарии',model.scenarios.length],['cards','Учебные карточки',model.cards.length],['trainings','Тренировки',model.trainings.length],['monitoring','Предупреждения',warnings]].map(([k,l,v])=><button key={k} onClick={()=>onOpen(k)}><span>{l}</span><strong>{v}</strong><i>›</i></button>)}</div><div className="admin-dashboard-grid"><section className="admin-panel admin-system"><header>Состояние системы</header><table><thead><tr><th>Компонент</th><th>Состояние</th><th>Последняя проверка</th><th>Метрика</th></tr></thead><tbody>{[['АРМ-112','Открыт','Интерфейс доступен'],['ИИ-модуль','Не проверен','Проверить в мониторинге'],['Учебные данные',data.error?'Ошибка':'Данные получены',`${data.sessions.length} работ`],['Карточки','Не проверено',`${model.cards.length} шт.`],['Сценарии','Данные получены',`${model.scenarios.length} шт.`]].map(([a,b,c])=><tr key={a}><td>{a}</td><td><Dot tone={b==='Нормально'?'green':b==='Не проверен'?'gray':'red'}/>{b}</td><td>{new Date().toLocaleString('ru-RU')}</td><td>{c}</td></tr>)}</tbody></table></section><section className="admin-panel admin-llm-summary"><header>ИИ-сервисы</header><div><b>Внешний ИИ</b><span><Dot tone="gray"/>Не проверен</span><small>Проверка выполняется в мониторинге</small></div><div><b>Маршрутизация запросов</b><span>Основная модель</span><small>Ключ задаётся локально</small></div><button onClick={()=>onOpen('monitoring')}>Открыть мониторинг</button></section><section className="admin-panel admin-events-panel"><header>Последние системные события</header>{[['Пользователи','Административная панель открыта'],['Тренировки',`Активных работ: ${data.sessions.filter(s=>s.status==='active').length}`],['Результаты',`Проверено работ: ${reviewed}`],['Карточки',`Утверждено: ${model.cards.filter(c=>c.status==='approved').length}`]].map(([a,b],i)=><p key={b}><span>{new Date(Date.now()-i*600000).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</span><b>{a}</b><em>{b}</em><Dot tone="blue"/></p>)}</section><section className="admin-panel admin-warning-panel"><header>Системные предупреждения</header>{warnings?<><article><Dot tone="orange"/><div><b>Есть элементы, требующие внимания</b><p>{model.cards.filter(c=>c.status!=='approved').length} карточек ещё не утверждено.</p></div></article>{data.error&&<article><Dot tone="red"/><div><b>Ошибка получения данных</b><p>{data.error}</p></div></article>}</>:<article><Dot/><div><b>Предупреждений нет</b><p>Критические компоненты отвечают штатно.</p></div></article>}</section></div></main>;
}

export default function Admin(){
 const [data,refresh]=useAdminData(),[open,setOpen]=useState(null);seedAdminUser();
 useEffect(()=>{if(!adminSignedIn())location.replace('/admin-login');},[]);
 const model=useMemo(()=>derived(data),[data.sessions,data.tasks,data.scenarios,data.trainings]);
 const name=adminName();
 if(!adminSignedIn())return null;
 return <div className="admin-shell"><aside className="admin-sidebar"><div className="admin-brand"><strong>112</strong><span>ADMIN</span></div><nav>{menu.map(([k,ic,label])=><button key={k} className={(open===k||(!open&&k==='home'))?'active':''} onClick={()=>k==='home'?setOpen(null):setOpen(k)}><i>{ic}</i><span>{label}</span></button>)}</nav><footer><span>v 1.1.0</span><span>© 2026 EDU SIM</span></footer></aside><header className="admin-topbar"><button className="admin-bell" title="Уведомления">♧</button><div className="admin-profile"><span>♙</span><div><b>{name}</b><small>Администратор</small></div></div><button className="admin-exit" title="Выйти" onClick={()=>{adminLogout();location.assign('/');}}>↦</button></header><Dashboard data={data} model={model} onOpen={setOpen}/>{open==='users'&&<UsersDrawer model={model} onClose={()=>setOpen(null)}/>} {open==='trainings'&&<TrainingsDrawer model={model} onClose={()=>setOpen(null)}/>} {open==='scenarios'&&<ScenariosDrawer model={model} onClose={()=>setOpen(null)}/>} {open==='cards'&&<CardsDrawer model={model} onClose={()=>setOpen(null)}/>} {open==='results'&&<ResultsDrawer data={data} onClose={()=>setOpen(null)}/>} {open==='monitoring'&&<MonitoringDrawer data={data} onClose={()=>setOpen(null)}/>} {open==='system'&&<SystemDrawer model={model} onClose={()=>setOpen(null)}/>} {open==='settings'&&<SettingsDrawer onClose={()=>setOpen(null)}/>}</div>;
}
