import {useEffect,useState} from 'react';
import {api} from './api.js';

export default function DispatcherDesk({student}){
 const [desks,setDesks]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notes,setNotes]=useState({}),[chosen,setChosen]=useState({}),[updates,setUpdates]=useState({});
 const refresh=()=>api('training_desk',{student}).then(setDesks).catch(e=>setError(e.message));
 useEffect(()=>{refresh();const timer=setInterval(refresh,5000);return()=>clearInterval(timer);},[student]);
 const act=async fn=>{setBusy(true);setError('');try{await fn();await refresh();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const handoff=desks.filter(d=>d.role!=='operator'&&d.status==='active');
 if(!handoff.length)return null;
 return <section className="student-panel dispatcher-desk"><h2>Карточки в работе</h2><p>Поступающие карточки обновляются каждые 5 секунд. Вам показаны только карточки вашей роли и службы.</p>{error&&<p role="alert">{error}</p>}{handoff.map(d=><section key={d.id}><h3>{d.title} · {d.role==='dds'?'Диспетчер ДДС':'Диспетчер службы '+d.service}</h3>{d.cards.length?d.cards.map(c=><article key={c.id} className="dispatcher-card"><h4>Карточка {c.id.slice(-6)} · оператор {c.student}</h4><dl>{Object.entries(c.card||{}).filter(([k,v])=>v&&!k.startsWith('_')).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>{d.role==='dds'?<><details><summary>Проверить и исправить поля карточки</summary><div className="dispatcher-fields">{Object.entries(c.card||{}).map(([key,value])=><label key={key}>{c.field_labels?.[key]||({_report:'Описание со слов заявителя',_services:'Привлекаемые службы',_class_ids:'Тип происшествия'})[key]||key}<textarea value={updates[c.id]?.[key]??value} onChange={e=>setUpdates(previous=>({...previous,[c.id]:{...previous[c.id],[key]:e.target.value}}))}/></label>)}</div></details><label>Направить службам (коды через запятую)<input value={chosen[c.id]||''} placeholder="101,103" onChange={e=>setChosen(x=>({...x,[c.id]:e.target.value}))}/></label><button disabled={busy||!chosen[c.id]?.trim()} onClick={()=>act(()=>api('training_route',{resource_id:d.id,card_id:c.id,student,services:(chosen[c.id]||'').split(',').map(x=>x.trim()).filter(Boolean),updates:updates[c.id]||{}}))}>Направить карточку</button></>:<><label>Действия по карточке<textarea value={notes[c.id]||''} onChange={e=>setNotes(x=>({...x,[c.id]:e.target.value}))} placeholder="Какой наряд направлен и что сделано"/></label><button disabled={busy||!notes[c.id]?.trim()} onClick={()=>act(()=>api('training_service_action',{resource_id:d.id,card_id:c.id,student,text:notes[c.id]}))}>Зафиксировать действия</button></>}</article>):<p>Новых карточек для вашей роли пока нет.</p>}</section>)}</section>;
}
