import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.AI_TEST_PLAYWRIGHT||'playwright');
const server=spawn(process.env.AI_TEST_PYTHON||'python',['-u','-c',"exec(open('tests/ui_fixture.py',encoding='utf-8').read())"],{env:{...process.env,PYTHONUTF8:'1',AI_TEST_REST_ONLY:'1'}});
let out='',err='';server.stdout.on('data',b=>out+=b);server.stderr.on('data',b=>err+=b);
const launch={headless:true};
if(process.env.AI_TEST_BROWSER_PATH)Object.assign(launch,{executablePath:process.env.AI_TEST_BROWSER_PATH,args:['--no-sandbox','--disable-dev-shm-usage']});
let browser;
try{
 browser=await chromium.launch(launch);
 for(let i=0;i<200&&!out.includes('http://');i++)await new Promise(r=>setTimeout(r,50));
 const base=out.match(/http:\/\/127\.0\.0\.1:\d+/)?.[0];assert.ok(base,err);
 const page=await browser.newPage({viewport:{width:1550,height:1050}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.goto(base+'/teacher#create-training');await page.locator('.classroom-builder').waitFor();
 const task=await page.evaluate(async()=>{const api=globalThis.TrainingAPI.api;
  const content=(await api('card_generate',{topic:'Учебный пожар',category:'1',index:1,total:1})).content;
  content.fields.phone_aon='+7 (000) 111-22-33';
  const caller_scenario={version:1,phone_callback:'+7 (000) 444-55-66'};
  const reference=await api('card_reference',{content,caller_scenario});
  return api('card_approve',{content,reference,caller_scenario,teacher:'Преподаватель',reference_checked:true,publish_training:true});
 });
 assert.ok(task.task_id);
 await page.reload();await page.locator('.classroom-builder').waitFor();
 await page.locator('.classroom-settings input[required]').fill('Занятие');
 await page.locator('.classroom-choices input[type=checkbox]').first().check();
 await page.getByRole('button',{name:/Создать тренировку и открыть комнату/}).click();
 await page.locator('.teacher-lobby').waitFor();
 await page.getByRole('button',{name:/Добавить 4 примера/}).click();
 await page.locator('.lobby-person').first().waitFor();
 for(const [index,role] of [[0,'Оператор 112'],[1,'Диспетчер 112'],[2,'Диспетчер службы'],[3,'Диспетчер службы']]){
  const person=page.locator('.lobby-person').nth(index);
  await person.locator('.lobby-avatar-button').click();
  await person.locator('.lobby-role-menu').getByRole('button',{name:role,exact:true}).click();
  await person.locator('.lobby-role').filter({hasText:role}).waitFor();
 }
 await page.getByRole('button',{name:/Начать тренировку/}).click();
 const training=await page.evaluate(async()=>{const rows=await globalThis.TrainingAPI.api('training_list');return rows[0];});
 assert.equal(training.status,'active');
 await page.goto(base+'/student');await page.evaluate(()=>localStorage.setItem('giik.student.profile.v1',JSON.stringify({name:'Алексей Иванов'})));await page.reload();
 await page.locator('[data-student-row]').first().waitFor();
 await page.getByRole('button',{name:'Открыть вызов'}).first().click();
 await page.locator('.student-incoming-popover #student-answer-call').waitFor();
 assert.equal(await page.locator('.student-call-chat').count(),0);
 await page.locator('#student-answer-call').click();
 await page.locator('.student-call-chat.is-open').waitFor();
 await page.locator('.student-call-turn.caller').first().waitFor();
 const session=await page.evaluate(async(id)=>globalThis.TrainingAPI.api('student_action',{student:'Алексей Иванов',id,operation:'student',full_form:true}),training.cards[0].operator_session_id);
 assert.equal(session.status,'active');
 const card={...session.card,_report:'Горит дом',_services:'["101"]',_main_service:'101'};
 await page.evaluate(async({id,card})=>globalThis.TrainingAPI.api('student_action',{student:'Алексей Иванов',id,operation:'submit',full_form:true,card}),{id:session.id,card});
 await page.evaluate(()=>localStorage.setItem('giik.student.profile.v1',JSON.stringify({name:'Мария Петрова'})));await page.reload();
 await page.getByText('Карточки в работе').waitFor();
 await page.getByText('Карточка '+training.cards[0].id.slice(-6)).waitFor();
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({result:'passed',training:training.id,card:training.cards[0].id}));
}finally{await browser?.close();server.kill();}
