import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const {chromium}=createRequire(import.meta.url)('playwright');
const server=spawn(process.env.AI_TEST_PYTHON||'python',['-u','-c',"exec(open('tests/ui_fixture.py',encoding='utf-8').read())"],{env:{...process.env,PYTHONUTF8:'1'}});
let out='',err='';server.stdout.on('data',b=>out+=b);server.stderr.on('data',b=>err+=b);
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 for(let i=0;i<100&&!out.includes('http://');i++)await new Promise(r=>setTimeout(r,50));
 const url=out.match(/http:\/\/127\.0\.0\.1:\d+/)?.[0];assert.ok(url,err);
 const page=await browser.newPage({viewport:{width:1900,height:1024}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto(url);await page.getByRole('link',{name:'Войти',exact:true}).click();await page.waitForFunction(()=>document.body.dataset.journalReady==='true');
 await page.getByText('Пока нет карточек',{exact:true}).waitFor();
 assert.equal(await page.locator('#journal-new').count(),1);
 assert.equal(await page.locator('.teacher-sidebar a').count(),8);
 await fs.mkdir('test-output',{recursive:true});
 await page.screenshot({path:'test-output/teacher-desktop.png',fullPage:true});
 await page.locator('[data-section=settings]').click();await page.locator('#profile-input').fill('Преподаватель Тестов');
 await page.getByRole('button',{name:'Сохранить',exact:true}).click();
 assert.equal(await page.locator('#profile-name').textContent(),'Преподаватель Тестов');
 await page.locator('[data-section=cards]').click();await page.waitForFunction(()=>document.body.dataset.journalReady==='true');await page.locator('#journal-new').click();await page.waitForFunction(()=>document.body.dataset.ready==='true');
 await page.locator('#new-card').click();await page.locator('#card-title').fill('Сохранённая карточка');
 await page.locator('[data-section=home]').click();await page.waitForFunction(()=>document.body.dataset.journalReady==='true');
 await page.locator('[data-section=cards]').click();await page.waitForFunction(()=>document.body.dataset.journalReady==='true');await page.locator('.journal-number').click();await page.waitForFunction(()=>document.body.dataset.ready==='true');
 assert.equal(await page.locator('#card-title').inputValue(),'Сохранённая карточка');
 await page.locator('[data-section=home]').click();await page.waitForFunction(()=>document.body.dataset.journalReady==='true');
 await page.locator('[data-section=scenarios]').click();await page.getByRole('heading',{name:'Сценарии',exact:true}).waitFor();
 await page.locator('[data-section=students]').click();await page.getByRole('heading',{name:'Обучающиеся',exact:true}).waitFor();
 assert.ok((await page.locator('main').textContent()).includes('Назначение групп'));
 await page.locator('[data-section=results]').click();await page.getByRole('link',{name:'Открыть проверку работ'}).click();
 await page.waitForFunction(()=>document.body.getAttribute('aria-busy')==='false');
 assert.ok((await page.locator('#heading').textContent()).includes('Проверка'));
 await page.goto(url);await page.getByRole('link',{name:'Войти',exact:true}).click();await page.waitForFunction(()=>document.body.dataset.journalReady==='true');
 await page.locator('#teacher-exit').click();await page.locator('#teacher-close').click();
 await page.getByRole('link',{name:'Войти',exact:true}).waitFor();
 assert.equal(await page.locator('input').count(),0);
 await page.screenshot({path:'test-output/welcome-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.screenshot({path:'test-output/welcome-mobile.png',fullPage:true});
 await page.getByRole('link',{name:'Войти',exact:true}).click();await page.waitForFunction(()=>document.body.dataset.journalReady==='true');
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.locator('.teacher-menu').click();await page.locator('[data-section=messages]').click();
 assert.equal(await page.locator('.teacher-sidebar').isVisible(),false);
 await page.locator('.teacher-menu').click();await page.locator('[data-section=home]').click();
 await page.screenshot({path:'test-output/teacher-mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);console.log('PASS: teacher design, navigation, existing workshop persistence, profile, mobile menu, exit/return, training links.');
}finally{server.kill();await browser.close();}
