import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const {chromium}=createRequire(import.meta.url)('playwright');
const server=spawn(process.env.AI_TEST_PYTHON||'python',['-u','-c',"exec(open('tests/ui_fixture.py',encoding='utf-8').read())"],{env:{...process.env,PYTHONUTF8:'1'}});
let out='',err='';server.stdout.on('data',b=>out+=b);server.stderr.on('data',b=>err+=b);
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 for(let i=0;i<100&&!out.includes('http://');i++)await new Promise(r=>setTimeout(r,50));
 const url=out.match(/http:\/\/127\.0\.0\.1:\d+/)?.[0];assert.ok(url,err);
 const page=await browser.newPage({viewport:{width:1500,height:1100}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.goto(url+'/cards');await page.waitForFunction(()=>document.body.dataset.ready==='true');
 const stored=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('giik.card-workshop.v1')));
 const finished=()=>page.waitForFunction(()=>document.querySelector('#generate').disabled===false);
 const referenceReady=async()=>{await page.locator('#generate-reference').click();await finished();await page.locator('#reference-reviewed').check();};
 await page.locator('#category').selectOption('1');await page.locator('#generate').click();await finished();
 assert.equal((await stored()).cards.length,1);assert.equal(await page.locator('#f-people').inputValue(),'Возможно, человек внутри; не подтверждено');
 await page.locator('#card-title').fill('Пожар в гараже · проверка преподавателем');
 await page.locator('#f-address_text').fill('Учебный город, улица Лесная, 14');
 await page.locator('#f-house').fill('14');await page.locator('#teacher').fill('Глеб');
 await page.locator('#review-note').fill('Проверены сведения, уточнён адрес');
 await referenceReady();await page.locator('#approve').click();await page.locator('#reopen').waitFor();
 assert.equal((await stored()).cards[0].status,'approved');assert.equal(await page.locator('#f-house').isDisabled(),true);
 await page.reload();await page.waitForFunction(()=>document.body.dataset.ready==='true');
 assert.equal(await page.locator('#f-house').inputValue(),'14');
 await page.locator('#reopen').click();await page.locator('#approve').waitFor();
 assert.equal((await stored()).cards[0].review,null);
 assert.equal((await stored()).cards[0].history.find(h=>h.action==='approved').content.fields.house,'14');
 await page.locator('#f-house').fill('15');
 assert.equal((await stored()).cards[0].history.find(h=>h.action==='approved').content.fields.house,'14');
 // Error leaves finished cards intact, and resume continues at the same index.
 await page.locator('#topic').fill('FAIL_ONCE');await page.locator('#count').fill('3');
 await page.locator('#generate').click();await finished();
 assert.equal((await stored()).batch.done,1);assert.equal((await stored()).batch.status,'error');
 await page.locator('#resume').click();await finished();
 assert.equal((await stored()).cards.length,4);assert.equal((await stored()).batch.done,3);
 // Stop applies after the in-flight request, with a resumable queue.
 await page.locator('#topic').fill('SLOW');await page.locator('#count').fill('10');
 await page.locator('#generate').click();await page.locator('#stop').click();await finished();
 assert.equal((await stored()).batch.status,'paused');assert.ok((await stored()).batch.done<10);
 await page.reload();await page.waitForFunction(()=>document.body.dataset.ready==='true');
 assert.equal(await page.locator('#resume').isVisible(),true);
 // A complete 100-card batch uses 100 separate, validated replies.
 const before=(await stored()).cards.length;
 await page.locator('#topic').fill('Проверка большой подборки');await page.locator('#count').fill('100');
 await page.locator('#generate').click();await finished();
 const state=await stored();assert.equal(state.batch.done,100);assert.equal(state.cards.length,before+100);
 assert.equal(new Set(state.cards.map(c=>c.id)).size,state.cards.length);
 await page.locator('#search').fill('Пожар в гараже');assert.equal(await page.locator('.card-item').count(),1);
 await page.locator('.card-item').click();await page.locator('#teacher').fill('Глеб');
 await referenceReady();await page.locator('#approve').click();await page.locator('#reopen').waitFor();
 const downloadPromise=page.waitForEvent('download');await page.locator('#export-all').click();const download=await downloadPromise;
 const exported=JSON.parse(await fs.readFile(await download.path(),'utf8'));assert.equal(exported.cards.length,state.cards.length);
 await fs.mkdir('test-output',{recursive:true});await page.screenshot({path:'test-output/cards-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.screenshot({path:'test-output/cards-mobile.png',fullPage:true});
 await page.locator('#new-card').click();await page.locator('#approve').click();
 await page.waitForFunction(()=>document.querySelector('#notice').classList.contains('error'));
 assert.equal((await stored()).cards[0].status,'draft');
 assert.deepEqual(errors,[]);
 console.log('PASS: generation 1/100, edits, approval, frozen snapshot, reopen, persistence, error/resume, stop, search, JSON export and mobile.');
}finally{server.kill();await browser.close();}
