import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import assert from 'node:assert/strict';
const {chromium}=createRequire(import.meta.url)('playwright');
const server=spawn(process.env.AI_TEST_PYTHON||'python',['-u','-c',"exec(open('tests/ui_fixture.py',encoding='utf-8').read())"],{env:{...process.env,PYTHONUTF8:'1'}});
let out='',err='';server.stdout.on('data',b=>out+=b);server.stderr.on('data',b=>err+=b);
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 for(let i=0;i<100&&!out.includes('http://');i++)await new Promise(r=>setTimeout(r,50));
 const url=out.match(/http:\/\/127\.0\.0\.1:\d+/)?.[0];assert.ok(url,err);
 const page=await browser.newPage({viewport:{width:1900,height:1120}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 const call=(action,payload={})=>page.evaluate(async({action,payload})=>{const r=await fetch('/api',{method:'POST',headers:{'Content-Type':'application/json','X-UI-Token':document.querySelector('meta[name=ui-token]').content},body:JSON.stringify({action,payload})});const d=await r.json();if(d.error)throw Error(d.error);return d.result;},{action,payload});
 const ready=()=>page.waitForFunction(()=>document.body.dataset.studentReady==='true');
 await page.goto(url);await page.locator('#role-student').click();await page.getByRole('link',{name:'Войти',exact:true}).click();await ready();
 assert.equal(new URL(page.url()).pathname,'/student');
 await page.getByText('Тренировок пока нет.',{exact:false}).waitFor();
 const task=await call('create',{sample:true,level:'medium',workflow:'caller'});
 await call('approve',{id:task.id,teacher:'Тестов П.П.'});
 const dds=await call('create',{sample:true,level:'hard',workflow:'dds'});
 await call('approve',{id:dds.id,teacher:'Тестов П.П.'});
 await page.reload();await ready();assert.equal(await page.locator('[data-student-row]').count(),2);
 await page.screenshot({path:'test-output/student-list.png',fullPage:true});
 await page.locator('#student-level').selectOption('hard');await page.getByRole('button',{name:'Найти',exact:true}).click();assert.equal(await page.locator('[data-student-row]').count(),1);
 await page.getByRole('button',{name:'Сбросить',exact:true}).click();
 await page.locator(`[data-student-row="${task.id}"]`).getByRole('button',{name:'Начать',exact:true}).click();
 await page.locator('#student-to-launch').waitFor();await page.screenshot({path:'test-output/student-details.png',fullPage:true});
 await page.locator('#student-to-launch').click();await page.locator('#student-start-confirm').waitFor();await page.screenshot({path:'test-output/student-launch.png',fullPage:true});
 await page.locator('#student-start-confirm').click();await page.locator('#student-question').waitFor();
 await page.locator('[data-student-field=address]').fill('Лесная, 14');
 await page.locator('#student-question').fill('Есть люди внутри?');await page.getByRole('button',{name:'Отправить',exact:true}).click();
 await page.getByRole('log').getByText('Муж заходил в гараж.',{exact:false}).waitFor();
 assert.equal(await page.locator('[data-student-field=address]').inputValue(),'Лесная, 14');
 await page.reload();await ready();await page.locator('#student-continue').click();await page.locator('#student-question').waitFor();
 assert.equal(await page.locator('[data-student-field=address]').inputValue(),'Лесная, 14');
 await page.screenshot({path:'test-output/student-card.png',fullPage:true});
 await page.locator('#student-submit').click();await page.locator('#student-download-report').waitFor();
 await page.getByText('Работа передана преподавателю',{exact:true}).waitFor();
 assert.equal(await page.locator('.student-compare').getByText('Доступен после проверки',{exact:true}).count(),39);
 const overview=await call('student_overview',{student:'Обучающийся'}),sid=overview.sessions[0].id;
 await call('assess',{id:sid});
 const review=await call('review',{id:sid});
 const decisions=Object.fromEntries(Object.keys(review.assessment.fields).map(k=>[k,{decision:'agree',comment:'Проверено преподавателем'}]));
 await call('finalize',{id:sid,teacher:'Тестов П.П.',grade:4,conclusion:'Хорошая работа. Уточняйте сведения о людях.',decisions});
 await page.reload();await ready();await page.locator('[data-student-section=results]').click();
 await page.locator(`[data-student-row="${sid}"]`).getByRole('button',{name:'Результат',exact:true}).click();
 await page.getByRole('heading',{name:'Тренировка проверена',exact:true}).waitFor();
 assert.equal(await page.locator('.student-compare').getByText('Доступен после проверки',{exact:true}).count(),0);
 await page.screenshot({path:'test-output/student-result.png',fullPage:true});
 const downloadPromise=page.waitForEvent('download');await page.locator('#student-download-report').click();assert.ok((await downloadPromise).suggestedFilename().endsWith('.json'));
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'test-output/student-mobile.png',fullPage:true});
 await page.setViewportSize({width:1900,height:1120});
 await page.locator('[data-student-section=trainings]').click();
 await page.locator(`[data-student-row="${dds.id}"]`).getByRole('button',{name:'Начать',exact:true}).click();
 await page.locator('#student-to-launch').click();await page.locator('#student-start-confirm').click();
 await page.getByRole('button',{name:'Позвонить службе',exact:true}).waitFor();
 assert.equal(await page.locator('#student-question').isDisabled(),true);
 await page.getByRole('button',{name:'Позвонить службе',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('#student-question').disabled);
 await page.locator('#student-question').fill('Передаю сообщение о повреждении трубы.');
 await page.getByRole('button',{name:'Отправить',exact:true}).click();
 await page.getByRole('log').getByText('Назовите точный адрес происшествия.',{exact:false}).waitFor();
 assert.equal(await page.getByRole('button',{name:'Подсказка',exact:true}).isDisabled(),true);
 await page.getByRole('button',{name:'Завершить звонок',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#student-question').disabled);
 await page.locator('[data-student-section=messages]').click();await page.getByRole('heading',{name:'Сообщений пока нет',exact:true}).waitFor();
 await page.locator('[data-student-section=profile]').click();await page.locator('#student-profile-name').fill('Другой ученик');await page.getByRole('button',{name:'Сохранить профиль',exact:true}).click();await ready();
 await page.locator('[data-student-section=results]').click();assert.equal(await page.locator('[data-student-row]').count(),0);
 await page.locator('#student-exit').click();await page.locator('#role-teacher').click();await page.getByRole('link',{name:'Войти',exact:true}).click();await page.waitForFunction(()=>document.body.dataset.journalReady==='true');
 assert.deepEqual(errors,[]);console.log('PASS: roles, student list/filters, details/launch, dialogue, draft resume, submission, teacher-only reference release, results/download, mobile/profile and teacher return.');
}finally{server.kill();await browser.close();}
