import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import assert from 'node:assert/strict';
const {chromium}=createRequire(import.meta.url)('playwright');
const server=spawn(process.env.AI_TEST_PYTHON||'python',['-u','-c',"exec(open('tests/ui_fixture.py',encoding='utf-8').read())"],{env:{...process.env,PYTHONUTF8:'1'}});
let out='',err='';server.stdout.on('data',b=>out+=b);server.stderr.on('data',b=>err+=b);
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 for(let i=0;i<100&&!out.includes('http://');i++)await new Promise(r=>setTimeout(r,50));
 const url=out.match(/http:\/\/127\.0\.0\.1:\d+/)?.[0];assert.ok(url,err);
 const page=await browser.newPage({viewport:{width:1900,height:1100}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.goto(url+'/cards');await page.waitForFunction(()=>document.body.dataset.ready==='true');
 const idle=()=>page.waitForFunction(()=>!document.querySelector('#generate').disabled);
 const current=()=>page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('giik.card-workshop.v1'));return s.cards.find(c=>c.id===s.selected);});
 await page.locator('#generate').click();await idle();
 assert.ok((await current()).reference);
 assert.equal(await page.locator('#composer').getAttribute('open'),null);
 await page.locator('#dock-preview').click();
 await page.screenshot({path:'test-output/incident-layout-desktop.png'});
 const cardBox=await page.locator('#f-house').locator('..').boundingBox(),left=await page.locator('.incident-left').boundingBox(),right=await page.locator('.incident-right').boundingBox();
 assert.ok(right.x>=left.x+left.width,'Address and classification side by side');
 await page.locator('#f-house').fill('14');
 await page.locator('#open-reference').click();
 assert.equal(await page.locator('#r-house').inputValue(),'Неизвестно');
 const refBox=await page.locator('#r-house').locator('..').boundingBox();assert.ok(Math.abs(cardBox.x-refBox.x)<1,'Field stays in same column');
 await page.locator('#r-house').fill('Не указан');
 assert.equal((await current()).content.fields.house,'14','Reference edit does not change card');
 assert.equal((await current()).reference.answer.expected_fields.house.value,'Не указан');
 await page.locator('#generate-reference').click();await idle();
 await page.locator('#reference-reviewed').check();await page.locator('#teacher').fill('Преподаватель');
 await page.locator('#approve').click();await page.locator('#reopen').waitFor();
 assert.equal(await page.locator('#r-house').isDisabled(),true);
 await page.locator('#dock-preview').click();await page.screenshot({path:'test-output/incident-reference-desktop.png'});
 await page.locator('#card-tab').click();assert.equal(await page.locator('#f-house').inputValue(),'14');
 assert.equal(await page.locator('#f-house').isDisabled(),true);
 await page.locator('#reopen').click();
 await page.locator('.incident-type .incident-group select').selectOption('17');
 await page.locator('.incident-type').getByRole('button',{name:'Человек в воде, на льдине',exact:true}).click();
 await page.locator('.incident-type').getByRole('button',{name:'Всплыл утопленник',exact:true}).click();
 assert.deepEqual((await current()).content.class_ids,['17070500']);
 assert.ok((await current()).content.services.includes('103'));
 await page.locator('#open-reference').click();assert.equal(await page.locator('#reference-reviewed').isDisabled(),true);
 assert.equal(await page.locator('[data-dock-service="103"]').count(),0,'Reference shows its saved service composition');
 await page.locator('#dock-other-services').click();assert.equal(await page.locator('[data-service="103"]').isDisabled(),true);
 await page.keyboard.press('Escape');
 await page.setViewportSize({width:390,height:844});await page.locator('#dock-preview').click();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.screenshot({path:'test-output/incident-layout-mobile.png'});
 await page.reload();await page.waitForFunction(()=>document.body.dataset.ready==='true');
 assert.equal(await page.locator('#f-house').inputValue(),'14');
 assert.deepEqual((await current()).content.class_ids,['17070500']);
 assert.deepEqual(errors,[]);console.log('PASS: shared form layout, isolated reference edits, approval lock, dependent type change/services, persistence and mobile.');
}finally{server.kill();await browser.close();}
