import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {searchAddresses} from '../frontend/src/address-search.js';
const addresses=JSON.parse(readFileSync('ui/geo/addresses.json','utf8')).addresses;
assert.ok(searchAddresses(addresses,'королева 7а').some(x=>x.house==='7А'));
assert.ok(searchAddresses(addresses,'королва 7а').some(x=>x.house==='7А'));
assert.equal(searchAddresses(addresses,'королева 987654').length,0);
assert.equal(searchAddresses(addresses,'королева')[0].kind,'street');
const {chromium}=createRequire(import.meta.url)('playwright');
const server=spawn(process.env.AI_TEST_PYTHON||'python',['-u','-c',"exec(open('tests/ui_fixture.py',encoding='utf-8').read())"],{env:{...process.env,PYTHONUTF8:'1'}});
let out='',err='';server.stdout.on('data',b=>out+=b);server.stderr.on('data',b=>err+=b);
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 for(let i=0;i<100&&!out.includes('http://');i++)await new Promise(r=>setTimeout(r,50));
 const url=out.match(/http:\/\/127\.0\.0\.1:\d+/)?.[0];assert.ok(url,err);
 const page=await browser.newPage({viewport:{width:1600,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.goto(url+'/cards');await page.waitForFunction(()=>document.body.dataset.ready==='true');
 await page.locator('#generate').click();await page.waitForFunction(()=>!document.querySelector('#generate').disabled);
 const address=page.getByRole('combobox',{name:'Поиск адреса · Железногорск, Красноярский край'});
 await address.fill('королва 7а');await page.locator('.address-suggestions [role=option]').first().click();
 assert.equal(await page.locator('#f-house').inputValue(),'7А');assert.ok(await page.locator('#f-latitude').inputValue());
 assert.equal(await page.locator('.address-map').getAttribute('data-map-kind'),'building');
 await page.locator('#f-house').fill('999');assert.equal(await page.locator('#f-latitude').inputValue(),'');assert.equal(await page.locator('.address-map').getAttribute('data-map-kind'),'none');
 await address.fill('королева');await page.locator('.address-suggestions [role=option]').first().click();assert.equal(await page.locator('#f-house').inputValue(),'');assert.equal(await page.locator('.address-map').getAttribute('data-map-kind'),'street');
 await address.fill('королева 7а');await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');
 await page.locator('#training-opening').fill('Помогите, из гаража идёт дым!');
 await page.locator('#open-reference').click();await page.locator('#generate-reference').click();await page.waitForFunction(()=>!document.querySelector('#generate').disabled);
 await page.locator('#reference-reviewed').check();await page.locator('#teacher').fill('Тестовый преподаватель');await page.locator('#approve').click();await page.locator('#reopen').waitFor();
 await page.locator('#card-tab').click();assert.equal(await address.isDisabled(),true);
 const student=await browser.newPage({viewport:{width:1600,height:1100}});student.on('pageerror',e=>errors.push(e.message));student.on('dialog',d=>d.accept());
 await student.addInitScript(()=>{window.micRequests=0;Object.defineProperty(navigator,'mediaDevices',{value:{getUserMedia:async()=>{window.micRequests++;return {getTracks:()=>[{stop(){}}]};}}});window.SpeechRecognition=class {start(){this.onresult({results:[[{transcript:'Кто-нибудь остался внутри?'}]]});this.onend();}abort(){} stop(){this.onend?.();}};});
 await student.goto(url+'/student');await student.waitForFunction(()=>document.body.dataset.studentReady==='true');
 await student.getByRole('button',{name:'Начать',exact:true}).click();await student.locator('#student-to-launch').click();await student.locator('#student-start-confirm').click();
 await student.locator('[data-student-field="street"]').waitFor();
 assert.equal(await student.locator('[data-student-field="street"]').inputValue(),'');
 assert.equal(await student.locator('[data-student-field="house"]').inputValue(),'');
 assert.equal(await student.locator('[data-student-field="phone_callback"]').isDisabled(),true);
 assert.ok((await student.locator('.student-chat').innerText()).includes('Помогите, из гаража идёт дым!'));
 assert.ok(!(await student.locator('.student-chat').innerText()).includes('Муж заходил'));
 await student.locator('#student-microphone').click();assert.equal(await student.evaluate(()=>window.micRequests),1);assert.equal(await student.locator('#student-question').inputValue(),'Кто-нибудь остался внутри?');await student.getByRole('button',{name:'Отправить',exact:true}).click();await student.getByText('Муж заходил внутрь, я не видела, чтобы он вышел.',{exact:false}).waitFor();
 await student.locator('#student-question').fill('Какой телефон для перезвона?');await student.getByRole('button',{name:'Отправить',exact:true}).click();await student.waitForFunction(()=>!document.querySelector('[data-student-field="phone_callback"]').disabled);
 assert.equal(await student.locator('[data-student-field="phone_callback"]').inputValue(),'');
 const phone=(await student.locator('.student-chat').innerText()).match(/\+7 \(000\) \d{3}-\d{2}-\d{2}/)[0];await student.locator('[data-student-field="phone_callback"]').fill(phone);
 await student.getByRole('combobox',{name:'Поиск адреса · Железногорск, Красноярский край'}).fill('королева 7а');await student.locator('.address-suggestions [role=option]').first().click();
 await student.locator('[data-student-field="people"]').fill('Возможно, мужчина внутри; не подтверждено');
 await student.getByRole('button',{name:'Сохранить',exact:true}).first().click();await student.getByText('Карточка сохранена.',{exact:true}).waitFor();
 await student.locator('[data-student-field="street"]').scrollIntoViewIfNeeded();await student.screenshot({path:'test-output/student-full-address.png'});
 await student.setViewportSize({width:390,height:844});assert.equal(await student.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await student.screenshot({path:'test-output/student-full-mobile.png'});
 await student.locator('#student-submit').click();await student.getByRole('heading',{name:'Работа передана преподавателю'}).waitFor();
 await page.goto(url+'/teacher#results');await page.getByRole('button',{name:'Открыть результат: Обучающийся'}).click();await page.getByRole('button',{name:'Открыть карточку',exact:true}).first().click();await page.locator('#teacher-assess').click();await page.locator('#teacher-grade').waitFor();
 assert.ok(await page.locator('[data-decision="phone_callback"]').count());assert.ok(await page.locator('[data-decision="_services"]').count());
 for(const el of await page.locator('[data-decision]').all())await el.selectOption('agree');
 for(const el of await page.locator('[data-decision-note]').all())await el.fill('Проверено преподавателем');
 await page.locator('#teacher-conclusion').fill('Работа проверена.');await page.locator('#teacher-finalize').click();await page.getByText('Итог: 4 / 5',{exact:true}).waitFor();
 assert.deepEqual(errors,[]);console.log('PASS: OSM typo/house/street/clear coordinates; approved card → full student worksheet → AI caller contract → phone disclosure → persistence → submission → full-field AI review → teacher decision; mobile.');
}finally{server.kill();await browser.close();}
