import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import assert from 'node:assert/strict';
const {chromium}=createRequire(import.meta.url)('playwright');
const server=spawn(process.env.AI_TEST_PYTHON||'python',['-u','-c',"exec(open('tests/ui_fixture.py',encoding='utf-8').read())"],{env:{...process.env,PYTHONUTF8:'1'}});
let out='',err='';server.stdout.on('data',b=>out+=b);server.stderr.on('data',b=>err+=b);
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 for(let i=0;i<100&&!out.includes('http://');i++)await new Promise(r=>setTimeout(r,50));
 const url=out.match(/http:\/\/127\.0\.0\.1:\d+/)?.[0];assert.ok(url,err);
 const page=await browser.newPage({viewport:{width:1500,height:1050}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.goto(url+'/cards');await page.waitForFunction(()=>document.body.dataset.ready==='true');
 const current=()=>page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('giik.card-workshop.v1'));return s.cards.find(c=>c.id===s.selected);});
 const idle=()=>page.waitForFunction(()=>!document.querySelector('#generate').disabled);
 await page.locator('#generate').click();await idle();
 assert.ok((await current()).reference,'Reference created automatically with card');
 await page.locator('#teacher').fill('Проверяющий');await page.locator('#approve').click();await idle();
 assert.equal((await current()).status,'draft','Cannot approve without checking reference');
 await page.locator('#open-reference').click();await page.locator('#reference-reviewed').check();
 await page.locator('[data-reference="summary"]').fill('Ответ исправлен преподавателем. Не угадывать число людей.');
 assert.equal(await page.locator('#reference-reviewed').isChecked(),false);
 await page.reload();await page.waitForFunction(()=>document.body.dataset.ready==='true');
 await page.locator('#open-reference').click();
 assert.match(await page.locator('[data-reference="summary"]').inputValue(),/исправлен преподавателем/);
 await page.locator('#card-tab').click();await page.locator('#f-house').fill('14');await page.locator('#approve').click();await idle();
 assert.equal((await current()).status,'draft');assert.match(await page.locator('#notice').innerText(),/изменена/);
 await page.locator('#open-reference').click();
 assert.equal(await page.locator('#reference-reviewed').isDisabled(),true);
 await page.locator('#generate-reference').click();await idle();
 assert.ok((await current()).history.some(h=>h.action==='reference_replaced'&&h.reference.answer.summary.includes('исправлен преподавателем')),JSON.stringify({error:(await current()).reference_error,history:(await current()).history}));
 const previous=(await current()).reference;
 await page.locator('#card-tab').click();const report=await page.locator('#report').inputValue();await page.locator('#report').fill('REF_FAIL');await page.locator('#open-reference').click();
 await page.locator('#generate-reference').click();await idle();
 assert.deepEqual((await current()).reference,previous,'Failure preserves old reference');
 assert.equal((await current()).content.report,'REF_FAIL','Failure preserves card');
 assert.match((await current()).reference_error,/ошибка/);
 await page.locator('#card-tab').click();await page.locator('#report').fill(report);await page.locator('#open-reference').click();await page.locator('#generate-reference').click();await idle();
 await page.locator('#reference-reviewed').check();await page.locator('#approve').click();await page.locator('#reopen').waitFor();
 const approved=await current();assert.ok(approved.history.find(h=>h.action==='approved').reference);
 assert.equal(await page.locator('[data-reference="summary"]').isDisabled(),true);
 await page.evaluate(()=>{const el=document.querySelector('#reference-answer');el.style.scrollMarginTop='160px';el.scrollIntoView();});
 await page.screenshot({path:'test-output/reference-desktop.png'});
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.locator('#reference-answer').scrollIntoViewIfNeeded();await page.screenshot({path:'test-output/reference-mobile.png'});
 await page.locator('#reopen').click();await page.locator('#approve').waitFor();
 await page.locator('[data-reference="summary"]').fill('Новая редакция');
 assert.deepEqual((await current()).history.find(h=>h.action==='approved').reference,approved.reference,'Approved snapshot stays frozen');
 assert.deepEqual(errors,[]);
 console.log('PASS: automatic reference, teacher edits/check, stale rejection, retry after failure, persistence and frozen approval.');
}finally{server.kill();await browser.close();}
