import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const calls=[];
const context={URLSearchParams,AbortController,setTimeout,clearTimeout,document:{querySelector:()=>({content:'ui-test-token'})}};
context.document.querySelector=selector=>selector.includes('ui-token')?{content:'ui-test-token'}:null;
context.fetch=async(url,options)=>{calls.push({url,options});return {ok:true,status:200,headers:{get:()=>null},json:async()=>({data:{ok:true},request_id:'test-request'})};};
vm.createContext(context);
vm.runInContext(fs.readFileSync('ui/api-routes.js','utf8'),context);
vm.runInContext(fs.readFileSync('ui/api-client.js','utf8'),context);
const api=context.TrainingAPI;
assert.equal((await api.api('teacher_dashboard')).ok,true);
assert.equal(calls.at(-1).url,'/api/v1/teacher/dashboard');
assert.equal(calls.at(-1).options.method,'GET');assert.equal(calls.at(-1).options.body,undefined);
await api.api('student_action',{student:'Иванов А/Б',id:'s-123456abcdef',operation:'student',full_form:false});
assert.equal(calls.at(-1).url,'/api/v1/students/'+encodeURIComponent('Иванов А/Б')+'/sessions/s-123456abcdef?full_form=false');
await api.api('student_action',{student:'А',id:'s-123456abcdef',operation:'ask',question:'Где вы?',full_form:true});
assert.equal(calls.at(-1).options.method,'POST');
assert.deepEqual(JSON.parse(calls.at(-1).options.body),{question:'Где вы?',full_form:true});
await api.api('save_task',{id:'t-123456abcdef',title:'Пожар',fields:{}});
assert.equal(calls.at(-1).options.method,'PUT');
assert.deepEqual(JSON.parse(calls.at(-1).options.body),{title:'Пожар',fields:{}});
await assert.rejects(api.api('student_action',{operation:'review'}),e=>e.code==='unknown_operation');
api.configure({baseUrl:'http://127.0.0.1:9010/api/v1',token:'integration-test'});
await api.api('tasks');
assert.equal(calls.at(-1).url,'http://127.0.0.1:9010/api/v1/tasks');
assert.equal(calls.at(-1).options.headers.Authorization,'Bearer integration-test');
assert.equal(calls.at(-1).options.headers['X-UI-Token'],undefined);
let attempts=0;
context.fetch=async()=>{attempts++;return {ok:false,status:409,headers:{get:()=>null},json:async()=>({error:{code:'state_conflict',message:'Работа сдана'},request_id:'trace123'})};};
await assert.rejects(api.api('tasks'),e=>e.status===409&&e.code==='state_conflict'&&e.requestId==='trace123');
assert.equal(attempts,1);
context.fetch=async(_url,options)=>new Promise((_resolve,reject)=>options.signal.addEventListener('abort',()=>reject(Object.assign(new Error(),{name:'AbortError'}))));
await assert.rejects(api.request('GET','/tasks',{}, {timeout:1}),e=>e.code==='timeout');
console.log('REST client: URL/method/payload, encoding, error and timeout checks passed');
