import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import assert from 'node:assert/strict';
const {chromium}=createRequire(import.meta.url)('playwright');
const server=spawn(process.env.AI_TEST_PYTHON||'python',['-u','-c',"exec(open('tests/ui_fixture.py',encoding='utf-8').read())"],{env:{...process.env,PYTHONUTF8:'1'}});
let out='',err='';server.stdout.on('data',b=>out+=b);server.stderr.on('data',b=>err+=b);
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 for(let i=0;i<100&&!out.includes('http://');i++)await new Promise(r=>setTimeout(r,50));
 const url=out.match(/http:\/\/127\.0\.0\.1:\d+/)?.[0];assert.ok(url,err);
 const page=await browser.newPage({viewport:{width:1500,height:1050}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const ready=()=>page.waitForFunction(()=>document.body.dataset.ready==='true');
 const idle=()=>page.waitForFunction(()=>!document.querySelector('#generate').disabled);
 const current=()=>page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('giik.card-workshop.v1'));return s.cards.find(c=>c.id===s.selected);});
 await page.goto(url+'/cards');await ready();await page.locator('#generate').click();await idle();
 const aon=await page.locator('#f-phone_aon').inputValue();
 assert.match(aon,/^\+7 \(000\) \d{3}-\d{2}-\d{2}$/);
 assert.equal(await page.locator('#f-phone_aon').getAttribute('readonly'),'');
 assert.equal((await current()).reference.source_content.fields.phone_aon,aon);
 assert.equal(await page.locator('#f-phone_callback').isDisabled(),true);
 const expected=(await current()).caller_scenario.phone_callback;
 assert.notEqual(expected,aon);assert.equal((await current()).reference.answer.expected_fields.phone_callback.value,expected);
 assert.equal(await page.locator('#f-phone_callback').inputValue(),'');
 const ask=async text=>{if(await page.locator('.incident-dialogue-fold').getAttribute('open')===null)await page.locator('.incident-dialogue-fold>summary').click();await page.locator('#caller-question').fill(text);await page.locator('#ask-caller').click();await idle();};
 await ask('Кто внутри?');assert.equal(await page.locator('#f-phone_callback').isDisabled(),true);
 assert.equal((await current()).caller_dialogue.turns.at(-1).text.includes(expected),false);
 const previous=(await current()).caller_dialogue;
 await ask('FAIL');assert.deepEqual((await current()).caller_dialogue,previous);
 assert.equal(await page.locator('#caller-question').inputValue(),'FAIL');
 await ask('На какой телефон вам перезвонить?');
 assert.equal(await page.locator('#f-phone_callback').isDisabled(),false);
 assert.equal(await page.locator('#f-phone_callback').inputValue(),'','No automatic answer entry');
 assert.ok((await current()).caller_dialogue.turns.at(-1).text.includes(expected));
 await page.locator('#f-phone_callback').fill('+7 (000) 123-45-67 доб. 12');
 await page.locator('#f-phone_scene').fill('+7 (000) 555-00-11');
 await page.reload();await ready();
 assert.equal(await page.locator('#f-phone_aon').inputValue(),aon);
 assert.equal(await page.locator('#f-phone_callback').inputValue(),'+7 (000) 123-45-67 доб. 12');
 assert.equal(await page.locator('#f-phone_scene').inputValue(),'+7 (000) 555-00-11');
 assert.equal(await page.locator('#copy-aon').count(),0);
 await page.locator('#f-phone_callback').fill('+7 (000) 222-33-44');
 await page.locator('#open-reference').click();await page.locator('#generate-reference').click();await idle();
 assert.equal((await current()).content.fields.phone_callback,'+7 (000) 222-33-44');
 assert.equal((await current()).content.fields.phone_aon,aon);
 await page.locator('#reference-reviewed').check();await page.locator('#teacher').fill('Тест');
 await page.locator('#approve').click();await page.locator('#reopen').waitFor();
 const approved=await current();
 await page.locator('#card-tab').click();assert.equal(await page.locator('#f-phone_callback').isDisabled(),true);
 assert.equal(await page.locator('#copy-aon').count(),0);
 await page.locator('#card-library > summary').click();await page.locator('#new-card').click();
 assert.match(await page.locator('#f-phone_aon').inputValue(),/^\+7 \(000\) /);
 assert.equal(await page.locator('#f-phone_callback').inputValue(),'');
 await ask('Ваш телефон?');await page.locator('#f-phone_callback').fill('Другой контакт, уточнить номер');
 // Only old empty/placeholder draft AON is migrated; approval and reference snapshots stay intact.
 await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('giik.card-workshop.v1'));const c=s.cards.find(c=>c.id===s.selected);c.content.fields.phone_aon='Не определён: вымышленная карточка';delete c.telephony;localStorage.setItem('giik.card-workshop.v1',JSON.stringify(s));});
 await page.reload();await ready();const migrated=await current();
 assert.match(migrated.content.fields.phone_aon,/^\+7 \(000\) /);
 assert.equal(migrated.content.fields.phone_callback,'Другой контакт, уточнить номер');
 assert.equal(migrated.history.at(-1).action,'caller_id_simulated');
 assert.deepEqual(await page.evaluate(id=>JSON.parse(localStorage.getItem('giik.card-workshop.v1')).cards.find(c=>c.id===id),approved.id),approved);
 await page.reload();await ready();assert.deepEqual(await current(),migrated);
 await page.locator('#dock-preview').click();await page.screenshot({path:'test-output/phone-desktop.png'});
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.screenshot({path:'test-output/phone-mobile.png'});
 assert.deepEqual(errors,[]);console.log('PASS: simulated AON, hidden callback, GigaChat dialogue, failure retry, manual entry, reference isolation, approval lock, draft migration, persistence and mobile.');
}finally{server.kill();await browser.close();}
