import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import assert from 'node:assert/strict';
const {chromium}=createRequire(import.meta.url)('playwright');
const server=spawn(process.env.AI_TEST_PYTHON||'python',['-u','-c',"exec(open('tests/ui_fixture.py',encoding='utf-8').read())"],{env:{...process.env,PYTHONUTF8:'1'}});
let out='',err='';server.stdout.on('data',b=>out+=b);server.stderr.on('data',b=>err+=b);
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 for(let i=0;i<100&&!out.includes('http://');i++)await new Promise(r=>setTimeout(r,50));
 const url=out.match(/http:\/\/127\.0\.0\.1:\d+/)?.[0];assert.ok(url,err);
 const page=await browser.newPage({viewport:{width:1700,height:1000}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 const call=(action,payload={})=>page.evaluate(async({action,payload})=>{const r=await fetch('/api',{method:'POST',headers:{'Content-Type':'application/json','X-UI-Token':document.querySelector('meta[name=ui-token]').content},body:JSON.stringify({action,payload})});const d=await r.json();if(d.error)throw Error(d.error);return d.result;},{action,payload});
 await page.goto(url+'/teacher#create-training');
 const task=await call('create',{sample:true,level:'medium'});
 await page.reload();await page.locator('#training-title').fill('Пожар в жилом доме — группа 2');
 await page.locator('#training-add-scenario').click();await page.getByRole('dialog').getByRole('checkbox').check();await page.getByRole('button',{name:'Готово',exact:true}).click();
 await page.getByRole('button',{name:'Редактировать сценарий 1'}).click();await page.locator('#task-reference-checked').check();await page.locator('#task-approve').click();await page.getByText('Утверждён · Преподаватель',{exact:true}).waitFor();await page.getByRole('button',{name:'Закрыть окно'}).click();
 await page.locator('#training-add-students').click();await page.locator('#training-student-names').fill('Обучающийся\nУчебный Иванов');await page.getByRole('button',{name:'Добавить в план',exact:true}).click();
 await page.getByLabel('Группа',{exact:true}).fill('Группа 2');
 await page.getByRole('button',{name:'Тестирование',exact:true}).click();await page.locator('#training-save').click();await page.reload();assert.equal(await page.locator('#training-title').inputValue(),'Пожар в жилом доме — группа 2');
 await page.waitForSelector('[data-builder-ready=true]');await page.screenshot({path:'test-output/training-builder.png',fullPage:true});
 await page.locator('#training-launch').click();await page.locator('#training-launch-confirm').click();await page.getByText('Тренировка запущена. Работы появились у обучающихся и в мониторинге.',{exact:true}).waitFor();
 await page.goto(url+'/teacher#monitoring');await page.locator('[data-teacher-row]').first().waitFor();assert.equal(await page.locator('[data-teacher-row]').count(),2);
 await page.getByRole('button',{name:'Обучающийся',exact:true}).click();await page.locator('#teacher-note').fill('Не забудьте уточнить номер дома.');await page.getByRole('button',{name:'Сохранить комментарий',exact:true}).click();await page.getByText('Комментарий сохранён. Итоговая оценка не изменена.',{exact:true}).waitFor();
 await page.screenshot({path:'test-output/training-monitor.png',fullPage:true});
 const data=await call('student_overview',{student:'Обучающийся'}),sid=data.sessions[0].id;
 await page.goto(url+'/student');await page.locator('#student-continue').click();await page.locator('#student-question').waitFor();assert.equal(await page.getByRole('button',{name:'Подсказка',exact:true}).isDisabled(),true);
 await page.locator('[data-student-field=address]').fill('Учебная, 14');await page.locator('#student-submit').click();await page.locator('#student-download-report').waitFor();
 await page.goto(url+'/teacher#results');await page.getByRole('button',{name:'Обучающийся',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#teacher-note')?.value==='Не забудьте уточнить номер дома.');
 await page.locator('.tw-footer').getByRole('button',{name:'Открыть карточку',exact:true}).click();await page.locator('#teacher-assess').click();await page.locator('[data-decision]').first().waitFor();
 for(const select of await page.locator('[data-decision]').all())await select.selectOption('agree');
 for(const input of await page.locator('[data-decision-note]').all())await input.fill('Сопоставлено с разговором.');
 await page.locator('#teacher-conclusion').fill('Адрес уточнён. Нужны дополнительные вопросы.');await page.locator('#teacher-finalize').click();await page.getByText('Итог: 4 / 5',{exact:true}).waitFor();await page.getByRole('button',{name:'Закрыть окно'}).click();
 await page.getByRole('button',{name:'Обучающийся',exact:true}).click();await page.getByText('Адрес уточнён. Нужны дополнительные вопросы.',{exact:true}).waitFor();
 await page.screenshot({path:'test-output/training-results.png',fullPage:true});
 const dl=page.waitForEvent('download');await page.getByRole('button',{name:'Экспорт',exact:true}).click();assert.ok((await dl).suggestedFilename().endsWith('.json'));
 await page.getByRole('button',{name:'Сформировать отчёт',exact:true}).click();await page.getByRole('dialog').getByText('Отчёт по выбранным работам',{exact:true}).waitFor();await page.getByRole('button',{name:'Закрыть окно'}).click();
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'test-output/training-results-mobile.png',fullPage:true});
 await page.setViewportSize({width:1700,height:1000});await page.goto(url+'/teacher#monitoring');await page.getByRole('button',{name:'Учебный Иванов',exact:true}).click();await page.getByRole('button',{name:'Завершить работу досрочно',exact:true}).click();await page.locator('#teacher-finish-reason').fill('Занятие завершено');await page.getByRole('button',{name:'Подтвердить завершение',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('dialog[open]'));
 assert.equal((await call('teacher_dashboard')).sessions.find(s=>s.student==='Учебный Иванов').status,'submitted');
 await page.goto(url+'/teacher#create-training');await page.waitForSelector('[data-builder-ready=true]');await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'test-output/training-builder-mobile.png',fullPage:true});
 await page.setViewportSize({width:1700,height:1000});await page.getByRole('button',{name:'+ Новый план',exact:true}).click();await page.locator('#training-title').fill('Пакет сценариев');await page.locator('#training-count').fill('3');
 let generated=0;
 await page.route('**/api',async route=>{const req=route.request().postDataJSON();if(req?.action==='create'&&++generated===2)return route.fulfill({status:502,contentType:'application/json',body:JSON.stringify({error:'Проверка прерывания очереди'})});return route.continue();});
 await page.locator('#training-generate').click();await page.getByText('Проверка прерывания очереди',{exact:true}).waitFor();
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('giik.training-plans.v1')).at(-1).task_ids.length),1);
 await page.unroute('**/api');await page.locator('#training-generate').click();await page.getByText('Сценарии и эталоны созданы. Проверьте и утвердите каждый.',{exact:true}).waitFor();
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('giik.training-plans.v1')).at(-1).task_ids.length),3);
 assert.equal(await page.locator('#training-launch').isDisabled(),true);
 assert.deepEqual(errors,[]);console.log('PASS: plan persistence, scenario/reference approval, launch, assigned student testing mode, monitor/comments, AI review/teacher finalization, results/report/export, forced submission, desktop/mobile, interrupted generation/resume.');
}finally{server.kill();await browser.close();}
