"""Regenerate the OpenAPI document and route bindings after api_contract.py edits."""
import json
from pathlib import Path
from api_contract import ROUTES, openapi

ROOT = Path(__file__).resolve().parent


def client_routes():
    return {r.operation_id: {'method':r.method, 'path':r.path, 'parameters':r.parameters} for r in ROUTES}


def build():
    (ROOT / 'openapi.json').write_text(json.dumps(openapi(), ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
    data = json.dumps(client_routes(), ensure_ascii=False, separators=(',',':'))
    (ROOT / 'ui' / 'api-routes.js').write_text('// Generated by build_api_contract.py; do not edit manually.\n'
        + 'globalThis.TrainingAPIRoutes = Object.freeze('+data+');\n', encoding='utf-8')


if __name__ == '__main__':
    build()
