import {useState} from 'react';
import {createAdmin,readAdminAccount,signInAdmin} from './admin-auth.js';

export default function AdminLogin(){
 const existing=readAdminAccount();
 const [setup,setSetup]=useState(!existing),[name,setName]=useState(existing?.name||''),[login,setLogin]=useState(existing?.login||''),[password,setPassword]=useState(''),[repeat,setRepeat]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const submit=async e=>{e.preventDefault();setError('');if(setup){if(name.trim().length<3)return setError('Укажите ФИО или имя администратора.');if(login.trim().length<3)return setError('Логин должен содержать не менее 3 символов.');if(password.length<6)return setError('Пароль должен содержать не менее 6 символов.');if(password!==repeat)return setError('Пароли не совпадают.');}
  setBusy(true);try{if(setup)await createAdmin({name,login,password});else if(!await signInAdmin(login,password))return setError('Неверный логин или пароль.');location.assign('/admin');}finally{setBusy(false);}};
 return <main className="admin-login-page"><section className="admin-login-card"><a className="admin-login-back" href="/">← На главную</a><div className="admin-login-mark">112</div><p className="admin-login-eyebrow">Административный контур</p><h1>{setup?'Первичная настройка администратора':'Вход администратора'}</h1><p className="admin-login-copy">{setup?'На этом компьютере ещё нет административной учётной записи. Создайте её один раз.':'Введите административные данные доступа.'}</p><form onSubmit={submit}>{setup&&<label>Имя администратора<input autoFocus value={name} onChange={e=>setName(e.target.value)} maxLength={160} placeholder="Иванов И.И."/></label>}<label>Логин<input autoFocus={!setup} value={login} onChange={e=>setLogin(e.target.value)} maxLength={80} autoComplete="username"/></label><label>Пароль<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={setup?'new-password':'current-password'}/></label>{setup&&<label>Повторите пароль<input type="password" value={repeat} onChange={e=>setRepeat(e.target.value)} autoComplete="new-password"/></label>}{error&&<p className="admin-login-error" role="alert">{error}</p>}<button className="admin-login-submit" disabled={busy}>{busy?'Подождите…':setup?'Создать администратора и войти':'Войти'}</button></form>{!setup&&<button className="admin-login-reset" onClick={()=>{if(confirm('Удалить локальную административную учётную запись и создать новую?')){localStorage.removeItem('giik.admin.account.v1');sessionStorage.removeItem('giik.admin.session.v1');setSetup(true);setName('');setLogin('');setPassword('');}}}>Создать администратора заново</button>}<small>Учётная запись хранится только в этой локальной копии программы.</small></section></main>;
}
