import {useState} from 'react';
import {api} from './api.js';
import VoiceControls from './VoiceControls.jsx';

export default function CallbackPhone({desk,card,student,busy,act}){
 const [open,setOpen]=useState(false),[number,setNumber]=useState(''),[question,setQuestion]=useState(''),[message,setMessage]=useState('');
 const expected=card.card?.phone_callback||card.card?.phone_aon||'';
 const call=card.callback_call||{},connected=call.status==='active';
 const turns=(card.callback_turns||[]).filter(turn=>turn.call_id===call.id);
 const dial=async e=>{e.preventDefault();setMessage('');if(!number.trim())return;const ok=await act(()=>api('training_dial_callback',{resource_id:desk.id,card_id:card.id,student,number}));if(ok)setMessage('Соединение установлено. Задайте вопрос заявителю.');else setMessage('Соединение не установлено. Сверьте набранный номер с карточкой.');};
 const hangup=async()=>{const ok=await act(()=>api('training_hangup_callback',{resource_id:desk.id,card_id:card.id,student,call_id:call.id}));if(ok){setQuestion('');setMessage('Разговор завершён. Для нового звонка снова наберите номер.');}};
 const ask=async e=>{e.preventDefault();if(!question.trim()||busy)return;const ok=await act(()=>api('training_callback',{resource_id:desk.id,card_id:card.id,student,question,source:'text',call_id:call.id}));if(ok)setQuestion('');};
 return <div className="dispatcher-phone-anchor"><button type="button" className={'dispatcher-phone-toggle '+(connected?'connected':'')} onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Телефон обратного звонка">☎ {connected?'На линии':'Телефон'}</button>
 {open&&<aside className="dispatcher-phone" aria-label="Учебный телефон диспетчера"><header><div><small>ДИСПЕТЧЕР 112 · ОБРАТНЫЙ ЗВОНОК</small><strong>{connected?'Заявитель на линии':'Наберите номер из карточки'}</strong></div><button type="button" onClick={()=>setOpen(false)} aria-label="Свернуть телефон">×</button></header>
 <p className="dispatcher-phone-target">Номер в карточке: <b>{expected||'не указан'}</b></p>
 {!connected?<form onSubmit={dial}><label htmlFor={'callback-number-'+card.id}>Набранный номер</label><input id={'callback-number-'+card.id} type="tel" inputMode="tel" autoComplete="off" value={number} maxLength={80} placeholder="+7 (000) 000-00-00" onChange={e=>setNumber(e.target.value)} disabled={busy}/><div className="dispatcher-dial-pad">{['1','2','3','4','5','6','7','8','9','+','0','⌫'].map(key=><button type="button" key={key} disabled={busy} onClick={()=>setNumber(value=>key==='⌫'?value.slice(0,-1):value+key)}>{key}</button>)}</div><button className="dispatcher-phone-call" disabled={busy||!number.trim()||!expected}>☎ Позвонить</button></form>:<><div className="dispatcher-phone-line"><span>● Соединено</span><button type="button" onClick={hangup} disabled={busy}>Завершить звонок</button></div><div className="dispatcher-phone-log" role="log" aria-label="Разговор с заявителем">{turns.map((turn,index)=><p key={index} className={turn.role==='caller'?'caller':'dds'}><b>{turn.role==='caller'?'Заявитель':'Диспетчер'}:</b> {turn.text}</p>)}{!turns.length&&<p>Соединение установлено. Уточните сведения у заявителя.</p>}</div><VoiceControls history={turns.map((turn,index)=>({...turn,id:call.id+'-'+index}))} setQuestion={setQuestion} disabled={busy} voiceId={card.voice_id}/><form className="dispatcher-phone-question" onSubmit={ask}><label htmlFor={'callback-question-'+card.id}>Ваш вопрос заявителю</label><textarea id={'callback-question-'+card.id} rows={2} maxLength={2000} value={question} placeholder="Например: сколько людей в доме?" onChange={e=>setQuestion(e.target.value)} disabled={busy}/><button disabled={busy||!question.trim()}>{busy?'Ожидаем ответ…':'Спросить заявителя →'}</button></form></>}
 {message&&<p role="status" className="dispatcher-phone-message">{message}</p>}</aside>}</div>;
}
