import ReferenceAnswer from './ReferenceAnswer.jsx';
import {useEffect,useState,useSyncExternalStore} from 'react';
import {createWorkshopStore} from './workshop-store.js';
import ServicesDock from './ServicesDock.jsx';
import {Cascade,Flags,ClassificationEditor,Services,ServiceDialog} from './Classification.jsx';
const date=value=>value?new Date(value).toLocaleString('ru-RU'):'—';
const secondary={address:['country','region','object','district','area','block','building','intercom','latitude','longitude'],caller:['phone_aon','phone_scene'],incident:['vis_info','extra_signs']};
const multiline=['address_text','access','description','people','injured','extra_signs','vis_info','control_notes'];
function Fields({keys,labels,content,store}){return <div className="field-grid">{keys.map(key=><label key={key} className={'field '+(['address_text','access','description','control_notes','vis_info'].includes(key)?'wide':'')} htmlFor={'f-'+key}>{labels[key]}{multiline.includes(key)?<textarea id={'f-'+key} data-field={key} maxLength={3000} rows={2} value={content.fields[key]} onChange={e=>store.edit('field',key,e.target.value)}/>:<input id={'f-'+key} data-field={key} maxLength={3000} type={key==='control_at'?'datetime-local':'text'} value={content.fields[key]} onChange={e=>store.edit('field',key,e.target.value)}/>}</label>)}</div>;}
function FieldSection({group,label,labels,index,content,store}){
 const extra=secondary[group]||[];
 const body=<><Fields keys={Object.keys(labels).filter(k=>!extra.includes(k))} labels={labels} content={content} store={store}/>{extra.length>0&&<details><summary>{group==='address'?'Полный адрес и координаты':group==='caller'?'АОН и телефон на месте':'Дополнительные сведения'}</summary><div className="details-body"><Fields keys={extra} labels={labels} content={content} store={store}/></div></details>}</>;
 return <section className="card-section">{group==='registration'?<details><summary>Регистрация и контроль</summary><div className="details-body">{body}</div></details>:<><div className="section-head"><span>0{index+2}</span><h3>{label}</h3></div>{body}{group==='address'&&<p className="source-note">Проверка по Яндексу и карта пока не подключены. Координаты ИИ не придумывает.</p>}</>}</section>;
}
function Editor({card,meta,state,store,reviewing,generating,referencePending,onChooseServices}){
 if(!card)return <article id="editor" className="editor"><div className="empty"><span className="empty-icon">▤</span><h2>Здесь появится ваша карточка</h2><p>Сгенерируйте подборку или создайте карточку вручную.<br/>Каждую можно проверить и утвердить отдельно.</p></div></article>;
 const c=card.content,locked=card.status==='approved';
 const sections=Object.entries(meta.groups).map(([group,[label,labels]],index)=><FieldSection key={group} {...{group,label,labels,index,content:c,store}}/>);
 return <article id="editor" className="editor" inert={reviewing}>
  <div className="editor-head"><div className="headline"><small>{card.number} · версия {card.revision}</small><span className={'badge '+card.status}>{locked?'Утверждена преподавателем':'На проверке'}</span></div><label htmlFor="card-title" className="sr-only">Название карточки</label><input id="card-title" maxLength={160} value={c.title} readOnly={locked} onChange={e=>store.edit('content','title',e.target.value)}/><p className="source-note">Создана {date(card.created_at)} · {card.provenance.source==='gigachat'?'GigaChat · вымышленные данные':'Заполнена вручную'} · сохранена {date(card.updated_at)}</p><button type="button" id="open-reference" onClick={()=>document.getElementById('reference-answer')?.scrollIntoView({block:'start'})}>Эталонный ответ ↓</button></div>
  <div className="editor-body"><fieldset id="content-fields" disabled={locked}>
   <section className="card-section"><div className="section-head"><span>01</span><h3>Исходное сообщение заявителя</h3></div><label htmlFor="report" className="sr-only">Сообщение заявителя</label><textarea id="report" maxLength={6000} rows={4} value={c.report} onChange={e=>store.edit('content','report',e.target.value)}/><p className="source-note">Сверьте поля с этим сообщением. Неизвестные сведения не означают отсутствие людей или пострадавших.</p></section>
   {sections.slice(0,2)}
   <ClassificationEditor meta={meta} content={c} store={store}/>
   {sections.slice(2)}
   <Services meta={meta} content={c} card={card} store={store} onChoose={onChooseServices}/>
  </fieldset>
  <ReferenceAnswer {...{card,meta,store,generating,referencePending}}/>
  <section className={'review-box '+(locked?'approved':'')}><h3>{locked?'Карточка утверждена':'Проверка преподавателем'}</h3>{locked?<><p className="review-meta">{card.review.teacher} · {date(card.review.at)}</p><p>{card.review.note||'Без замечаний'}</p><div className="review-actions"><button id="reopen" onClick={store.reopen}>Вернуть на доработку</button><button id="export-one" onClick={store.exportOne}>Скачать карточку</button></div></>:<><p>Проверьте адрес, описание, признаки и состав служб. После утверждения карточка будет защищена от случайных правок.</p><div className="field-grid"><label>Преподаватель<input id="teacher" maxLength={160} placeholder="Ваше имя" value={state.teacher} onChange={e=>store.edit('teacher',null,e.target.value)}/></label><label>Комментарий<input id="review-note" maxLength={3000} value={card.review_note||''} placeholder="Необязательно" onChange={e=>store.edit('note',null,e.target.value)}/></label></div><div className="review-actions"><button id="validate" onClick={()=>store.review('validate')}>Проверить поля</button><button id="approve" className="primary" onClick={()=>store.review('approve')} disabled={generating}>Утвердить карточку и эталон</button><button id="export-one" onClick={store.exportOne}>Скачать</button></div></>}</section>
  <details><summary>История карточки · {card.history.length}</summary>{card.history.slice().reverse().map((h,i)=><div className="history-row" key={i}>{date(h.at)} · {h.text}</div>)}</details><p className="footer-note">Правки сохраняются автоматически в этом браузере. Утверждение здесь — отметка локального прототипа, без проверки учётной записи.</p></div>
 </article>;
}
function Generator({store,snapshot,onStart}){
 const {state,meta,generating,reviewing}=snapshot,b=state.batch;
 const [topic,setTopic]=useState(b?.topic||''),[category,setCategory]=useState(b?.category||'1'),[count,setCount]=useState(b?.total||1);
 const [selection,setSelection]=useState(b?.classification||{}),[flags,setFlags]=useState(b?.flags||{}),[location,setLocation]=useState(b?.location||'Учебный город');
 const changeGroup=k=>{setCategory(k);setSelection({});setFlags({});};
 const suffix=snapshot.referencePending?'Создаётся эталонный ответ':b&&(b.done>=b.total?'Подборка готова':b.status==='error'?'Ошибка — можно повторить':b.status==='paused'?'Приостановлено':snapshot.stopRequested?'Останавливаем после текущей карточки':`Создаётся карточка ${b.done+1}`);
 const entries=meta.catalog.filter(x=>(category==='mixed'||x.category===category)&&Object.entries(selection).every(([k,v])=>!v||x[k]===v));
 return <section className="generator"><form id="generate-form" onSubmit={e=>{e.preventDefault();if(store.start({topic,category,total:Number(count),classification:selection,flags,location}))onStart();}}><fieldset disabled={generating||reviewing} className="creation-grid">
  <section className="creation-panel"><h2>Основные параметры</h2><div className="creation-panel-body">
   <label className="topic">Тема и пожелания<textarea id="topic" maxLength={3000} rows={5} value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Например: пожар в жилом доме, разные адреса и сведения о людях"/></label>
   <label>Локация<input id="generation-location" maxLength={160} value={location} onChange={e=>setLocation(e.target.value)}/></label>
   <label className="count">Количество карточек<input id="count" type="number" min="1" max="100" required value={count} onChange={e=>setCount(e.target.value)}/></label>
   <p className="source-note">Создайте от 1 до 100 карточек вместе с эталонными ответами. Преподаватель проверяет и утверждает каждую пару отдельно.</p>
   <button id="generate" className="primary" disabled={generating||reviewing}>Сгенерировать</button>
  </div></section>
  <section className="creation-panel"><h2>Категории событий</h2><div className="creation-panel-body"><div className="category-tabs">{[['1','Пожар'],['2','ДТП'],['22','Медицина'],['14','ЖКХ'],['13','Газ'],['3','Взрыв'],['17','Человек в опасности'],['24','БПЛА']].map(([k,label])=><button type="button" key={k} data-category={k} className={category===k?'selected':''} onClick={()=>changeGroup(k)}>{label}</button>)}</div><label>Все группы происшествий<select id="category" value={category} onChange={e=>changeGroup(e.target.value)}>{Object.entries(meta.categories).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div>
  <h2>Параметры генерации</h2><div className="creation-panel-body"><Cascade meta={meta} category={category} selection={selection} onChange={next=>{setSelection(next);setFlags({});}}/><Flags meta={meta} value={flags} onChange={(k,v)=>setFlags({...flags,[k]:v})} allowAll={false} entries={entries}/></div></section>
 </fieldset></form>
 <div id="progress-panel" hidden={!b}>{b&&<><div className="progress-line"><span id="progress-text" role="status">Готово {b.done} из {b.total} · {suffix}</span><button id="stop" className="quiet" hidden={!generating} disabled={snapshot.stopRequested} onClick={store.stop}>Остановить после текущей</button><button id="resume" className="quiet" hidden={generating||b.done>=b.total} disabled={reviewing} onClick={store.resume}>Продолжить оставшиеся</button></div><progress id="progress" max={b.total} value={b.done}/></>}</div>
 <p className="catalog-note">Классификатор v046/24 · {Object.keys(meta.categories).length-1} группы · {meta.catalog.length} типов происшествий. Карточки сохраняются в этом браузере.</p></section>;
}
export default function Cards(){
 const [store]=useState(createWorkshopStore),snapshot=useSyncExternalStore(store.subscribe,store.getSnapshot);
 const {state,meta,ready,reviewing,generating,referencePending}=snapshot;
 const [filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[servicesOpen,setServicesOpen]=useState(false);
 useEffect(()=>{const detach=store.attach();store.init();return detach;},[store]);
 useEffect(()=>{document.body.dataset.ready=String(ready);return()=>{delete document.body.dataset.ready;};},[ready]);
 const approved=state.cards.filter(c=>c.status==='approved').length;
 const list=state.cards.filter(c=>(filter==='all'||c.status===filter)&&`${c.number} ${c.content.title} ${c.content.fields.city} ${c.content.fields.street} ${c.content.fields.house} ${c.content.fields.address_text}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()));
 const card=state.cards.find(c=>c.id===state.selected);
 return <main id="workshop" className="teacher-main"><section className="intro"><div><p className="eyebrow">ПОДГОТОВКА МАТЕРИАЛОВ</p><h1>От идеи до готовой карточки</h1><p>Задайте тему. Проверьте сведения. Утвердите результат.</p></div><div id="stats" className="stats">{[[state.cards.length,'Всего карточек'],[state.cards.length-approved,'На проверке'],[approved,'Утверждено']].map(([n,label])=><div className="stat" key={label}><strong>{n}</strong><span>{label}</span></div>)}</div></section>
 <div id="notice" role="status" hidden={!snapshot.notice} className={snapshot.error?'error':''}>{snapshot.notice}</div><div id="storage-warning" role="alert" hidden={!snapshot.warning}>{snapshot.warning}</div>
 {!ready?<p role="status">{snapshot.error?'Обновите страницу, чтобы повторить загрузку.':'Загружаю карточки…'}</p>:<><Generator store={store} snapshot={snapshot} onStart={()=>{setFilter('all');setSearch('');}}/><section className="workspace"><aside className="library"><div className="library-title"><h2>Мои карточки</h2><button id="new-card" className="quiet" disabled={reviewing} onClick={()=>{store.addManual();setFilter('all');setSearch('');}}>+ Вручную</button></div><label className="sr-only" htmlFor="search">Поиск карточек</label><input id="search" type="search" placeholder="Найти по названию или адресу" value={search} onChange={e=>setSearch(e.target.value)}/><div className="filters" role="group" aria-label="Статус карточек">{[['all','Все'],['draft','Черновики'],['approved','Утверждены']].map(([key,label])=><button key={key} data-filter={key} className={filter===key?'active':''} onClick={()=>setFilter(key)}>{label}</button>)}</div>
 <div id="card-list">{list.length?list.map(c=><button key={c.id} className={'card-item '+(c.id===state.selected?'selected':'')} data-id={c.id} aria-pressed={c.id===state.selected} onClick={()=>store.select(c.id)}><span className="card-meta"><span>{c.number}</span><span className={'badge '+c.status}>{c.status==='approved'?'Утверждена':'Черновик'}</span></span><strong>{c.content.title||'Без названия'}</strong><p>{c.content.fields.address_text||[c.content.fields.city,c.content.fields.street,c.content.fields.house].filter(Boolean).join(', ')||'Адрес не заполнен'}</p></button>):<p className="empty-list">Пока нет карточек по этому фильтру.</p>}</div><button id="export-all" className="export" disabled={!state.cards.length} onClick={store.exportAll}>↓ Скачать все карточки</button><p className="storage-note">Без базы данных. Карточки сохраняются в этом браузере. Для переноса или резервной копии скачайте JSON.</p></aside><Editor key={card?.id||'empty'} {...{card,meta,state,store,reviewing,generating,referencePending}} onChooseServices={()=>setServicesOpen(true)}/></section><ServicesDock {...{card,meta,store,reviewing}} generating={snapshot.generating} warning={snapshot.warning} onChoose={()=>setServicesOpen(true)}/><ServiceDialog {...{card,meta,store,reviewing}} open={servicesOpen} onClose={()=>setServicesOpen(false)}/></>}
 </main>;
}
