import {useEffect,useMemo,useState} from 'react';
import {api} from './api.js';
import {readProfile} from './Shell.jsx';
import {Panel} from './TrainingWorkspace.jsx';
import TeacherLobby from './TeacherLobby.jsx';

export default function ClassroomTrainingBuilder(){
 const [tasks,setTasks]=useState([]),[trainings,setTrainings]=useState([]),[categories,setCategories]=useState({}),[services,setServices]=useState({});
 const [title,setTitle]=useState(''),[group,setGroup]=useState(''),[mode,setMode]=useState('training'),[seconds,setSeconds]=useState(300),[source,setSource]=useState('cards'),[ids,setIds]=useState([]),[categoryIds,setCategoryIds]=useState([]),[query,setQuery]=useState('');
 const [roomId,setRoomId]=useState(()=>new URLSearchParams(location.search).get('room')||''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const refresh=async()=>{const [dashboard,plans,meta]=await Promise.all([api('teacher_dashboard'),api('training_list'),api('card_meta')]);setTasks(dashboard.tasks);setTrainings(plans);setCategories(meta.categories);setServices(meta.services);};
 useEffect(()=>{refresh().catch(e=>setError(e.message));},[]);
 const cards=useMemo(()=>tasks.filter(t=>t.status==='approved'&&t.format==='incident-v1'),[tasks]);
 const selected=source==='cards'?ids.map(id=>cards.find(card=>card.id===id)).filter(Boolean):cards.filter(card=>card.category_ids?.some(category=>categoryIds.includes(category)));
 const categoryOptions=Object.entries(categories).filter(([id])=>id!=='mixed');
 const toggle=(value,current,update)=>update(current.includes(value)?current.filter(x=>x!==value):[...current,value]);
 const create=async e=>{e.preventDefault();if(!title.trim()||!selected.length)return;setBusy(true);setError('');setNotice('');try{const room=await api('training_save',{title:title.trim(),teacher:readProfile(),group:group.trim(),mode,seconds:Number(seconds),...(source==='cards'?{task_ids:ids}:{categories:categoryIds})});setRoomId(room.id);setNotice('Комната готова. Добавьте участников и назначьте роли.');setTitle('');setGroup('');setIds([]);setCategoryIds([]);await refresh();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const close=()=>{setRoomId('');const url=new URL(location.href);url.searchParams.delete('room');history.replaceState(null,'',url);refresh().catch(e=>setError(e.message));};
 return <div className="classroom-builder"><div className="tw-page-heading"><div><h1>{roomId?'Комната ожидания':'Создать тренировку'}</h1><p>{roomId?'Назначьте роли участникам и запустите занятие.':'Выберите утверждённые карточки или категории. После создания откроется комната ожидания.'}</p></div>{roomId?<button className="tw-primary" onClick={close}>← К тренировкам</button>:<a className="tw-primary" href="/cards">+ Подготовить карточку</a>}</div>
 {error&&<p role="alert" className="tw-error">{error}</p>}{notice&&!roomId&&<p role="status" className="tw-note">{notice}</p>}
 {roomId?<TeacherLobby id={roomId} services={services} onClose={close} onActivated={refresh}/>:<><form className="classroom-form" onSubmit={create}><Panel title="1. Настройки тренировки"><div className="classroom-settings"><label>Название тренировки<input required maxLength={100} value={title} placeholder="Например, Вызов в жилом доме" onChange={e=>setTitle(e.target.value)}/></label><label>Группа (необязательно)<input maxLength={160} value={group} onChange={e=>setGroup(e.target.value)}/></label><label>Режим<select value={mode} onChange={e=>setMode(e.target.value)}><option value="training">Обучение с подсказками</option><option value="practice">Тренировка без подсказок</option><option value="testing">Тестирование без подсказок</option></select></label><label>Время на карточку, секунд<input type="number" min={0} max={86400} value={seconds} onChange={e=>setSeconds(e.target.value)}/></label></div></Panel>
 <Panel title="2. Карточки для занятия"><div className="classroom-source" role="group" aria-label="Способ выбора карточек"><button type="button" className={source==='cards'?'active':''} aria-pressed={source==='cards'} onClick={()=>setSource('cards')}>Конкретные карточки</button><button type="button" className={source==='categories'?'active':''} aria-pressed={source==='categories'} onClick={()=>setSource('categories')}>Категории карточек</button></div>
 {source==='cards'?<><label className="classroom-search">Поиск карточки<input value={query} placeholder="Название происшествия" onChange={e=>setQuery(e.target.value)}/></label><div className="classroom-choices" aria-label="Утверждённые карточки">{cards.filter(card=>card.title.toLocaleLowerCase().includes(query.toLocaleLowerCase())).map(card=><label key={card.id} className="classroom-choice"><input type="checkbox" checked={ids.includes(card.id)} onChange={()=>toggle(card.id,ids,setIds)}/><span><strong>{card.title}</strong><small>{card.category_ids?.map(id=>categories[id]||id).join(' · ')||'Без категории'}</small></span></label>)}{!cards.length&&<p>Утверждённых полных карточек пока нет. <a href="/cards">Создайте и утвердите карточку</a>.</p>}</div></>:<><p className="classroom-hint">В тренировку войдут все утверждённые карточки отмеченных категорий. Набор фиксируется при создании комнаты.</p><div className="classroom-categories" aria-label="Категории карточек">{categoryOptions.map(([id,label])=>{const count=cards.filter(card=>card.category_ids?.includes(id)).length;return <label key={id} className={'classroom-choice '+(!count?'empty':'')}><input type="checkbox" disabled={!count} checked={categoryIds.includes(id)} onChange={()=>toggle(id,categoryIds,setCategoryIds)}/><span><strong>{label}</strong><small>{count} карточек</small></span></label>})}</div></>}
 <div className="classroom-preview"><div><strong>Выбрано: {selected.length} {selected.length===1?'карточка':'карточек'}</strong>{selected.length>100&&<span role="alert">Максимум 100 карточек. Уменьшите число категорий.</span>}<p>{selected.length?selected.map(card=>card.title).join(' · '):'Отметьте карточки или категории, чтобы увидеть состав тренировки.'}</p></div><button type="submit" className="tw-primary" disabled={busy||!title.trim()||!selected.length||selected.length>100}>{busy?'Создаём…':'Создать тренировку и открыть комнату →'}</button></div></Panel></form>
 <Panel title="Созданные тренировки"><div className="classroom-existing">{trainings.length?trainings.map(plan=><article key={plan.id}><div><strong>{plan.title}</strong><small>{plan.status==='prepared'?'Комната ожидания':plan.status==='active'?'Тренировка идёт':'Завершена'} · {plan.task_ids?.length||plan.cards?.length||'—'} карточек · {plan.participants.length} участников</small></div>{plan.status!=='completed'&&<button onClick={()=>setRoomId(plan.id)}>Открыть комнату →</button>}</article>):<p>Пока нет тренировок. Выберите карточки выше и создайте первую комнату.</p>}</div></Panel></>}
 </div>;
}
