import {useEffect,useState} from 'react';
import {api} from './api.js';
import {readProfile} from './Shell.jsx';
import {Panel} from './TrainingWorkspace.jsx';
<<<<<<< HEAD
import TeacherLobby from './TeacherLobby.jsx';

const people=text=>text.split('\n').map(x=>x.trim()).filter(Boolean).map(line=>{const [student,r,service='']=line.split(';').map(x=>x.trim());return {student,role:({оператор:'operator',ддс:'dds',служба:'service'})[(r||'').toLowerCase()]||r||'waiting',service};});
=======

const people=text=>text.split('\n').map(x=>x.trim()).filter(Boolean).map(line=>{const [student,r,service='']=line.split(';').map(x=>x.trim());return {student,role:({оператор:'operator',ддс:'dds',служба:'service'})[(r||'').toLowerCase()]||r||'operator',service};});
>>>>>>> ec5491b6745f1dd11607901b6ecc81befa475fae
export default function CurriculumBuilder(){
 const [tasks,setTasks]=useState([]),[scenarios,setScenarios]=useState([]),[trainings,setTrainings]=useState([]),[services,setServices]=useState({});
 const [title,setTitle]=useState(''),[description,setDescription]=useState(''),[selected,setSelected]=useState([]),[levels,setLevels]=useState({}),[editingScenario,setEditingScenario]=useState('');
 const [trainingTitle,setTrainingTitle]=useState(''),[chosen,setChosen]=useState([]),[participants,setParticipants]=useState(''),[mode,setMode]=useState('training'),[seconds,setSeconds]=useState(30),[difficulty,setDifficulty]=useState('medium'),[group,setGroup]=useState(''),[editingTraining,setEditingTraining]=useState('');
 const [notice,setNotice]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
<<<<<<< HEAD
 const [lobbyId,setLobbyId]=useState('');
=======
>>>>>>> ec5491b6745f1dd11607901b6ecc81befa475fae
 const refresh=async()=>{const [o,s,t,services]=await Promise.all([api('teacher_dashboard'),api('scenario_list'),api('training_list'),api('services_list')]);setTasks(o.tasks);setScenarios(s);setTrainings(t);setServices(services);};
 useEffect(()=>{refresh().catch(e=>setError(e.message));},[]);
 const run=async fn=>{setBusy(true);setError('');setNotice('');try{await fn();await refresh();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const toggle=(list,update,id)=>update(list.includes(id)?list.filter(x=>x!==id):[...list,id]);
 const scenarioPayload=()=>({title,description,teacher:readProfile(),task_ids:selected,task_difficulties:Object.fromEntries(selected.map(id=>[id,Number(levels[id]||3)]))});
 const clearScenario=()=>{setTitle('');setDescription('');setSelected([]);setLevels({});setEditingScenario('');};
 const createScenario=approve=>run(async()=>{const s=await api(editingScenario?'scenario_save_update':'scenario_save',{...scenarioPayload(),...(editingScenario?{resource_id:editingScenario}:{})});if(approve)await api('scenario_approve',{resource_id:s.id,teacher:readProfile()});setNotice(approve?'Сценарий утверждён.':'Черновик сохранён.');clearScenario();});
 const editScenario=s=>{setEditingScenario(s.id);setTitle(s.title);setDescription(s.description||'');setSelected(s.task_ids);setLevels(s.task_difficulties||{});window.scrollTo(0,0);};
 const clearTraining=()=>{setTrainingTitle('');setChosen([]);setParticipants('');setEditingTraining('');};
<<<<<<< HEAD
 const createTraining=()=>run(async()=>{const room=await api(editingTraining?'training_save_update':'training_save',{title:trainingTitle,teacher:readProfile(),scenario_ids:chosen,participants:people(participants),mode,seconds:Number(seconds),difficulty,group,...(editingTraining?{resource_id:editingTraining}:{})});setNotice('Комната открыта. Пригласите обучающихся и назначьте роли.');setLobbyId(room.id);clearTraining();});
 const editTraining=t=>{setEditingTraining(t.id);setTrainingTitle(t.title);setChosen(t.scenario_ids);setParticipants(t.participants.map(p=>[p.student,p.role,p.service].filter(Boolean).join('; ')).join('\n'));setMode(t.mode);setSeconds(t.seconds);setDifficulty(t.difficulty);setGroup(t.group);window.scrollTo(0,0);};
 return <div className="curriculum"><div className="tw-page-heading"><div><h1>Сценарии и тренировки</h1><p>Утвердите сценарии, создайте комнату и назначьте роли подключившимся обучающимся.</p></div><a className="tw-primary" href="/cards">+ Создать полную карточку</a></div>
 {error&&<p role="alert" className="tw-error">{error}</p>}{notice&&<p role="status" className="tw-note">{notice}</p>}
 <fieldset disabled={busy} className="curriculum-columns"><Panel title="1. Утвердить сценарий"><label>Тема<input value={title} maxLength={100} onChange={e=>setTitle(e.target.value)}/></label><label>Описание<textarea value={description} maxLength={2000} onChange={e=>setDescription(e.target.value)}/></label><h3>Утверждённые полные карточки</h3><div className="curriculum-scroll">{tasks.filter(t=>t.status==='approved'&&t.format==='incident-v1').map(t=><label className="tw-checkbox" key={t.id}><input type="checkbox" checked={selected.includes(t.id)} onChange={()=>toggle(selected,setSelected,t.id)}/>{t.title}<select aria-label={'Сложность: '+t.title} value={levels[t.id]||3} onChange={e=>setLevels({...levels,[t.id]:Number(e.target.value)})}>{[1,2,3,4,5].map(n=><option key={n} value={n}>Уровень {n}</option>)}</select></label>)}</div><button disabled={!title.trim()||!selected.length} onClick={()=>createScenario(false)}>Сохранить черновик</button><button className="tw-primary" disabled={!title.trim()||!selected.length} onClick={()=>createScenario(true)}>Сохранить и утвердить</button>{editingScenario&&<button onClick={clearScenario}>Отмена редактирования</button>}</Panel>
 <Panel title="2. Подготовить тренировку"><label>Название<input value={trainingTitle} maxLength={100} onChange={e=>setTrainingTitle(e.target.value)}/></label><h3>Сценарии</h3><div className="curriculum-scroll">{scenarios.filter(s=>s.status==='approved').map(s=><label className="tw-checkbox" key={s.id}><input type="checkbox" checked={chosen.includes(s.id)} onChange={()=>toggle(chosen,setChosen,s.id)}/>{s.title} · {s.task_ids.length} задач</label>)}</div><label>Группа<input value={group} onChange={e=>setGroup(e.target.value)}/></label><label>Режим<select value={mode} onChange={e=>setMode(e.target.value)}><option value="training">Обучение, подсказка после 10 секунд</option><option value="testing">Тестирование, без подсказок</option></select></label><label>Время на карточку, секунд<input type="number" min="0" max="86400" value={seconds} onChange={e=>setSeconds(e.target.value)}/></label><label>Сложность<select value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="easy">Низкая</option><option value="medium">Средняя</option><option value="hard">Высокая</option><option value="adaptive">Адаптивная</option></select></label><label>Участники заранее (необязательно): имя; роль; код службы<textarea rows={5} value={participants} onChange={e=>setParticipants(e.target.value)} placeholder={'Иванов; оператор\nПетров; ДДС\nСидоров; служба; 101'}/></label><small>Можно оставить пустым: обучающиеся войдут по коду комнаты, а роли назначаются после входа.</small><details><summary>Посмотреть службы и коды</summary><ul>{Object.entries(services).map(([code,label])=><li key={code}>{code} — {label}</li>)}</ul></details><button className="tw-primary" disabled={!trainingTitle.trim()||!chosen.length} onClick={createTraining}>{editingTraining?'Сохранить изменения':'Подготовить тренировку'}</button>{editingTraining&&<button onClick={clearTraining}>Отмена редактирования</button>}</Panel></fieldset>
 <Panel title="Сценарии">{scenarios.length?<ul>{scenarios.map(s=><li key={s.id}>{s.title} · {s.task_ids.length} задач · {s.status==='approved'?'утверждён':'черновик'} {s.status==='draft'&&<><button onClick={()=>editScenario(s)}>Изменить</button><button onClick={()=>run(async()=>{await api('scenario_approve',{resource_id:s.id,teacher:readProfile()});setNotice('Сценарий утверждён.');})}>Утвердить</button><button onClick={()=>{if(confirm('Удалить черновик сценария?'))run(async()=>{await api('scenario_delete',{resource_id:s.id});setNotice('Черновик удалён.');});}}>Удалить</button></>}</li>)}</ul>:<p>Пока нет сценариев.</p>}</Panel>
 <Panel title="Тренировки">{trainings.length?<div className="tw-table-scroll"><table className="tw-table"><thead><tr><th>Название</th><th>Сценарии</th><th>Участники</th><th>Обработано карточек</th><th>Статус</th><th>Действие</th></tr></thead><tbody>{trainings.map(t=><tr key={t.id}><td>{t.title}</td><td>{t.scenario_ids.length}</td><td>{t.participants.map(p=>p.student+' ('+p.role+(p.service?' '+p.service:'')+')').join(', ')}</td><td>{t.cards.filter(c=>c.status==='done').length} / {t.cards.length}</td><td>{({prepared:'Подготовлена',active:'Активна',completed:'Завершена'})[t.status]}</td><td>{t.status==='prepared'?<><button onClick={()=>editTraining(t)}>Изменить</button><button className="tw-primary" onClick={()=>setLobbyId(t.id)}>Открыть комнату</button><button onClick={()=>{if(confirm('Удалить подготовленную тренировку?'))run(async()=>{await api('training_delete',{resource_id:t.id});setNotice('Тренировка удалена.');});}}>Удалить</button></>:t.status==='active'?<button onClick={()=>run(async()=>{await api('training_complete',{resource_id:t.id,teacher:readProfile()});setNotice('Тренировка завершена.');})}>Завершить</button>:'—'}</td></tr>)}</tbody></table></div>:<p>Подготовьте тренировку.</p>}</Panel>
 {lobbyId&&<TeacherLobby id={lobbyId} services={services} onClose={()=>setLobbyId('')} onActivated={refresh}/>}
=======
 const createTraining=()=>run(async()=>{await api(editingTraining?'training_save_update':'training_save',{title:trainingTitle,teacher:readProfile(),scenario_ids:chosen,participants:people(participants),mode,seconds:Number(seconds),difficulty,group,...(editingTraining?{resource_id:editingTraining}:{})});setNotice('Тренировка подготовлена. Активируйте её, когда участники готовы.');clearTraining();});
 const editTraining=t=>{setEditingTraining(t.id);setTrainingTitle(t.title);setChosen(t.scenario_ids);setParticipants(t.participants.map(p=>[p.student,p.role,p.service].filter(Boolean).join('; ')).join('\n'));setMode(t.mode);setSeconds(t.seconds);setDifficulty(t.difficulty);setGroup(t.group);window.scrollTo(0,0);};
 return <div className="curriculum"><div className="tw-page-heading"><div><h1>Сценарии и тренировки</h1><p>Утвердите сценарии из готовых карточек, затем назначьте участников и их учебные роли.</p></div><a className="tw-primary" href="/cards">+ Создать полную карточку</a></div>
 {error&&<p role="alert" className="tw-error">{error}</p>}{notice&&<p role="status" className="tw-note">{notice}</p>}
 <fieldset disabled={busy} className="curriculum-columns"><Panel title="1. Утвердить сценарий"><label>Тема<input value={title} maxLength={100} onChange={e=>setTitle(e.target.value)}/></label><label>Описание<textarea value={description} maxLength={2000} onChange={e=>setDescription(e.target.value)}/></label><h3>Утверждённые полные карточки</h3><div className="curriculum-scroll">{tasks.filter(t=>t.status==='approved'&&t.format==='incident-v1').map(t=><label className="tw-checkbox" key={t.id}><input type="checkbox" checked={selected.includes(t.id)} onChange={()=>toggle(selected,setSelected,t.id)}/>{t.title}<select aria-label={'Сложность: '+t.title} value={levels[t.id]||3} onChange={e=>setLevels({...levels,[t.id]:Number(e.target.value)})}>{[1,2,3,4,5].map(n=><option key={n} value={n}>Уровень {n}</option>)}</select></label>)}</div><button disabled={!title.trim()||!selected.length} onClick={()=>createScenario(false)}>Сохранить черновик</button><button className="tw-primary" disabled={!title.trim()||!selected.length} onClick={()=>createScenario(true)}>Сохранить и утвердить</button>{editingScenario&&<button onClick={clearScenario}>Отмена редактирования</button>}</Panel>
 <Panel title="2. Подготовить тренировку"><label>Название<input value={trainingTitle} maxLength={100} onChange={e=>setTrainingTitle(e.target.value)}/></label><h3>Сценарии</h3><div className="curriculum-scroll">{scenarios.filter(s=>s.status==='approved').map(s=><label className="tw-checkbox" key={s.id}><input type="checkbox" checked={chosen.includes(s.id)} onChange={()=>toggle(chosen,setChosen,s.id)}/>{s.title} · {s.task_ids.length} задач</label>)}</div><label>Группа<input value={group} onChange={e=>setGroup(e.target.value)}/></label><label>Режим<select value={mode} onChange={e=>setMode(e.target.value)}><option value="training">Обучение, подсказка после 10 секунд</option><option value="testing">Тестирование, без подсказок</option></select></label><label>Время на карточку, секунд<input type="number" min="0" max="86400" value={seconds} onChange={e=>setSeconds(e.target.value)}/></label><label>Сложность<select value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="easy">Низкая</option><option value="medium">Средняя</option><option value="hard">Высокая</option><option value="adaptive">Адаптивная</option></select></label><label>Участники, один на строку: имя; роль; код службы<textarea rows={5} value={participants} onChange={e=>setParticipants(e.target.value)} placeholder={'Иванов; оператор\nПетров; ДДС\nСидоров; служба; 101'}/></label><small>Роль «служба» требует код из классификатора.</small><details><summary>Посмотреть службы и коды</summary><ul>{Object.entries(services).map(([code,label])=><li key={code}>{code} — {label}</li>)}</ul></details><button className="tw-primary" disabled={!trainingTitle.trim()||!chosen.length||!participants.trim()} onClick={createTraining}>{editingTraining?'Сохранить изменения':'Подготовить тренировку'}</button>{editingTraining&&<button onClick={clearTraining}>Отмена редактирования</button>}</Panel></fieldset>
 <Panel title="Сценарии">{scenarios.length?<ul>{scenarios.map(s=><li key={s.id}>{s.title} · {s.task_ids.length} задач · {s.status==='approved'?'утверждён':'черновик'} {s.status==='draft'&&<><button onClick={()=>editScenario(s)}>Изменить</button><button onClick={()=>run(async()=>{await api('scenario_approve',{resource_id:s.id,teacher:readProfile()});setNotice('Сценарий утверждён.');})}>Утвердить</button><button onClick={()=>{if(confirm('Удалить черновик сценария?'))run(async()=>{await api('scenario_delete',{resource_id:s.id});setNotice('Черновик удалён.');});}}>Удалить</button></>}</li>)}</ul>:<p>Пока нет сценариев.</p>}</Panel>
 <Panel title="Тренировки">{trainings.length?<div className="tw-table-scroll"><table className="tw-table"><thead><tr><th>Название</th><th>Сценарии</th><th>Участники</th><th>Обработано карточек</th><th>Статус</th><th>Действие</th></tr></thead><tbody>{trainings.map(t=><tr key={t.id}><td>{t.title}</td><td>{t.scenario_ids.length}</td><td>{t.participants.map(p=>p.student+' ('+p.role+(p.service?' '+p.service:'')+')').join(', ')}</td><td>{t.cards.filter(c=>c.status==='done').length} / {t.cards.length}</td><td>{({prepared:'Подготовлена',active:'Активна',completed:'Завершена'})[t.status]}</td><td>{t.status==='prepared'?<><button onClick={()=>editTraining(t)}>Изменить</button><button onClick={()=>run(async()=>{await api('training_activate',{resource_id:t.id});setNotice('Тренировка запущена.');})}>Активировать</button><button onClick={()=>{if(confirm('Удалить подготовленную тренировку?'))run(async()=>{await api('training_delete',{resource_id:t.id});setNotice('Тренировка удалена.');});}}>Удалить</button></>:t.status==='active'?<button onClick={()=>run(async()=>{await api('training_complete',{resource_id:t.id,teacher:readProfile()});setNotice('Тренировка завершена.');})}>Завершить</button>:'—'}</td></tr>)}</tbody></table></div>:<p>Подготовьте тренировку.</p>}</Panel>
>>>>>>> ec5491b6745f1dd11607901b6ecc81befa475fae
 </div>;
}
