import {useEffect,useState} from 'react';
import {api} from './api.js';
import VoiceControls from './VoiceControls.jsx';
import AddressMap from './AddressMap.jsx';
import DispatcherIncidentCard from './DispatcherIncidentCard.jsx';
function DemoGenerator({desk,student,busy,act}){
 const [count,setCount]=useState(4),[topic,setTopic]=useState(''),[location,setLocation]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{let active=true;api('geo_addresses').then(data=>{if(active)setLocation(`${data.city}, ${data.region}`);}).catch(e=>{if(active)setNotice('Адреса OSM недоступны: '+e.message);});return()=>{active=false;};},[]);
 const create=async()=>{setNotice('');const value=Number(count);const ok=await act(()=>api('training_dispatcher_examples',{resource_id:desk.id,student,count:value,topic:topic.trim(),location:location.trim()}));if(ok)setNotice(`Готово: ${value} ИИ-карточки добавлены прямо в вашу очередь.`);};
 return <section className="dispatcher-ai-generator"><div className="dispatcher-section-head"><div><small>САМОСТОЯТЕЛЬНАЯ ПРАКТИКА</small><h5>Создать эталонные карточки через ИИ</h5></div><span>Без оператора</span></div><p>ИИ сформирует вымышленные карточки и сразу отправит их вам как Диспетчеру 112. Можно перезванивать заявителю, уточнять сведения и направлять службы.</p><div className="dispatcher-ai-generator-grid"><label>Количество<select value={count} disabled={busy} onChange={e=>setCount(Number(e.target.value))}>{[1,2,3,4].map(v=><option key={v} value={v}>{v}</option>)}</select></label><label>Город OSM<select value={location} disabled={busy||!location} onChange={e=>setLocation(e.target.value)}><option value={location}>{location||"Загружаем адреса…"}</option></select></label><label className="wide">Пожелание к примерам<input value={topic} maxLength={1000} disabled={busy} placeholder="Необязательно: например, вечер, сложные адреса, разные службы" onChange={e=>setTopic(e.target.value)}/></label><button className="dispatcher-primary" disabled={busy||!location.trim()} onClick={create}>{busy?'ИИ создаёт карточки…':`Создать ${count} ИИ-карточки`}</button></div>{notice&&<p className="dispatcher-ai-generator-ok" role="status">{notice}</p>}</section>;
}
const remaining=(timestamp,seconds,clock)=>{if(!timestamp)return seconds;return Math.ceil(seconds-(clock-new Date(timestamp).getTime())/1000);};
const timerLabel=seconds=>String(Math.floor(Math.max(0,seconds)/60)).padStart(2,'0')+':'+String(Math.max(0,seconds)%60).padStart(2,'0');
const seniorNames={'101':'Старший пожарной охраны','102':'Старший полиции','103':'Старший бригады скорой помощи','104':'Старший аварийной газовой службы'};
function RoutedCard({desk,card,student,services,busy,act}){
 const [service,setService]=useState(card.services[0]||''),[route,setRoute]=useState(null),[map,setMap]=useState(null);
 const call=card.dds_senior_calls?.[service],answered=call?.status==='answered';
 const address=[card.card?.city,card.card?.street,card.card?.house].filter(Boolean).join(', ')||card.card?.address_text||'адрес не указан';
 const report=card.card?._report||card.card?.description||'происшествие';
 const speaker=seniorNames[service]||'Старший службы '+(services[service]||service);
 const words=`${speaker}. Выехали по адресу: ${address}. Причина вызова: ${report}`;
 useEffect(()=>{setRoute(null);setMap(null);if(!answered)return;let live=true;Promise.all([api('training_dds_service_route',{resource_id:desk.id,card_id:card.id,student,service}),api('geo_map')]).then(([r,m])=>{if(live){setRoute(r);setMap(m);}}).catch(e=>{if(live)setRoute({found:false,message:e.message});});return()=>{live=false;};},[desk.id,card.id,student,service,answered]);
 return <article className="dispatcher-routed-card"><div className="dispatcher-section-head"><div><small>НАПРАВЛЕННАЯ КАРТОЧКА · {card.id.slice(-6)}</small><h4>{card.ai_title||card.card?.description||'Сообщение о происшествии'}</h4></div><span>{new Date(card.routed_at).toLocaleTimeString('ru-RU')}</span></div><p><b>Адрес:</b> {address}</p><p><b>Причина:</b> {report}</p><div className="dds-routed-services" role="group" aria-label="Направленные службы">{card.services.map(code=><button key={code} type="button" className={service===code?'selected':''} onClick={()=>setService(code)}>{code} · {services[code]||'Служба'}</button>)}</div>
 {!answered?<div className="dispatcher-senior-call dds-senior-call" role="alertdialog" aria-label={'Входящий вызов: '+speaker}><span className="dispatcher-ring">☎</span><div><strong>Входящий вызов · {speaker}</strong><small>Подтверждение выезда по адресу {address}</small></div><button className="dispatcher-primary" disabled={busy} onClick={()=>act(()=>api('training_dds_senior_answer',{resource_id:desk.id,card_id:card.id,student,service}))}>Ответить на вызов</button></div>:<div className="dds-response-layout"><section className="dispatcher-senior-conversation"><h5>Разговор со старшим службы</h5><p>{words}</p><VoiceControls history={[{id:card.id+'-'+service+'-dds-senior',role:'service',text:words}]} setQuestion={()=>{}} disabled voiceId={card.voice_id}/></section><section className="dispatcher-route"><h5>Маршрут подразделения к дому вызова</h5>{route?.found?<><p><b>{route.origin.label}</b> → <b>{route.destination.label}</b> · {route.distance_m} м</p>{map&&<AddressMap data={map} route={route} point={route.destination.point} kind="building" label={route.destination.label}/>}</>:<p role="status">{route?.message||'Строим маршрут…'}</p>}</section></div>}</article>;
}
function ServiceReview({desk,card,student,busy,act,clock,services}){
 const progress=card.service_progress?.[desk.service]||{},[status,setStatus]=useState('accepted'),[text,setText]=useState(''),[route,setRoute]=useState(null),[map,setMap]=useState(null);
 const address=[card.card?.city,card.card?.street,card.card?.house].filter(Boolean).join(', ')||card.card?.address_text||'адрес не указан';
 const report=card.card?._report||card.card?.description||'происшествие';
 const speaker=seniorNames[desk.service]||'Старший службы '+(services[desk.service]||desk.service);
 const words=`${speaker}. Выехали по адресу: ${address}. Причина вызова: ${report}`;
 const opened=!!progress.opened_at,first=!!progress.first_entry_at,answered=!!progress.call_answered_at;
 useEffect(()=>{if(!first)return;let live=true;Promise.all([api('training_service_route',{resource_id:desk.id,card_id:card.id,student}),api('geo_map')]).then(([r,m])=>{if(live){setRoute(r);setMap(m);}}).catch(e=>{if(live)setRoute({found:false,message:e.message});});return()=>{live=false;};},[first,desk.id,card.id,student]);
 const firstEntry=async()=>{if(await act(()=>api('training_service_action',{resource_id:desk.id,card_id:card.id,student,status,text})))setText('');};
 return <article className="dispatcher-card dispatcher-service-detail"><div className="dispatcher-card-title"><div><small>СЛУЖБА {desk.service} · {services[desk.service]}</small><h4>Карточка {card.id.slice(-6)}</h4></div><span>{first?'Первая запись внесена':opened?'В работе':'Ожидает открытия'}</span></div>
 <div className="dispatcher-deadline"><div><small>ОТКРЫТЬ КАРТОЧКУ ЗА 30 СЕКУНД</small><strong className={!opened&&remaining(card.routed_at,30,clock)<0?'late':''}>{opened?progress.open_late?'Открыто позже срока':'Открыто вовремя':timerLabel(remaining(card.routed_at,30,clock))}</strong></div><div><small>ПЕРВАЯ ЗАПИСЬ ЗА 3 МИНУТЫ ПОСЛЕ ОТКРЫТИЯ</small><strong className={opened&&!first&&remaining(progress.opened_at,180,clock)<0?'late':''}>{first?progress.first_entry_late?'Запись позже срока':'Запись вовремя':opened?timerLabel(remaining(progress.opened_at,180,clock)):'После открытия'}</strong></div></div>
 {!opened?<div className="dispatcher-inbox-summary"><p><b>Тип:</b> {card.card?.description||report}</p><p><b>Адрес:</b> {address}</p><p><b>Поступила:</b> {new Date(card.routed_at).toLocaleTimeString('ru-RU')}</p><button className="dispatcher-primary" disabled={busy} onClick={()=>act(()=>api('training_service_open',{resource_id:desk.id,card_id:card.id,student}))}>Открыть карточку →</button></div>:<><div className="dispatcher-info"><div><small>АДРЕС ВЫЗОВА</small><strong>{address}</strong></div><div><small>ОБСТОЯТЕЛЬСТВА</small><strong>{report}</strong></div></div><details className="dispatcher-details"><summary>Все поля карточки</summary><dl>{Object.entries(card.card||{}).filter(([key])=>!key.startsWith('_')).map(([key,value])=><div key={key}><dt>{card.field_labels?.[key]||key}</dt><dd>{value||'—'}</dd></div>)}</dl></details>
 <section className="dispatcher-entry"><h5>{first?'Журнал действий':'Первая запись'}</h5>{progress.entries?.map((entry,i)=><p key={i}><b>{entry.status==='accepted'?'Принято':entry.status==='dispatched'?'Выезд':'На месте'} · {new Date(entry.at).toLocaleTimeString('ru-RU')}</b> — {entry.text}</p>)}<div className="dispatcher-entry-form"><label>Статус<select value={status} onChange={e=>setStatus(e.target.value)}><option value="accepted">Принято</option><option value="dispatched">Выезд</option><option value="on_scene">На месте</option></select></label><label>Текст записи<textarea rows={2} value={text} onChange={e=>setText(e.target.value)} placeholder="Укажите состав наряда и принятые меры"/></label><button className="dispatcher-primary" disabled={busy||!text.trim()} onClick={firstEntry}>Сохранить запись</button></div></section>
 {first&&!answered&&<div className="dispatcher-senior-call" role="alert"><span className="dispatcher-ring">☎</span><div><strong>Входящий вызов · {speaker}</strong><small>Подтверждение выезда по карточке {card.id.slice(-6)}</small></div><button className="dispatcher-primary" disabled={busy} onClick={()=>act(()=>api('training_senior_answer',{resource_id:desk.id,card_id:card.id,student}))}>Ответить на вызов</button></div>}
 {answered&&<section className="dispatcher-senior-conversation"><h5>Разговор со старшим службы</h5><p>{words}</p><VoiceControls history={[{id:card.id+'-senior',role:'service',text:words}]} setQuestion={()=>{}} disabled voiceId={card.voice_id}/></section>}
 {first&&<section className="dispatcher-route"><h5>Маршрут к дому вызова</h5>{route?.found?<><p><b>{route.origin.label}</b> → <b>{route.destination.label}</b> · {route.distance_m} м</p>{map&&<AddressMap data={map} route={route} point={route.destination.point} kind="building" label={route.destination.label}/>}</>:<p role="status">{route?.message||'Строим маршрут…'}</p>}</section>}
 {answered&&<button className="dispatcher-primary" disabled={busy} onClick={()=>act(()=>api('training_service_action',{resource_id:desk.id,card_id:card.id,student,text:progress.entries?.at(-1)?.text||'Выезд подтверждён'}))}>Завершить работу по карточке</button>}
 </>}</article>;
}
export default function DispatcherDesk({student}){
 const [desks,setDesks]=useState([]),[services,setServices]=useState({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[clock,setClock]=useState(Date.now()),[query,setQuery]=useState(''),[selected,setSelected]=useState('');
 const refresh=()=>api('training_desk',{student}).then(setDesks).catch(e=>setError(e.message));
 useEffect(()=>{refresh();api('services_list').then(setServices).catch(e=>setError(e.message));const timer=setInterval(refresh,5000),seconds=setInterval(()=>setClock(Date.now()),1000);return()=>{clearInterval(timer);clearInterval(seconds);};},[student]);
 const act=async fn=>{setBusy(true);setError('');try{await fn();await refresh();return true;}catch(e){setError(e.message);return false;}finally{setBusy(false);}};
 const handoff=desks.filter(d=>d.role!=='operator'&&d.status==='active');if(!handoff.length)return null;
 return <section className="student-panel dispatcher-desk"><div className="dispatcher-heading"><div><small>РАБОЧЕЕ МЕСТО · 112</small><h2>Поиск происшествий</h2><p>Карточки от оператора поступают на проверку. Решение о службах принимает диспетчер 112.</p></div><span>{new Date(clock).toLocaleTimeString('ru-RU')}</span></div><label className="dispatcher-search">Поиск по номеру, типу и адресу<input value={query} placeholder="Найти происшествие…" onChange={e=>setQuery(e.target.value)}/></label>{error&&<p role="alert" className="lobby-error">{error}</p>}
 {handoff.map(d=>{const visible=d.cards.filter(c=>!query.trim()||[c.id,c.ai_title,c.student,c.card?._report,c.card?.description,c.card?.address_text,c.card?.city,c.card?.street,c.card?.house].some(v=>String(v||'').toLocaleLowerCase('ru').includes(query.trim().toLocaleLowerCase('ru'))));const active=visible.find(c=>c.id===selected);
 return <section key={d.id}><div className="dispatcher-queue"><h3>Список происшествий</h3><span>{d.role==='dds'?'Диспетчер 112':'Диспетчер '+(services[d.service]||d.service)} · {visible.length} в очереди</span></div>{d.role==='dds'&&<details className="dispatcher-generator-fold"><summary>+ Создать ИИ-примеры для самостоятельной практики</summary><DemoGenerator desk={d} student={student} busy={busy} act={act}/></details>}
 {d.role==='dds'?<><div className="dispatcher-queue-head"><span>№</span><span>Время</span><span>Тип происшествия</span><span>Адрес</span><span>Статус</span></div>{visible.map(c=><button type="button" key={c.id} className={'dispatcher-queue-item '+(selected===c.id?'selected':'')} onClick={()=>setSelected(selected===c.id?'':c.id)} aria-expanded={selected===c.id}><strong>{c.id.slice(-6)}</strong><span>{new Date(c.submitted_at).toLocaleTimeString('ru-RU')}</span><span>{c.ai_title||c.card?.description||'Сообщение от оператора'}</span><span>{[c.card?.city,c.card?.street,c.card?.house].filter(Boolean).join(', ')||c.card?.address_text||'Адрес уточняется'}</span><em>На проверке</em><small>Описание: {c.card?._report||'—'}</small></button>)}{!visible.length&&<p className="dispatcher-empty">Карточек на проверке пока нет.</p>}{active&&<DispatcherIncidentCard key={active.id} desk={d} card={active} services={services} student={student} busy={busy} act={act}/>}<section className="dds-routed-list"><h3>Направленные карточки</h3>{d.routed_cards?.length?d.routed_cards.map(c=><RoutedCard key={c.id} desk={d} card={c} student={student} services={services} busy={busy} act={act}/>):<p>После выбора служб здесь появятся вызовы старших и маршруты подразделений.</p>}</section></>:visible.length?visible.map(c=><div key={c.id}><div className="dispatcher-inbox-row"><strong>№ {c.id.slice(-6)}</strong><span>{new Date(c.routed_at||c.submitted_at).toLocaleTimeString('ru-RU')}</span><span>{c.card?.description||c.card?._report||'Происшествие'}<small>{[c.card?.city,c.card?.street,c.card?.house].filter(Boolean).join(', ')||c.card?.address_text}</small></span><span>{c.service_progress?.[d.service]?.opened_at?'Открыта':'Ожидает открытия'}</span></div><ServiceReview desk={d} card={c} student={student} busy={busy} act={act} clock={clock} services={services}/></div>):<p className="dispatcher-empty">Новых карточек пока нет.</p>}</section>;})}</section>;
}
