import {referenceCurrent} from './reference-state.js';
export default function ReferenceAnswer({card,meta,store,generating,referencePending}){
 const reference=card.reference,answer=reference?.answer,current=referenceCurrent(card),approved=card.status==='approved';
 const busy=referencePending===card.id,locked=approved||generating||!!referencePending;
 const edit=(section,value)=>store.editReference(section,null,value);
 return <section id="reference-answer" className="reference-answer">
  <div className="reference-heading"><div><span className="eyebrow">ДЛЯ ПРЕПОДАВАТЕЛЯ</span><h3>Эталонный ответ</h3></div><span className={'badge '+(approved&&reference?'approved':'draft')}>{busy?'Создаётся…':!reference?'Не создан':approved?'Утверждён':current?'На проверке':'Требует обновления'}</span></div>
  <p>Правильное заполнение по сообщению заявителя, вопросы для уточнения и критичные ошибки. Окончательный ответ утверждает преподаватель.</p>
  {card.reference_error&&<p role="alert" className="reference-warning">Не удалось создать эталон: {card.reference_error} Карточка и предыдущий ответ сохранены.</p>}
  {reference&&!current&&!approved&&<p role="alert" className="reference-warning">Карточка изменилась после создания эталона. Обновите его и проверьте снова перед утверждением.</p>}
  {!approved&&<button type="button" id="generate-reference" disabled={locked} onClick={store.generateReference}>{busy?'GigaChat готовит эталон…':reference?'Обновить эталон через GigaChat':'Создать эталон через GigaChat'}</button>}
  {answer&&<fieldset disabled={locked} className="reference-fields"><label>Правильный ответ — кратко<textarea data-reference="summary" rows={3} maxLength={2000} value={answer.summary} onChange={e=>edit('summary',e.target.value)}/></label>
   <details><summary>Эталонное заполнение полей · {Object.keys(answer.expected_fields).length}</summary><div className="reference-values">{Object.entries(meta.reference_fields).map(([key,label])=><div className="reference-value" key={key}><label>{label}<textarea data-reference-field={key} rows={2} maxLength={3000} value={answer.expected_fields[key].value} onChange={e=>store.editReference('expected_fields',key,e.target.value)}/></label><label className="reference-evidence">Цитата из сообщения<textarea data-reference-evidence={key} rows={2} maxLength={1000} placeholder="Сведений нет — оставьте пустым" value={answer.expected_fields[key].evidence} onChange={e=>store.editReference('expected_fields',key,e.target.value,'evidence')}/></label></div>)}</div></details>
   <details><summary>Классификация и службы</summary>{[['classification_reason','Почему выбран этот тип'],['services_reason','Обоснование состава служб']].map(([key,label])=><label key={key}>{label}<textarea data-reference={key} rows={3} maxLength={2000} value={answer[key]} onChange={e=>edit(key,e.target.value)}/></label>)}</details>
   {[['questions','Что уточнить у заявителя'],['critical_errors','Критичные ошибки']].map(([section,title])=><details key={section}><summary>{title} · {answer[section].length}</summary>{answer[section].map((value,index)=><div className="reference-list-row" key={index}><textarea aria-label={`${title}: ${index+1}`} rows={2} maxLength={1000} value={value} onChange={e=>edit(section,answer[section].map((x,i)=>i===index?e.target.value:x))}/><button type="button" aria-label={`Убрать пункт ${index+1}: ${title}`} onClick={()=>edit(section,answer[section].filter((_,i)=>i!==index))}>×</button></div>)}<button type="button" disabled={answer[section].length>=12} onClick={()=>edit(section,[...answer[section],''])}>Добавить пункт</button></details>)}
  </fieldset>}
  {reference&&<p className="source-note">{reference.model} · {new Date(reference.generated_at).toLocaleString('ru-RU')}{reference.edited_at?' · есть правки преподавателя':''}</p>}
  {!approved&&<label className="reference-confirm"><input id="reference-reviewed" type="checkbox" checked={card.reference_checked===true&&current} disabled={!current||locked} onChange={e=>store.edit('reference_checked',null,e.target.checked)}/>Я проверил эталонный ответ и его соответствие карточке</label>}
  {approved&&!reference&&<p className="source-note">Ранее утверждённая карточка без эталона. Верните её на доработку, чтобы добавить ответ.</p>}
 </section>;
}
