import {useEffect,useRef,useState} from 'react';
import {serverLogout} from './session-auth.js';
export const PROFILE='giik.teacher.profile.v1';
export function readProfile(){try{return JSON.parse(localStorage.getItem(PROFILE))?.name||'Преподаватель';}catch{return 'Преподаватель';}}
const paths={home:'M2 11L12 3l10 8M5 10v11h5v-7h4v7h5V10',layers:'M2 7l10-5 10 5-10 5zM2 12l10 5 10-5M2 17l10 5 10-5',message:'M3 3h18v15H9l-5 4v-4H3z',cards:'M3 4h18v16H3zM6 8h12M6 12h12M6 16h7',settings:'M10 2h4l1 3 3 1 3-1 2 4-2 2v3l2 2-2 4-3-1-3 1-1 3h-4l-1-3-3-1-3 1-2-4 2-2v-3L1 9l2-4 3 1 3-1zM16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0',search:'M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0M15 15l7 7',filter:'M3 3h18l-7 9v8l-4 2V12z',plus:'M12 3v18M3 12h18',file:'M6 2h8l5 5v15H6zM14 2v6h5',users:'M14 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0M2 22v-3a8 8 0 0 1 16 0v3M16 3a4 4 0 0 1 0 8M20 22v-4a9 9 0 0 0-3-6',chart:'M3 21V13h4v8zM10 21V8h4v13zM17 21V2h4v19z',exit:'M13 3H4v18h9M10 12h12M17 7l5 5-5 5',arrow:'M2 12h25M20 6l7 6-7 6'};
export function Icon({name}){return <svg viewBox={`0 0 ${name==='arrow'?30:24} 24`} fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><path d={paths[name]||paths.file}/></svg>;}
<<<<<<< HEAD
export const sections={home:'Главная','create-training':'Создание тренировки','scenario-builder':'Конструктор сценариев','legacy-builder':'Старые упражнения',trainings:'Тренировки',monitoring:'Мониторинг',scenarios:'Сценарии',students:'Обучающиеся',results:'Результаты',materials:'Методические материалы',cards:'Карточки',messages:'Сообщения',settings:'Настройки'};
=======
export const sections={home:'Главная','create-training':'Создание тренировки','legacy-builder':'Старые упражнения',trainings:'Тренировки',monitoring:'Мониторинг',scenarios:'Сценарии',students:'Обучающиеся',results:'Результаты',materials:'Методические материалы',cards:'Карточки',messages:'Сообщения',settings:'Настройки'};
>>>>>>> ec5491b6745f1dd11607901b6ecc81befa475fae
export default function Shell({section,children,journal=false}){
 const [profile,setProfile]=useState(readProfile),[open,setOpen]=useState(false),dialog=useRef(null);
 useEffect(()=>{const update=()=>setProfile(readProfile());window.addEventListener('storage',update);window.addEventListener('profile-changed',update);return()=>{window.removeEventListener('storage',update);window.removeEventListener('profile-changed',update);};},[]);
 const link=(key)=> <a key={key} data-section={key} className={key==='settings'?'teacher-settings':undefined} aria-current={(section===key||(key==='trainings'&&['create-training','monitoring'].includes(section)))?'page':undefined} href={'/teacher#'+key} onClick={()=>setOpen(false)}>{journal&&<Icon name={({home:'home',trainings:'layers',scenarios:'file',students:'users',results:'chart',cards:'cards',messages:'message',settings:'settings'})[key]}/>}<span>{sections[key]}</span></a>;
 useEffect(()=>{document.body.classList.toggle('teacher-menu-open',open);return()=>document.body.classList.remove('teacher-menu-open');},[open]);
<<<<<<< HEAD
 return <><div id="teacher-shell"><a className="teacher-skip" href={'#'+(location.pathname==='/cards'?'workshop':'teacher-content')}>К содержимому</a><aside className="teacher-sidebar"><nav aria-label="Меню преподавателя">{Object.keys(sections).filter(k=>!['settings','create-training','monitoring','legacy-builder'].includes(k)).map(link)}</nav>{link('settings')}{journal&&<div className="journal-sidebar-footer"><span>Локальный стенд</span><span>© 2026</span></div>}</aside><header className="teacher-header">{section==='cards'&&!journal&&<a className="creation-brand" href="/teacher"><strong>112</strong><span>Создание карточек</span></a>}<button className="teacher-menu" aria-label="Открыть меню" aria-expanded={open} onClick={()=>setOpen(!open)}>☰</button><div className="teacher-profile"><a href="/teacher#settings"><span id="profile-name">{profile}</span><small>Преподаватель</small></a><button id="teacher-exit" title="Завершить работу" aria-label="Завершить работу" onClick={()=>{if(document.querySelector('#generate:disabled')||document.querySelector('#editor[inert]')){alert('Дождитесь текущей операции. Генерацию можно остановить после текущей карточки.');return;}dialog.current.showModal();}}><Icon name="exit"/></button></div></header><dialog id="teacher-exit-dialog" ref={dialog}><h2>Завершить работу?</h2><p>Сохранённые карточки останутся в этом браузере.</p><div className="teacher-dialog-actions"><button id="teacher-stay" onClick={()=>dialog.current.close()}>Остаться</button><button id="teacher-close" className="teacher-dark" onClick={async()=>{await serverLogout();location.assign('/');}}>Завершить</button></div></dialog></div>{children}</>;
=======
 return <><div id="teacher-shell"><a className="teacher-skip" href={'#'+(location.pathname==='/cards'?'workshop':'teacher-content')}>К содержимому</a><aside className="teacher-sidebar"><nav aria-label="Меню преподавателя">{Object.keys(sections).filter(k=>!['settings','create-training','monitoring','legacy-builder'].includes(k)).map(link)}</nav>{link('settings')}{journal&&<div className="journal-sidebar-footer"><span>Локальный стенд</span><span>© 2026</span></div>}</aside><header className="teacher-header">{section==='cards'&&!journal&&<a className="creation-brand" href="/teacher"><strong>112</strong><span>Создание карточек</span></a>}<button className="teacher-menu" aria-label="Открыть меню" aria-expanded={open} onClick={()=>setOpen(!open)}>☰</button><div className="teacher-profile"><a href="/teacher#settings"><span id="profile-name">{profile}</span><small>Преподаватель</small></a><button id="teacher-exit" title="Завершить работу" aria-label="Завершить работу" onClick={()=>{if(document.querySelector('#generate:disabled')||document.querySelector('#editor[inert]')){alert('Дождитесь текущей операции. Генерацию можно остановить после текущей карточки.');return;}dialog.current.showModal();}}><Icon name="exit"/></button></div></header><dialog id="teacher-exit-dialog" ref={dialog}><h2>Завершить работу?</h2><p>Сохранённые карточки останутся в этом браузере.</p><div className="teacher-dialog-actions"><button id="teacher-stay" onClick={()=>dialog.current.close()}>Остаться</button><button id="teacher-close" className="teacher-dark" onClick={()=>location.assign('/')}>Завершить</button></div></dialog></div>{children}</>;
>>>>>>> ec5491b6745f1dd11607901b6ecc81befa475fae
}
