import {useEffect,useRef,useState} from 'react';
export const PROFILE='giik.teacher.profile.v1';
export function readProfile(){try{return JSON.parse(localStorage.getItem(PROFILE))?.name||'Преподаватель';}catch{return 'Преподаватель';}}
const paths={plus:'M12 3v18M3 12h18',file:'M6 2h8l5 5v15H6zM14 2v6h5',users:'M14 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0M2 22v-3a8 8 0 0 1 16 0v3M16 3a4 4 0 0 1 0 8M20 22v-4a9 9 0 0 0-3-6',chart:'M3 21V13h4v8zM10 21V8h4v13zM17 21V2h4v19z',exit:'M13 3H4v18h9M10 12h12M17 7l5 5-5 5',arrow:'M2 12h25M20 6l7 6-7 6'};
export function Icon({name}){return <svg viewBox={`0 0 ${name==='arrow'?30:24} 24`} fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><path d={paths[name]||paths.file}/></svg>;}
export const sections={home:'Главная',trainings:'Тренировки',scenarios:'Сценарии',students:'Обучающиеся',results:'Результаты',cards:'Карточки',messages:'Сообщения',settings:'Настройки'};
export default function Shell({section,children}){
 const [profile,setProfile]=useState(readProfile),[open,setOpen]=useState(false),dialog=useRef(null);
 useEffect(()=>{const update=()=>setProfile(readProfile());window.addEventListener('storage',update);window.addEventListener('profile-changed',update);return()=>{window.removeEventListener('storage',update);window.removeEventListener('profile-changed',update);};},[]);
 const link=(key)=> <a key={key} data-section={key} className={key==='settings'?'teacher-settings':undefined} aria-current={section===key?'page':undefined} href={key==='cards'?'/cards':'/teacher#'+key} onClick={()=>setOpen(false)}>{sections[key]}</a>;
 useEffect(()=>{document.body.classList.toggle('teacher-menu-open',open);return()=>document.body.classList.remove('teacher-menu-open');},[open]);
 return <><div id="teacher-shell"><a className="teacher-skip" href={'#'+(section==='cards'?'workshop':'teacher-content')}>К содержимому</a><aside className="teacher-sidebar"><nav aria-label="Меню преподавателя">{Object.keys(sections).filter(k=>k!=='settings').map(link)}</nav>{link('settings')}</aside><header className="teacher-header">{section==='cards'&&<a className="creation-brand" href="/teacher"><strong>112</strong><span>Создание карточек</span></a>}<button className="teacher-menu" aria-label="Открыть меню" aria-expanded={open} onClick={()=>setOpen(!open)}>☰</button><div className="teacher-profile"><a href="/teacher#settings"><span id="profile-name">{profile}</span><small>Преподаватель</small></a><button id="teacher-exit" title="Завершить работу" aria-label="Завершить работу" onClick={()=>{if(document.querySelector('#generate:disabled')||document.querySelector('#editor[inert]')){alert('Дождитесь текущей операции. Генерацию можно остановить после текущей карточки.');return;}dialog.current.showModal();}}><Icon name="exit"/></button></div></header><dialog id="teacher-exit-dialog" ref={dialog}><h2>Завершить работу?</h2><p>Сохранённые карточки останутся в этом браузере.</p><div className="teacher-dialog-actions"><button id="teacher-stay" onClick={()=>dialog.current.close()}>Остаться</button><button id="teacher-close" className="teacher-dark" onClick={()=>location.assign('/')}>Завершить</button></div></dialog></div>{children}</>;
}
