import {useEffect,useState} from 'react';
import {api} from './api.js';

const labels={waiting:'Преподаватель назначает роль',operator:'Оператор 112',dds:'Диспетчер 112',service:'Диспетчер службы'};
const initials=name=>name.trim().split(/\s+/).slice(0,2).map(word=>word[0]?.toUpperCase()).join('');

export default function StudentLobby({name,onJoined,onStarted}){
 const [code,setCode]=useState(()=>new URLSearchParams(location.search).get('room')||''),[entryName,setEntryName]=useState(()=>new URLSearchParams(location.search).get('name')||(name==='Обучающийся'?'':name));
 const [room,setRoom]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [joinedName,setJoinedName]=useState('');
 useEffect(()=>{if(!room||room.status!=='prepared')return;let live=true;const poll=async()=>{try{const next=await api('training_lobby',{resource_id:room.id});if(!live)return;setRoom(next);if(next.status==='active'){setRoom(null);onStarted(joinedName);}}catch(e){if(live)setError(e.message);}};const timer=setInterval(poll,2500);return()=>{live=false;clearInterval(timer);};},[room?.id,room?.status,joinedName]);
 const join=async event=>{event.preventDefault();setError('');setBusy(true);try{const found=await api('training_find_lobby',{room_code:code.trim().toUpperCase()});let student=entryName.trim();if(student.length<3||student==='Обучающийся')throw Error('Введите своё имя и фамилию.');const result=await api('training_join',{resource_id:found.id,student});student=result.participants.find(p=>p.student.toLocaleLowerCase()===student.toLocaleLowerCase())?.student||student;setJoinedName(student);onJoined(student);setRoom(result);}catch(e){setError(e.message);}finally{setBusy(false);}};
 const own=room?.participants.find(p=>p.student.toLocaleLowerCase()===joinedName.toLocaleLowerCase());
 return <>{!room?<section className="lobby-entry student-panel"><div><small>СОВМЕСТНАЯ ТРЕНИРОВКА</small><h2>Войти в комнату ожидания</h2><p>Преподаватель выдаст код, назначит роль и начнёт общую сессию.</p></div><form onSubmit={join}><label>Код комнаты<input aria-label="Код комнаты" value={code} maxLength={8} placeholder="Например, A1B2C3D4" onChange={e=>setCode(e.target.value.toUpperCase())}/></label><label>Ваше имя<input aria-label="Имя участника" value={entryName} maxLength={160} placeholder="Фамилия Имя" onChange={e=>setEntryName(e.target.value)}/></label><button className="student-blue" disabled={busy||code.trim().length!==8||entryName.trim().length<3}>{busy?'Подключаем…':'Войти в комнату →'}</button></form>{error&&<p role="alert" className="lobby-error">{error}</p>}</section>:<div className="lobby-overlay" role="dialog" aria-modal="true" aria-label="Комната ожидания обучающегося"><div className="lobby-shell"><header className="lobby-top"><span className="lobby-mark">112 <small>ОБЩАЯ ТРЕНИРОВКА</small></span><button onClick={()=>setRoom(null)} aria-label="Выйти из комнаты">×</button></header><div className="lobby-hero" style={room.banner_key?{backgroundImage:`linear-gradient(90deg,#091d2ce8,#0e344498),url(/banners/${room.banner_key}.webp)`}:undefined}><span className="lobby-kicker">КОМНАТА {room.room_code} · ОЖИДАНИЕ ЗАПУСКА</span><h2>{room.title}</h2><p>{room.description||'Перед началом ознакомьтесь с участниками и своей ролью. Карточка появится после запуска преподавателем.'}</p><div className="lobby-hero-stats"><span>{room.card_count} карточек</span><span>{room.participants.length} участников</span><span>{room.mode==='testing'?'Тестирование':room.mode==='practice'?'Тренировка':'Обучение'}</span></div></div><main className="lobby-main"><div className="lobby-assignment"><div className="lobby-avatar">{initials(joinedName)}</div><div><small>ВАША РОЛЬ</small><strong>{labels[own?.role]||'Ожидает назначения'}</strong><span>{own?.role==='service'?`Служба ${own.service}`:'Следите за экраном — данные обновляются автоматически.'}</span></div></div><div className="lobby-heading"><div><h3>Участники</h3><p>Преподаватель распределяет обязанности до начала занятия.</p></div><span className="lobby-live"><i/>Связь с комнатой</span></div><div className="lobby-roster">{room.participants.map(p=><article className={'lobby-person '+(p.student===joinedName?'self':'')} key={p.id}><div className="lobby-avatar">{initials(p.student)}</div><strong>{p.student}</strong><small>{labels[p.role]||p.role}{p.service?' · '+p.service:''}</small></article>)}</div>{error&&<p role="alert" className="lobby-error">{error}</p>}<footer className="lobby-footer"><p>Оставайтесь на этой странице. После запуска автоматически откроется ваше рабочее место.</p><button onClick={()=>setRoom(null)}>Вернуться к списку</button></footer></main></div></div>}</>;
}
