import {useEffect,useRef,useState} from 'react';
import {serverLogout,serverIdentity} from './session-auth.js';
import {api} from './api.js';
import {Icon} from './Shell.jsx';
import StudentSession from './StudentSession.jsx';
import StudentBriefing from './StudentBriefing.jsx';
import StudentResult from './StudentResult.jsx';
import DispatcherDesk from './DispatcherDesk.jsx';
import StudentLobby from './StudentLobby.jsx';
import Materials from './Materials.jsx';
const PROFILE='giik.student.profile.v1';
const readName=()=>{try{return new URLSearchParams(location.search).get('name')||sessionStorage.getItem('practice:student:tab')||JSON.parse(localStorage.getItem(PROFILE))?.name||localStorage.getItem('practice:student')||'Обучающийся';}catch{return 'Обучающийся';}};
const sections={trainings:'Мои тренировки',cards:'Карточки происшествий',results:'Результаты',materials:'Методические материалы',messages:'Сообщения',profile:'Профиль'};
const statuses={available:'Не начата',awaiting_call:'Входящий вызов',queued:'Ожидает предыдущую',active:'В процессе',submitted:'На проверке',pending_teacher:'На проверке',reviewed:'Проверена'};
const workflow=w=>w==='dds'?'Диспетчер ДДС':'Оператор 112';
const duration=seconds=>{const s=Math.max(0,Math.floor(seconds));return [Math.floor(s/3600),Math.floor(s/60)%60,s%60].map(x=>String(x).padStart(2,'0')).join(':');};

const pendingCall=s=>s?.status==='awaiting_call'||(s?.status==='active'&&s?.workflow==='caller'&&!s?.activated_at&&!s?.call_answered_at&&s?.history?.length===1);

function IncomingCall({session,busy,onAnswer,onClose}){
 useEffect(()=>{const key=e=>{if(e.key==='Insert'&&!busy){e.preventDefault();onAnswer();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[busy,onAnswer]);
 return <aside className="student-incoming-popover" role="dialog" aria-label="Входящий вызов 112" aria-modal="false"><span className="student-incoming-popover-icon" aria-hidden="true">☎</span><div><strong>Входящий звонок</strong><span>с номера {session.card.phone_aon||'номер не определён'}</span></div><button id="student-answer-call" className="student-incoming-answer" disabled={busy} onClick={onAnswer}>{busy?'Соединяем…':'ОТВЕТИТЬ НА ВЫЗОВ'}</button><button className="student-incoming-dismiss" aria-label="Свернуть входящий вызов" disabled={busy} onClick={onClose}>×</button></aside>;
}

export default function Student(){
 const [name,setName]=useState(readName),[profileName,setProfileName]=useState(readName),[section,setSection]=useState('trainings');
 const [data,setData]=useState({tasks:[],sessions:[],fields:{}}),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(false);
 const [brief,setBrief]=useState(null),[stage,setStage]=useState('details'),[resultMode,setResultMode]=useState(false);
 const [session,setSession]=useState(null),[values,setDraft]=useState({}),[dirty,setDirty]=useState(false),[tick,setTick]=useState(Date.now()),[filter,setFilter]=useState({query:'',status:'',period:''}),[applied,setApplied]=useState(filter),[ascending,setAscending]=useState(false);
 const dialog=useRef(null),[help,setHelp]=useState('');
 const notify=(text,isError=false)=>{setNotice(text);setError(isError);};
 const load=async()=>{const result=await api('student_overview',{student:name});setData(result);setLoaded(true);};
 useEffect(()=>{let active=true;setLoaded(false);setData({tasks:[],sessions:[],fields:{}});api('student_overview',{student:name}).then(result=>{if(active){setData(result);setLoaded(true);}}).catch(e=>{if(active)notify(e.message,true);});return()=>{active=false;};},[name]);
 useEffect(()=>{document.body.dataset.studentReady=String(loaded);return()=>{delete document.body.dataset.studentReady;};},[loaded]);
 useEffect(()=>{const id=setInterval(()=>setTick(Date.now()),1000);return()=>clearInterval(id);},[]);
 useEffect(()=>{if(!session||session.status!=='active'||!dirty||busy)return;let cancelled=false;const id=setTimeout(async()=>{try{await api('student_action',{full_form:true,student:name,id:session.id,operation:'save_card',card:values});if(!cancelled)setDirty(false);}catch{/* The browser draft remains available until the learner retries. */}},1200);return()=>{cancelled=true;clearTimeout(id);};},[session?.id,session?.status,dirty,busy,values,name]);
 useEffect(()=>{if(!session||session.status!=='active'||!session.training?.training_id)return;const id=setInterval(async()=>{try{const updated=await api('student_overview',{student:name});setData(updated);const row=updated.sessions.find(s=>s.id===session.id);if(row&&row.status!=='active'){setSession(null);setDraft({});setDirty(false);notify('Время карточки истекло. Сохранённый черновик передан преподавателю. Примите следующий вызов.');}}catch(e){notify(e.message,true);}},3000);return()=>clearInterval(id);},[session?.id,session?.status,session?.training?.training_id,name]);
 useEffect(()=>{const warn=e=>{if(busy||dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[busy,dirty]);
 const saveDraft=next=>{setDraft(next);setDirty(true);try{localStorage.setItem('practice:card:'+session.id,JSON.stringify(next));}catch{notify('Не удалось сохранить черновик в браузере. Нажмите «Сохранить».',true);}};
 const enter=s=>{setSession(s);let draft=null;try{draft=s.status==='active'?JSON.parse(localStorage.getItem('practice:card:'+s.id)):null;}catch{}if(draft&&s.legacy_map&&Object.values(s.legacy_map).every(k=>typeof draft[k]==='string'))draft={...s.card,...Object.fromEntries(Object.entries(s.legacy_map).map(([key,old])=>[key,draft[old]]))};const valid=draft&&Object.keys(s.card).every(k=>typeof draft[k]==='string');setDraft(valid?draft:s.card);setDirty(!!valid);};
 const open=async(row,confirmed=false)=>{if(busy)return;if(row.status==='queued'){notify('Сначала завершите предыдущую карточку этого сценария.',true);return;}if(row.status==='available'&&!confirmed){setBrief(row);setStage('details');return;}setBusy(true);notify('');try{const s=row.status==='available'?await api('student_start',{full_form:true,student:name,task_id:row.id}):await api('student_action',{full_form:true,student:name,id:row.id,operation:'student'});enter(s);setBrief(null);setResultMode(!['active','awaiting_call'].includes(s.status));await load();}catch(e){notify(e.message,true);}finally{setBusy(false);}};
 const act=async(operation,payload={})=>{if(busy||!session)return false;setBusy(true);const previousId=session.id;try{const s=await api('student_action',{full_form:true,student:name,id:previousId,operation,...payload});if(operation==='accept'){setSession(s);setDraft(s.card);setDirty(false);await load();notify('Вызов принят. Слушайте заявителя и уточняйте обстоятельства.');return true;}if(operation==='save_card'){setSession(s);setDraft(s.card);setDirty(false);try{localStorage.removeItem('practice:card:'+previousId);}catch{}notify('Карточка сохранена.');return true;}if(operation==='submit'){try{localStorage.removeItem('practice:card:'+previousId);}catch{}setDirty(false);if(s.auto_advanced){enter(s);setResultMode(false);await load();notify(`Карточка завершена. Автоматически открыта карточка ${s.training?.card_index||''} из ${s.training?.card_total||''}.`);return true;}setSession(s);setDraft(s.card);setResultMode(true);await load();notify(s.scenario_complete?'Все назначенные карточки сценария завершены. Результаты переданы преподавателю.':s.training?.handoff_to_dds?'Карточка передана диспетчеру 112 для проверки и направления службам.':'Работа сдана и доступна преподавателю для проверки.');return true;}setSession(s);notify('');return true;}catch(e){notify(e.message,true);return false;}finally{setBusy(false);}};
 const navigate=key=>{if(busy)return;setSection(key);setBrief(null);setSession(null);setResultMode(false);setDirty(false);notify('');};
 const info=kind=>{setHelp(kind);dialog.current.showModal();};
 const current=data.sessions.find(s=>s.id===session?.id&&['active','awaiting_call'].includes(s.status))||data.sessions.find(s=>['active','awaiting_call'].includes(s.status)),currentTime=current&&current.status==='active'&&current.activated_at?duration((tick-new Date(current.activated_at||current.created_at).getTime())/1000):'00:00:00';
 const currentPack=current?.training?.plan_id?data.sessions.filter(s=>s.training?.plan_id===current.training.plan_id):current?[current]:[];
 const currentDone=currentPack.filter(s=>['submitted','pending_teacher','reviewed'].includes(s.status)).length,currentTotal=current?.training?.card_total||currentPack.length||1;
 const started=new Set(data.sessions.map(s=>s.task_id));
 const allRows=[...data.sessions,...data.tasks.filter(t=>!started.has(t.id)).map(t=>({...t,status:'available'}))];
 const rows=allRows.filter(r=>(section!=='results'||['submitted','pending_teacher','reviewed'].includes(r.status))&&(section!=='cards'||r.status!=='available')&&(!applied.query||r.title.toLocaleLowerCase().includes(applied.query.toLocaleLowerCase()))&&(!applied.status||r.status===applied.status)&&(!applied.period||Date.now()-new Date(r.created_at).getTime()<=Number(applied.period)*86400000)).sort((a,b)=>(ascending?1:-1)*(new Date(a.created_at)-new Date(b.created_at)));
 const serviceCodes=(()=>{try{return session?.format==='incident-v1'?JSON.parse(values._services||'[]'):null;}catch{return [];}})();
 const exit=async()=>{if(busy)return;if(dirty&&!confirm('Выйти? Черновик останется в этом браузере.'))return;await serverLogout();location.assign('/');};
 return <><header className="student-header"><span>Система 112. Учебный контур</span><div><Icon name="users"/><span><strong>{name}</strong><small>Обучающийся</small></span><button id="student-exit" disabled={busy} onClick={exit}>Выйти</button></div></header>
  <section className="student-channels"><div><span>Учебная сессия</span><div className="student-buttons"><button onClick={()=>info('instruction')}>Инструкция</button><button onClick={()=>info('support')}>Техническая поддержка</button></div></div><div className={pendingCall(session)?'student-channel-ringing':''}><span>Телефон 112 (учебный)</span>{pendingCall(session)&&<span className="student-channel-call" aria-label="Входящий вызов">☎</span>}<strong>{pendingCall(session)?'ВХОДЯЩИЙ ВЫЗОВ':session?.status==='active'&&session.workflow==='caller'?'Заявитель на линии':'Ожидание тренировки'}</strong><small>{pendingCall(session)?'Откройте вызов и ответьте заявителю':'Учебный разговор · текст и голос'}</small></div><div><span>Внутренний телефон</span><strong>{session?.dds?.service_name||'Служба не выбрана'}</strong><small>{session?.dds?.connection==='connected'?'Соединение установлено':'Доступен в тренировке ДДС'}</small></div><div><span>Чат с преподавателем</span><strong>Не подключён</strong><small>Замечания появятся в результатах</small></div><div><strong>Мои тренировки</strong><small>Учебный контур</small><small>Пользователь: {name}</small></div><div className="student-timer"><strong>{currentTime}</strong><small>{current?'С начала текущей тренировки':'Нет активной тренировки'}</small></div></section>
  <div className="student-layout"><aside className="student-nav"><nav aria-label="Меню обучающегося">{Object.entries(sections).map(([key,label])=><button key={key} data-student-section={key} aria-current={section===key?'page':undefined} disabled={busy} onClick={()=>navigate(key)}><Icon name={({trainings:'layers',cards:'cards',results:'chart',messages:'message',profile:'settings'})[key]}/>{label}</button>)}</nav></aside>
  <main className="student-main" id="student-main">{notice&&<p role={error?'alert':'status'} className={'student-message '+(error?'error':'')}>{notice}</p>}{!loaded&&!notice&&<p>Загружаю тренировки…</p>}{!loaded&&error&&<button onClick={()=>load().catch(e=>notify(e.message,true))}>Повторить</button>}{!session&&!brief&&section==='trainings'&&<><StudentLobby name={name} onJoined={student=>{sessionStorage.setItem('practice:student:tab',student);const url=new URL(location.href);url.searchParams.delete('name');history.replaceState(null,'',url);localStorage.setItem(PROFILE,JSON.stringify({name:student}));localStorage.setItem('practice:student',student);setName(student);setProfileName(student);}} onStarted={async student=>{try{const updated=await api('student_overview',{student});setData(updated);setLoaded(true);const pending=updated.sessions.find(row=>row.status==='awaiting_call');if(pending){enter(await api('student_action',{full_form:true,student,id:pending.id,operation:'student'}));setSection('trainings');notify('Входящий вызов 112. Ответьте заявителю.');}else notify('Тренировка началась. Ожидайте передачи от оператора.');}catch(e){notify(e.message,true);}}}/><DispatcherDesk student={name}/></>}
   {brief?<StudentBriefing task={brief} {...{stage,setStage,busy}} start={()=>open(brief,true)} back={()=>setBrief(null)}/>:session&&resultMode?<StudentResult session={session} fields={session?.field_labels||data.fields} summary={data.sessions.find(s=>s.id===session.id)} allSessions={data.sessions} back={()=>navigate('trainings')} openCard={()=>setResultMode(false)}/>:session&&!pendingCall(session)?<StudentSession key={session.id} {...{session,values,dirty,busy,act}} fields={session?.field_labels||data.fields} setValues={saveDraft} back={()=>navigate('trainings')}/>:<><h1>{sections[section]}</h1>
   {section==='materials'?<Materials/>:section==='profile'?(serverIdentity()?<section className="student-panel student-profile"><label>Имя обучающегося<input id="student-profile-name" value={serverIdentity().name} disabled/></label><p>Профиль связан с серверной учётной записью <b>{serverIdentity().login}</b>. ФИО и системную роль изменяет администратор.</p></section>:<form className="student-panel student-profile" onSubmit={e=>{e.preventDefault();if(!profileName.trim())return;try{localStorage.setItem(PROFILE,JSON.stringify({name:profileName.trim()}));localStorage.setItem('practice:student',profileName.trim());sessionStorage.setItem('practice:student:tab',profileName.trim());setName(profileName.trim());notify('Имя сохранено.');}catch{notify('Не удалось сохранить имя.',true);}}}><label>Имя обучающегося<input id="student-profile-name" value={profileName} required maxLength={160} onChange={e=>setProfileName(e.target.value)}/></label><p>По этому имени показываются ваши учебные работы в локальном стенде.</p><button className="student-blue">Сохранить профиль</button></form>):section==='messages'?<section className="student-panel"><h2>Сообщений пока нет</h2><p>Чат с преподавателем ещё не подключён. Его заключения по сданным работам доступны в разделе «Результаты».</p><button onClick={()=>navigate('results')}>Открыть результаты</button></section>:<>
    <p className="student-subtitle">{section==='results'?'Сданные работы и результаты, подтверждённые преподавателем':section==='cards'?'Карточки ваших учебных сеансов':'Доступные учебные тренировки и результаты их прохождения'}</p>
    <form className="student-filters" onSubmit={e=>{e.preventDefault();setApplied({...filter,query:filter.query.trim()});}}><label>Поиск по названию<input id="student-search" placeholder="Введите название тренировки или сценария" value={filter.query} onChange={e=>setFilter({...filter,query:e.target.value})}/></label><label>Статус<select id="student-status" value={filter.status} onChange={e=>setFilter({...filter,status:e.target.value})}><option value="">Все статусы</option>{Object.entries(statuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Период<select id="student-period" value={filter.period} onChange={e=>setFilter({...filter,period:e.target.value})}><option value="">Всё время</option><option value="7">Последние 7 дней</option><option value="30">Последние 30 дней</option></select></label><button className="student-blue">Найти</button><button type="button" onClick={()=>{const empty={query:'',status:'',period:''};setFilter(empty);setApplied(empty);}}>Сбросить</button></form>
    {section==='trainings'&&<section className="student-current student-panel"><h2>Текущая тренировка</h2>{current?<div className="student-current-grid"><div><small>Сценарий</small><strong>{current.training?.title||current.title}</strong><small>Текущая карточка</small><span>{current.title} · {workflow(current.workflow)}</span></div><div><small>Выполнено карточек</small><strong>{currentDone} из {currentTotal}</strong><progress max={currentTotal} value={currentDone}/><span>{Math.round(currentDone/currentTotal*100)}%</span></div><div><small>С начала тренировки</small><strong>{currentTime}</strong></div><div><button className="student-dark" id="student-continue" disabled={busy} onClick={()=>open(current)}>Продолжить</button><button className="student-link" disabled={busy} onClick={()=>open(current)}>Перейти к карточке</button></div></div>:<p className="student-empty">Нет активной тренировки. Выберите доступное задание ниже.</p>}</section>}
    <section className="student-panel student-list"><h2>{section==='results'?'Результаты тренировок':section==='cards'?'Мои карточки':'Список доступных тренировок'}<button id="student-refresh" disabled={busy} onClick={async()=>{setBusy(true);try{await load();notify('Список обновлён.');}catch(e){notify(e.message,true);}finally{setBusy(false);}}}>Обновить</button></h2><div className="student-table-scroll"><table className="student-table"><thead><tr>{['№','Название тренировки','Сценарий','Преподаватель'].map(t=><th key={t}>{t}</th>)}<th><button onClick={()=>setAscending(!ascending)}>Дата и время {ascending?'↑':'↓'}</button></th>{['Режим','Карточки','Статус','Результат','Действие'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id} data-student-row={r.id}><td>{i+1}</td><td><strong>{r.training?.title||r.title}</strong>{r.training&&<small>Карточка {r.training.card_index} из {r.training.card_total}</small>}</td><td>{r.training?r.title+' · '+workflow(r.workflow):workflow(r.workflow)}</td><td>{r.training?.teacher||r.teacher||'—'}</td><td>{new Date(r.created_at).toLocaleString('ru-RU',{dateStyle:'short',timeStyle:'short'})}</td><td>{r.training?.mode==='testing'?'Тестирование':r.training?.mode==='practice'?'Тренировка':'Обучение'}</td><td>{r.training?.card_total||1}</td><td><span className={'student-status '+r.status}>{statuses[r.status]}</span></td><td>{r.grade!=null?r.grade+' / 5':'—'}</td><td><button disabled={busy||r.status==='queued'} className={r.status==='active'?'student-dark':''} onClick={()=>open(r)}>{r.status==='available'?'Начать':r.status==='queued'?'Ожидает':r.status==='active'?'Продолжить':r.status==='awaiting_call'?'Открыть вызов':r.status==='reviewed'?'Результат':'Посмотреть'}</button></td></tr>)}{!rows.length&&<tr><td colSpan={10} className="student-empty">{!loaded?'Загрузка…':allRows.length?'По выбранным условиям ничего не найдено.':'Тренировок пока нет. Преподавателю нужно утвердить учебное задание.'}</td></tr>}</tbody></table></div></section><p className="student-count">Показано {rows.length} из {allRows.filter(r=>section==='results'?['submitted','pending_teacher','reviewed'].includes(r.status):section==='cards'?r.status!=='available':true).length}</p>
   </> }</>}
  </main></div>
  {pendingCall(session)&&<IncomingCall session={session} busy={busy} onAnswer={()=>act('accept')} onClose={()=>navigate('trainings')}/>}
  <footer className="student-dock"><strong>Службы:</strong><div className="student-service-tabs">{serviceCodes?.length===0&&<span>Выберите службы в карточке</span>}{(serviceCodes?serviceCodes.map(code=>session.service_labels?.[code]||code):['Служба 101','Служба 104','Служба 102','Деж. ЖКХ','ЦЭМП','ЦОДД','Мослифт']).map(label=><button key={label} onClick={()=>serviceCodes?document.querySelector('.student-service-choices')?.scrollIntoView({behavior:'smooth',block:'center'}):info('services')}><span>⌃</span>{label}</button>)}</div><div className="student-dock-actions"><button className="student-dock-save" disabled={busy||session?.status!=='active'} onClick={()=>act('save_card',{card:values})}>СОХРАНИТЬ</button><button aria-label="Инструкция" onClick={()=>info('instruction')}><Icon name="file"/></button><button aria-label="Сообщения" disabled={busy} onClick={()=>navigate('messages')}><Icon name="message"/></button></div></footer>
  <dialog ref={dialog} className="student-dialog"><h2>{help==='instruction'?'Как работать':help==='services'?'Службы реагирования':'Техническая поддержка'}</h2>{help==='instruction'?<><p>Выберите тренировку и нажмите «Начать». Общайтесь с заявителем или службой, самостоятельно заполняйте карточку и сдайте работу преподавателю.</p><p>Прогресс сохраняется. Заключение и оценка появятся после проверки преподавателем.</p><p>Здесь доступны учебные задания существующего прототипа. Утверждённые карточки преподавателя доступны как отдельные тренировки с полной формой и виртуальным заявителем ИИ.</p></>:help==='services'?<p>Панель служб показана по макету. Разговор с конкретной службой доступен внутри тренировки «Диспетчер ДДС». Реальная отправка подразделений не подключена.</p>:<p>При ошибке сохраните карточку и обратитесь к преподавателю. Отправка обращений в техническую поддержку пока не подключена.</p>}<button onClick={()=>dialog.current.close()}>Понятно</button></dialog>
 </>;
}
