import {Icon} from './Shell.jsx';
const steps=['Ознакомиться с условиями учебного вызова','Уточнить сведения у собеседника','Самостоятельно заполнить карточку','Сохранить и сдать работу преподавателю'];
export default function StudentBriefing({task,stage,setStage,start,back,busy}){
 const banner=task.banner_key?`/banners/${task.banner_key}.webp`:null;
 const workflow=task.workflow==='dds'?'Диспетчер ДДС':'Оператор 112';
 const description=task.workflow==='dds'?'Проверьте полученную карточку 112 по доступному уточнению. Свяжитесь с представителем службы и передайте сведения о происшествии.':'Примите учебное сообщение, задайте заявителю уточняющие вопросы и самостоятельно заполните карточку происшествия.';
 return <><button className="student-link" onClick={back} disabled={busy}>← Назад к списку</button><div className="student-title-row"><div><h1>{stage==='launch'?'Запуск тренировки':task.title}</h1><p className="student-subtitle">{stage==='launch'?'Подтвердите параметры и начните выполнение учебной тренировки':'Ознакомьтесь с параметрами тренировки и начните выполнение'}</p></div></div>
 {stage==='details'?<div className="student-brief-grid"><section className="student-panel"><h2>Основная информация</h2><dl className="student-fact-list">{[['Сценарий',workflow],['Описание',description],['Тип тренировки','Индивидуальная'],['Количество карточек','1'],['Нормативное время','Не задано'],['Преподаватель',task.teacher||'—'],['Дата и время',new Date(task.created_at).toLocaleString('ru-RU')]].map(([label,value])=><div key={label}><Icon name="file"/><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section><div><blockquote className={`student-motto${banner?' has-banner':''}`}>{banner&&<img className="student-motto-image" src={banner} alt="" aria-hidden="true"/>}<span>Ваша задача — спокойно и внимательно принять сообщение и передать достоверные сведения.</span></blockquote><section className="student-panel"><h2>Что предстоит сделать</h2><ol className="student-steps">{steps.map(s=><li key={s}>{s}</li>)}</ol><p className="student-hint">Для сценариев, назначенных преподавателем, режим «Обучение» может автоматически подсказывать после паузы; в режиме «Тестирование» подсказок нет. Итоговое решение принимает преподаватель.</p></section><button id="student-to-launch" className="student-dark student-wide" onClick={()=>setStage('launch')}>Перейти к запуску →</button></div></div>:<><section className="student-panel student-launch"><div><h2>Информация о тренировке</h2><div className="student-launch-content"><h3>{task.title}</h3><div className="student-launch-facts">{[['Сценарий',workflow],['Преподаватель',task.teacher||'—'],['Формат','Индивидуальная'],['Карточек','1'],['Норматив времени','Не задано']].map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div><p>{description}</p></div></div><aside><h2>Текущий прогресс</h2><div className="student-launch-content"><strong>0 из 1 карточки</strong><progress value="0" max="1"/><p>Тренировка ещё не начата</p></div><h2>Состав тренировки</h2><p className="student-launch-content">{task.title}</p></aside></section><section className="student-panel student-launch-check"><h2>Что нужно сделать</h2><ol className="student-steps">{steps.map(s=><li key={s}>{s}</li>)}</ol><div className="student-buttons"><button id="student-start-confirm" className="student-dark" disabled={busy} onClick={start}>{busy?'Открываю тренировку…':'НАЧАТЬ ТРЕНИРОВКУ'}</button><button disabled={busy} onClick={back}>Вернуться к списку</button></div></section></>}
 </>;
}
