import {useState} from 'react';
export default function StudentResult({session,fields,summary,back,openCard}){
 const [downloadError,setDownloadError]=useState(''),decision=session.result;
 const download=()=>{try{const blob=new Blob([JSON.stringify({training:session.title,student:session.student,status:session.status,card:session.card,result:decision},null,2)],{type:'application/json;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Результат-'+session.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{setDownloadError('Не удалось скачать отчёт. Повторите попытку.');}};
 return <><div className="student-title-row"><div><h1>Результаты тренировки</h1><p className="student-subtitle">Итоговый отчёт по учебной тренировке</p></div><div className="student-buttons"><button onClick={back}>К списку тренировок</button><button className="student-blue" id="student-download-report" onClick={download}>Скачать отчёт</button></div></div>
 {downloadError&&<p role="alert">{downloadError}</p>}
 <section className="student-panel student-result-banner"><span className={'student-result-mark '+(decision?'done':'')}>{decision?'✓':'…'}</span><div><h2>{decision?'Тренировка проверена':'Работа передана преподавателю'}</h2><p>{decision?decision.conclusion:'Ожидайте проверки. Предварительная оценка ИИ не является итоговым результатом.'}</p><div className="student-result-meta"><span><small>Название тренировки</small><strong>{session.title}</strong></span><span><small>Преподаватель</small><strong>{decision?.teacher||summary?.teacher||'—'}</strong></span><span><small>Формат</small><strong>Индивидуальная</strong></span></div></div></section>
 <div className="student-result-metrics">{[['Сдано карточек','1 / 1'],['Общее время',session.duration_seconds!=null?Math.floor(session.duration_seconds/60)+':'+String(session.duration_seconds%60).padStart(2,'0'):'—'],['Норматив','Не задан'],['Отклонение','—'],['Ошибки','—'],['Грамматика','—'],['Оценка ИИ','Не публикуется'],['Оценка преподавателя',decision?decision.grade+' / 5':'На проверке'],['Итог',decision?decision.grade+' / 5':'—']].map(([label,value])=><article className="student-panel" key={label}><small>{label}</small><strong>{value}</strong></article>)}</div>
 <section className="student-panel student-result-recommendation"><h2>Рекомендации преподавателя</h2><p>{decision?.conclusion||'Рекомендации появятся после проверки.'}</p></section>
 <div className="student-result-grid"><section className="student-panel"><h2>Карточка результата</h2><div className="student-result-card-heading"><strong>{session.title}</strong><button onClick={openCard}>Посмотреть разговор и карточку</button></div><div className="student-table-scroll"><table className="student-table student-compare"><thead><tr><th>Поле</th><th>Ваше решение</th><th>Эталон</th><th>Комментарий преподавателя</th></tr></thead><tbody>{Object.entries(fields).map(([key,label])=><tr key={key}><td>{label}</td><td>{session.card[key]||'Не заполнено'}</td><td>{session.reference?(session.reference[key]||'Эталон для этого поля не задан'):'Доступен после проверки'}</td><td>{decision?(decision.fields[key]?.comment||'Не оценивалось по этому сценарию'):'Ожидает проверки'}</td></tr>)}</tbody></table></div></section><aside className="student-panel"><h2>Карточки тренировки (1)</h2><button className="student-result-item" onClick={openCard}><span>1 · {session.title}</span><strong>{decision?decision.grade+' / 5':'На проверке'}</strong></button></aside></div>
 </>;
}
