import {useEffect,useState} from 'react';
import {api} from './api.js';
import {readProfile} from './Shell.jsx';

const demoNames=['Алексей Иванов','Мария Петрова','Дмитрий Соколов','Анна Кузнецова'];
const labels={waiting:'Роль не назначена',operator:'Оператор 112',dds:'Диспетчер 112',service:'Диспетчер службы'};
const initials=name=>name.trim().split(/\s+/).slice(0,2).map(word=>word[0]?.toUpperCase()).join('');

export default function TeacherLobby({id,services,onClose,onActivated}){
 const [room,setRoom]=useState(null),[menu,setMenu]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const refresh=()=>api('training_lobby',{resource_id:id}).then(setRoom).catch(e=>setError(e.message));
 useEffect(()=>{refresh();const timer=setInterval(refresh,3000);return()=>clearInterval(timer);},[id]);
 const act=async fn=>{setBusy(true);setError('');try{const result=await fn();if(result?.participants)setRoom(result);else await refresh();return true;}catch(e){setError(e.message);return false;}finally{setBusy(false);}};
 const assign=async(participant,role,service='')=>{if(await act(()=>api('training_role',{resource_id:id,participant_id:participant.id,teacher:readProfile(),role,service})))setMenu('');};
 const add=async names=>{if(await act(()=>api('training_add_participants',{resource_id:id,teacher:readProfile(),students:names})))setNotice('Участники добавлены. Нажмите на кружок, чтобы назначить роль.');};
 const invite=room?`${location.origin}/student?room=${room.room_code}`:'';
 const ready=room?.participants.some(p=>p.role==='operator')&&room?.participants.some(p=>p.role==='dds')&&room?.participants.every(p=>p.role!=='waiting');
 return <section className="teacher-lobby" aria-label="Комната ожидания преподавателя">{room?<><div className="lobby-top"><span className="lobby-mark">112 <small>КОМНАТА ОЖИДАНИЯ</small></span><button type="button" onClick={onClose}>← Вернуться к тренировкам</button></div><div className="lobby-hero" style={room.banner_key?{backgroundImage:`linear-gradient(90deg,#14262be0,#263b45a8),url(/banners/${room.banner_key}.webp)`}:undefined}><span className="lobby-kicker">{room.status==='prepared'?'УЧАСТНИКИ СОБИРАЮТСЯ':'СЕССИЯ ИДЁТ'}</span><h2>{room.title}</h2><p>{room.description||'Преподаватель распределяет роли перед началом занятия.'}</p><div className="lobby-hero-stats"><span>{room.card_count} карточек</span><span>{room.participants.length} участников</span><span>{room.mode==='testing'?'Тестирование':room.mode==='practice'?'Тренировка':'Обучение'}</span></div></div>
 <div className="lobby-main"><section className="lobby-invite"><div><small>КОД КОМНАТЫ</small><strong>{room.room_code}</strong><p>Обучающиеся вводят код на своём экране или открывают ссылку.{location.hostname==='127.0.0.1'&&<span> Для других компьютеров откройте эту страницу по IP учебной сети.</span>}</p></div><button type="button" onClick={async()=>{try{await navigator.clipboard.writeText(invite);setNotice('Ссылка скопирована.');}catch{setNotice(invite);}}}>Скопировать ссылку</button></section>
 {room.status==='prepared'&&<section className="lobby-add"><div><small>УЧАСТНИКИ</small><h3>Добавить в ожидание</h3><p>Пригласите группу по коду или добавьте демонстрационных обучающихся.</p><div className="lobby-demo-names">{demoNames.map(person=><span key={person}>{initials(person)} · {person}</span>)}</div><button type="button" disabled={busy||demoNames.every(student=>room.participants.some(p=>p.student===student))} onClick={()=>add(demoNames)}>+ Добавить 4 примера</button></div><form onSubmit={e=>{e.preventDefault();if(name.trim()){add([name.trim()]);setName('');}}}><label>Добавить по имени<input value={name} maxLength={160} placeholder="Фамилия Имя" onChange={e=>setName(e.target.value)}/></label><button disabled={busy||!name.trim()}>Добавить</button></form></section>}
 <div className="lobby-heading"><div><h3>Участники комнаты</h3><p>{room.status==='prepared'?'Нажмите на кружок обучающегося и выберите его роль.':'Роли закреплены. Карточки поступают на рабочие места.'}</p></div><span className="lobby-live"><i/>Обновляется автоматически</span></div>
 <div className="lobby-roster">{room.participants.map(person=><article className="lobby-person" key={person.id}><div className="lobby-person-center"><button type="button" className="lobby-avatar-button" aria-label={`Выбрать роль: ${person.student}`} aria-expanded={menu===person.id} disabled={busy||room.status!=='prepared'} onClick={()=>setMenu(menu===person.id?'':person.id)}><span className="lobby-avatar">{initials(person.student)}</span><span className="lobby-avatar-hint">{room.status==='prepared'?'Назначить роль':''}</span></button><strong>{person.student}</strong><span className={'lobby-role '+person.role}>{labels[person.role]||'Роль не назначена'}{person.service?' · '+(services[person.service]||person.service):''}</span></div>
 {menu===person.id&&room.status==='prepared'&&<div className="lobby-role-menu" role="group" aria-label={'Назначить роль: '+person.student}>{Object.entries(labels).map(([role,label])=><button type="button" className={person.role===role?'selected':''} key={role} disabled={busy} onClick={()=>assign(person,role,role==='service'?Object.keys(services)[0]||'':'')}>{label}</button>)}</div>}
 {person.role==='service'&&room.status==='prepared'&&<label className="lobby-service">Служба<select value={person.service} disabled={busy} onChange={e=>assign(person,'service',e.target.value)}>{Object.entries(services).map(([code,label])=><option key={code} value={code}>{code} · {label}</option>)}</select></label>}
 {room.status==='prepared'&&<div className="lobby-person-actions"><a href={`/student?room=${room.room_code}&name=${encodeURIComponent(person.student)}`} target="_blank" rel="noopener noreferrer">Открыть как обучающийся ↗</a><button type="button" disabled={busy} onClick={()=>act(()=>api('training_remove_participant',{resource_id:id,participant_id:person.id,teacher:readProfile()}))}>Убрать</button></div>}</article>)}{!room.participants.length&&<p className="lobby-empty">Участников пока нет. Добавьте примеры или поделитесь кодом комнаты.</p>}</div>
 {error&&<p role="alert" className="lobby-error">{error}</p>}{notice&&<p role="status" className="lobby-note">{notice}</p>}
 <footer className="lobby-footer"><p>{room.status==='prepared'?ready?'Роли назначены. Можно начинать занятие.':'Для запуска назначьте оператора 112, диспетчера 112 и роли остальным участникам.':'Тренировка запущена. Участники видят свои рабочие места.'}</p>{room.status==='prepared'&&<button type="button" className="lobby-start" disabled={busy||!ready} onClick={()=>act(async()=>{await api('training_activate',{resource_id:id});await onActivated();setMenu('');return api('training_lobby',{resource_id:id});})}>Начать тренировку →</button>}</footer></div></>:<p className="lobby-loading">Открываем комнату…</p>}</section>;
}
