import {useEffect,useState} from 'react';
import {api} from './api.js';
import {Icon,PROFILE,readProfile,sections} from './Shell.jsx';
import Materials from './Materials.jsx';
const statuses={active:'В процессе',submitted:'На проверке',pending_teacher:'На проверке',reviewed:'Проверена'};
const workflow=k=>k==='dds'?'Диспетчер ДДС':'Оператор 112';
function Table({rows,empty,blank=false}){return <div className="teacher-table-wrap"><table className="teacher-table"><thead><tr>{['Дата','Название','Сценарий','Обучающийся','Результат'].map(label=><th key={label} scope="col">{label}</th>)}</tr></thead><tbody>{rows.length?rows.map(s=><tr key={s.id}><td>{s.created_at?new Date(s.created_at).toLocaleDateString('ru-RU'):'—'}</td><td><a href={'/training#'+(s.status==='active'?'learn':'works')}>{s.title}</a></td><td>{workflow(s.workflow)}</td><td>{s.student}</td><td>{s.grade!=null?s.grade+' / 5':statuses[s.status]||'—'}</td></tr>):<tr className="empty-row"><td colSpan={5}>{empty}</td></tr>}{blank&&Array.from({length:Math.max(0,4-Math.max(1,rows.length))},(_,i)=><tr key={'blank'+i} className="blank-row" aria-hidden="true"><td colSpan={5}/></tr>)}</tbody></table></div>;}
function Home({data}){return <><section className="teacher-hero"><p className="teacher-eyebrow">Панель преподавателя</p><h1>УПРАВЛЯЙТЕ<br/>ОБУЧЕНИЕМ</h1></section><section className="teacher-actions" aria-label="Быстрые действия">{[
 ['plus','Создать','тренировку','/teacher#create-training'],['file','Выбрать','сценарий','/teacher#scenarios'],['users','Назначить','обучающихся','/teacher#students'],['chart','Посмотреть','результаты','/teacher#results']
 ].map(([icon,first,last,url],i)=><a key={icon} className={'teacher-tile '+(i===0?'primary':'')} href={url}><Icon name={icon}/><span className="tile-label">{first}<br/>{last}</span><span className="tile-arrow"><Icon name="arrow"/></span></a>)}</section><section><div className="teacher-section-heading"><h2>Последние тренировки</h2><span className="rule"/><a href="/teacher#trainings">Все тренировки <Icon name="arrow"/></a></div><Table rows={data.sessions.slice(0,4)} empty="Тренировок пока нет. Начните с подготовки карточек или создайте тренировку." blank/></section></>;}
function Settings(){const [name,setName]=useState(()=>readProfile()==='Преподаватель'?'':readProfile()),[status,setStatus]=useState('');return <form id="profile-form" className="teacher-form" onSubmit={e=>{e.preventDefault();if(!name.trim())return;try{localStorage.setItem(PROFILE,JSON.stringify({name:name.trim()}));window.dispatchEvent(new Event('profile-changed'));setStatus('Имя сохранено.');}catch{setStatus('Браузер не смог сохранить имя.');}}}><label htmlFor="profile-input">Имя преподавателя</label><input id="profile-input" maxLength={160} required value={name} onChange={e=>setName(e.target.value)} placeholder="Фамилия и инициалы"/><p>Имя отображается в шапке панели на этом устройстве. При утверждении карточки имя преподавателя указывается отдельно.</p><button className="teacher-dark">Сохранить</button><p id="profile-status" role="status">{status}</p></form>;}
export default function Teacher({section}){
 const [data,setData]=useState({sessions:[],tasks:[],scenarios:[],trainings:[]}),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);
 useEffect(()=>{let active=true;Promise.all([api('teacher_overview'),api('scenario_list'),api('training_list')]).then(([value,scenarios,trainings])=>{if(active){setData({...value,scenarios,trainings});setError('');}}).catch(()=>{if(active)setError('Не удалось загрузить сохранённые тренировки. Карточки доступны через меню.');});return()=>{active=false;};},[attempt]);
 useEffect(()=>{document.body.dataset.teacherReady='true';return()=>{delete document.body.dataset.teacherReady;};},[]);
 const students=new Map();data.sessions.forEach(s=>students.set(s.student,(students.get(s.student)||0)+1));data.trainings.forEach(t=>t.participants.forEach(p=>students.set(p.student,students.get(p.student)||0)));
 return <main id="teacher-content" className="teacher-main" aria-live="polite">{error&&<p className="teacher-error">{error} <button id="reload-overview" className="teacher-button" onClick={()=>setAttempt(attempt+1)}>Повторить</button></p>}{section==='home'?<Home data={data}/>:<><p className="teacher-eyebrow">Панель преподавателя</p><h1 className="teacher-title">{sections[section]}</h1>
 {section==='settings'&&<Settings/>}
 {section==='materials'&&<Materials teacher/>}
 {section==='trainings'&&<><div className="teacher-toolbar"><a href="/training#learn" className="teacher-dark">Создать тренировку</a><a href="/cards" className="teacher-button">Подготовить карточки</a></div><Table rows={data.sessions} empty="Сохранённых тренировок пока нет."/></>}
 {section==='results'&&<><p className="teacher-description">Оценки, подтверждённые преподавателем, показаны по шкале 2–5. Работы без окончательного решения отмечены «На проверке».</p><div className="teacher-toolbar"><a className="teacher-dark" href="/training#works">Открыть проверку работ</a></div><Table rows={data.sessions.filter(s=>s.status!=='active')} empty="Сданных работ пока нет."/></>}
 {section==='scenarios'&&<><p className="teacher-description">Утверждённый сценарий объединяет полные учебные карточки и может входить в несколько тренировок.</p><a className="teacher-dark" href="/teacher#create-training">Создать сценарий или тренировку</a><div className="teacher-panels">{data.scenarios.length?data.scenarios.map(row=><article key={row.id} className="teacher-panel"><span className="teacher-tag">{row.status==='approved'?'Утверждён':'Черновик'}</span><h2>{row.title}</h2><p>{row.description||'Без описания'} · {row.task_ids.length} задач</p></article>):<p>Сценариев пока нет.</p>}</div></>}
 {section==='students'&&<><p className="teacher-description">Здесь отображаются участники сохранённых тренировок. Добавить участников и указать группу можно при создании тренировки. Доступ через учётные записи пока не подключён.</p><a className="teacher-button" href="/teacher#create-training">Создать тренировку →</a><div className="teacher-panels" style={{marginTop:25}}>{students.size?[...students].map(([name,count])=><article className="teacher-panel" key={name}><h2>{name}</h2><p>Тренировок: {count}</p></article>):<article className="teacher-panel"><h2>Список пока пуст</h2><p>Участники появятся после создания тренировок в учебном прототипе.</p></article>}</div></>}
 {section==='messages'&&<article className="teacher-panel"><h2>Сообщений пока нет</h2><p>Обмен сообщениями с обучающимися пока не подключён. Замечания к карточке можно оставить при её утверждении.</p><a className="teacher-button" href="/cards">Перейти к карточкам →</a></article>}
 </>}</main>;
}
