import {useEffect,useRef,useState} from 'react';
import {api} from './api.js';
import {readProfile} from './Shell.jsx';
import {Cascade} from './Classification.jsx';
import {Panel,Metrics,Modal} from './TrainingWorkspace.jsx';
const STORAGE='giik.training-plans.v1';
const fresh=()=>({id:crypto.randomUUID(),title:'',mode:'training',seconds:300,location:'',count:1,category:'1',classification:{},topic:'',comment:'',students:[],group:'',task_ids:[],assignment_task_ids:[],launched:false});
const restore=()=>{try{const value=JSON.parse(localStorage.getItem(STORAGE));return Array.isArray(value)?value.filter(p=>typeof p.id==='string'&&Array.isArray(p.task_ids)&&Array.isArray(p.students)).map(p=>({...p,mode:p.mode==='testing'?'testing':'training',assignment_task_ids:Array.isArray(p.assignment_task_ids)?p.assignment_task_ids.filter(id=>p.task_ids.includes(id)):[...p.task_ids],launched:false})):[];}catch{return [];}};
function TaskEditor({id,fields,onClose,onUpdate}){
 const [task,setTask]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[checked,setChecked]=useState(false);
 useEffect(()=>{let live=true;api('teacher_task',{id}).then(t=>{if(live)setTask(t);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[id]);
 const run=async approve=>{setBusy(true);setError('');try{await api('save_task',task);if(approve)await api('approve',{id,teacher:readProfile()});setTask(await api('teacher_task',{id}));setChecked(false);await onUpdate();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const set=(k,v)=>{setTask({...task,[k]:v});setChecked(false);};
 return <Modal title="Сценарий и эталонный ответ" wide onClose={()=>!busy&&onClose()}>{error&&<p role="alert" className="tw-error">{error}</p>}{task?<><p>{task.status==='approved'?'Утверждён · '+task.approved_by:'Черновик · проверьте все сведения перед утверждением'}</p><fieldset disabled={busy||task.status==='approved'}><label>Название<input maxLength={160} value={task.title} onChange={e=>set('title',e.target.value)}/></label><label>Первая реплика<textarea value={task.opening} maxLength={4000} onChange={e=>set('opening',e.target.value)}/></label><label>Поведение собеседника<textarea value={task.persona} maxLength={4000} onChange={e=>set('persona',e.target.value)}/></label><div className="tw-table-scroll"><table className="tw-table tw-task-fields"><thead><tr><th>Поле</th><th>Факт сценария</th><th>Что знает собеседник</th><th>Эталон</th><th>Критерий</th><th>Вес</th></tr></thead><tbody>{Object.entries(task.fields).map(([k,row])=><tr key={k}><th>{task.field_labels?.[k]||fields[k]}</th>{['truth','known','expected','criterion','weight'].map(prop=><td key={prop}>{prop==='weight'?<input aria-label={'Вес: '+fields[k]} type="number" min={1} max={10} value={row[prop]} onChange={e=>set('fields',{...task.fields,[k]:{...row,[prop]:Number(e.target.value)}})}/>:<textarea aria-label={prop+': '+fields[k]} maxLength={4000} rows={4} value={row[prop]} onChange={e=>set('fields',{...task.fields,[k]:{...row,[prop]:e.target.value}})}/>}</td>)}</tr>)}</tbody></table></div>{task.workflow==='dds'&&<><h3>Контекст ДДС и передачи службе</h3><label>Указания для проверки<textarea value={task.verification_notes} onChange={e=>set('verification_notes',e.target.value)}/></label><p><strong>{task.service.name}</strong> · {task.service.role}</p><p>{task.service.knowledge}</p><h4>Входящая карточка</h4>{Object.entries(task.incoming_card).map(([k,v])=><p key={k}>{task.field_labels?.[k]||fields[k]}: {v}</p>)}<h4>Сбои связи</h4><p>{task.faults}</p><h4>Эталон действий</h4>{Object.entries(task.actions).map(([k,v])=><p key={k}>{v.expected} · {v.criterion}</p>)}<a href="/training#tasks">Расширенное редактирование сценария ДДС →</a></>}{task.status==='draft'&&<><label className="tw-checkbox"><input id="task-reference-checked" type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>Сценарий и эталон проверены мной</label><div className="tw-modal-actions"><button onClick={()=>run(false)}>Сохранить черновик</button><button className="tw-primary" id="task-approve" disabled={!checked} onClick={()=>run(true)}>Утвердить сценарий и эталон</button></div></>}</fieldset></>:<p>Загрузка…</p>}</Modal>;
}

export default function TrainingBuilder(){
 const restored=restore();
 const [plans,setPlans]=useState(restored),[plan,setPlan]=useState(()=>restored.at(-1)||fresh()),[tasks,setTasks]=useState([]),[fields,setFields]=useState({}),[meta,setMeta]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[picker,setPicker]=useState(false),[edit,setEdit]=useState(''),[preview,setPreview]=useState(false),[studentsOpen,setStudentsOpen]=useState(false),[names,setNames]=useState(''),[launch,setLaunch]=useState(false);
 const stop=useRef(false),planRef=useRef(plan);planRef.current=plan;
 const reload=async()=>{const data=await api('teacher_dashboard');setTasks(data.tasks);setFields(data.fields);};
 useEffect(()=>{Promise.all([reload(),api('card_meta').then(setMeta)]).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(!busy)return;const prevent=e=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',prevent);return()=>window.removeEventListener('beforeunload',prevent);},[busy]);
 const update=(k,v)=>setPlan(p=>({...p,[k]:v}));
 const save=p=>{const normalized={...p,assignment_task_ids:(p.assignment_task_ids||[]).filter(id=>p.task_ids.includes(id)),launched:false};const next=[...plans.filter(x=>x.id!==normalized.id),normalized];localStorage.setItem(STORAGE,JSON.stringify(next));setPlans(next);return normalized;};
 const run=async fn=>{setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);setProgress('');}};
 const selected=plan.task_ids.map(id=>tasks.find(t=>t.id===id)).filter(Boolean);
 const assigned=plan.assignment_task_ids.map(id=>tasks.find(t=>t.id===id)).filter(Boolean);
 const approved=selected.filter(t=>t.status==='approved').length,assignedApproved=assigned.filter(t=>t.status==='approved').length;
 const chooseAssignment=(id,checked)=>setPlan(p=>({...p,assignment_task_ids:checked?[...new Set([...p.assignment_task_ids,id])]:p.assignment_task_ids.filter(x=>x!==id)}));
 const addToCatalog=(ids)=>setPlan(p=>{const task_ids=[...new Set([...p.task_ids,...ids])];return {...p,task_ids,assignment_task_ids:[...new Set([...p.assignment_task_ids,...ids])]};});
 const removeFromCatalog=id=>setPlan(p=>({...p,task_ids:p.task_ids.filter(x=>x!==id),assignment_task_ids:p.assignment_task_ids.filter(x=>x!==id)}));
 const selectAll=()=>update('assignment_task_ids',[...plan.task_ids]);
 const clearSelection=()=>update('assignment_task_ids',[]);
 const generate=()=>run(async()=>{
  if(!plan.title.trim())throw Error('Укажите название сценария.');
  if(!Number.isInteger(plan.count)||plan.count<1||plan.count>100)throw Error('Количество карточек: от 1 до 100.');
  const remaining=plan.count-plan.task_ids.length;if(remaining<=0)throw Error('В сценарии уже достаточно карточек. Увеличьте количество или уберите лишние.');
  stop.current=false;let next={...plan};
  for(let i=0;i<remaining&&!stop.current;i++){
   setProgress(`Создаётся карточка ${next.task_ids.length+1} из ${plan.count}…`);
   const topic=[`Каталог сценария: ${plan.title}`,meta?.categories[plan.category],...Object.values(plan.classification),plan.location&&'Место: '+plan.location,plan.topic,plan.comment].filter(Boolean).join('. ').slice(0,3900);
   const t=await api('create',{topic,level:'medium',workflow:plan.workflow||'caller'});
   next={...next,task_ids:[...next.task_ids,t.id],assignment_task_ids:[...new Set([...next.assignment_task_ids,t.id])]};
   setPlan(next);planRef.current=next;setTasks(old=>[t,...old]);save(next);
  }
  setNotice(stop.current?'Генерация остановлена. Созданные карточки сохранены в сценарии.':'Карточки сценария созданы. Проверьте и утвердите каждую.');
 });
 const addStudents=()=>{const values=[...new Set(names.split(/[\n;]/).map(x=>x.trim()).filter(Boolean))];if(values.some(n=>n.length>160)||values.length>100){setError('Не более 100 имён, до 160 символов каждое.');return;}setPlan(p=>({...p,students:values}));setStudentsOpen(false);};
 const removeStudent=name=>setPlan(p=>({...p,students:p.students.filter(x=>x!==name)}));
 const launchPlan=()=>run(async()=>{
  if(!assigned.length)throw Error('Выберите хотя бы одну карточку для назначения.');
  const assignmentId=crypto.randomUUID();
  await api('teacher_launch',{plan_id:assignmentId,scenario_id:plan.id,title:plan.title,group:plan.group,seconds:plan.seconds,teacher:readProfile(),students:plan.students,task_ids:plan.assignment_task_ids,mode:plan.mode});
  save(plan);setLaunch(false);setNotice(`Сценарий назначен: ${assigned.length} карточек для ${plan.students.length} обучающихся. Его можно назначить повторно другой группе или с другим набором карточек.`);
 });
 return <div className="tw-builder" data-builder-ready={!!meta}>
  <div className="tw-page-heading"><div><h1>Сценарии и назначение</h1><p className="tw-muted">Сценарий — постоянный каталог карточек. Назначение создаётся отдельно: можно выдать весь каталог или только выбранные карточки.</p></div><div><select aria-label="Каталог сценариев" disabled={busy} value={plan.id} onChange={e=>{const p=plans.find(x=>x.id===e.target.value);if(p)setPlan(p);}}><option value={plan.id}>{plan.title||'Новый сценарий'}</option>{plans.filter(p=>p.id!==plan.id).map(p=><option key={p.id} value={p.id}>{p.title||'Без названия'}</option>)}</select><button disabled={busy} onClick={()=>{save(plan);setPlan(fresh());setNotice('Открыт новый сценарий. Предыдущий сохранён в каталоге.');}}>+ Новый сценарий</button></div></div>
  {error&&<p className="tw-error" role="alert">{error}</p>}{notice&&<p className="tw-note" role="status">{notice}</p>}{busy&&<div className="tw-note" role="status">{progress||'Сохранение…'} {progress&&<button onClick={()=>{stop.current=true;setProgress('Остановка после текущей карточки…');}}>Остановить</button>}</div>}
  <fieldset disabled={busy}>
   <div className="tw-builder-top">
    <Panel title="Параметры сценария"><div className="tw-parameters"><label>Название сценария<input id="training-title" maxLength={160} value={plan.title} onChange={e=>update('title',e.target.value)} placeholder="Например: Пожары"/></label><div className="tw-parameter"><span>Режим при назначении</span><div className="tw-segments">{[['training','Обучение'],['testing','Тестирование']].map(([k,v])=><button key={k} type="button" aria-pressed={plan.mode===k} onClick={()=>update('mode',k)}>{v}</button>)}</div></div><label>Ориентир времени на карточку, секунд<input type="number" min={0} max={86400} value={plan.seconds} onChange={e=>update('seconds',Number(e.target.value))}/></label><label>Локация<input maxLength={160} value={plan.location} onChange={e=>update('location',e.target.value)} placeholder="Населённый пункт"/></label><label>Количество карточек в сценарии<input id="training-count" type="number" min={1} max={100} value={plan.count} onChange={e=>update('count',Number(e.target.value))}/></label><label>Роль обучающегося<select value={plan.workflow||'caller'} onChange={e=>update('workflow',e.target.value)}><option value="caller">Оператор 112</option><option value="dds">Диспетчер ДДС</option></select></label><p className="tw-muted">Сценарий можно дополнять и использовать повторно. Запуск больше не блокирует каталог.</p></div></Panel>
    <div className="tw-builder-right">
     <Panel title="Категория карточек">{!meta&&<p role="status">Загрузка классификатора…</p>}{meta&&<><div className="tw-segments">{[['1','Пожар'],['2','ДТП'],['22','Медицина'],['14','ЖКХ'],['13','Газ'],['3','Взрыв'],['24','БПЛА']].map(([k,v])=><button key={k} aria-pressed={plan.category===k} onClick={()=>setPlan({...plan,category:k,classification:{}})}>{v}</button>)}</div><label>Все категории<select value={plan.category} onChange={e=>setPlan({...plan,category:e.target.value,classification:{}})}>{Object.entries(meta.categories).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></>}</Panel>
     <Panel title="Параметры генерации">{meta&&<Cascade meta={meta} category={plan.category} selection={plan.classification} onChange={v=>update('classification',v)}/>}<label>Дополнительные условия<textarea id="training-topic" rows={2} maxLength={1999} placeholder="Например: разные типы объектов, разное время суток и осложняющие факторы" value={plan.topic} onChange={e=>update('topic',e.target.value)}/></label></Panel>
    </div>
   </div>
   <Panel title={`Карточки сценария · ${selected.length}`} actions={<div><button id="training-add-scenario" onClick={()=>setPicker(true)}>+ Добавить карточки</button><button type="button" onClick={selectAll}>Выбрать все для выдачи</button><button type="button" onClick={clearSelection}>Снять выбор</button></div>}>
    <p className="tw-muted">Галочка «Выдать» не удаляет карточку из сценария, а только определяет состав ближайшего назначения.</p>
    <div className="tw-table-scroll"><table className="tw-table"><thead><tr><th>Выдать</th><th>№</th><th>Карточка</th><th>Эталон</th><th>Действия</th></tr></thead><tbody>{selected.map((t,i)=><tr key={t.id}><td><input aria-label={'Выдать карточку '+(i+1)} type="checkbox" checked={plan.assignment_task_ids.includes(t.id)} onChange={e=>chooseAssignment(t.id,e.target.checked)}/></td><td>{i+1}</td><td>{t.title}</td><td>{t.status==='approved'?'Утверждён':'На проверке'}</td><td><button aria-label={'Редактировать сценарий '+(i+1)} onClick={()=>setEdit(t.id)}>✎</button><button aria-label={'Убрать карточку '+(i+1)+' из сценария'} onClick={()=>removeFromCatalog(t.id)}>×</button></td></tr>)}{!selected.length&&<tr><td colSpan={5}>Добавьте готовые карточки или создайте набор с помощью ГигаЧата.</td></tr>}</tbody></table></div><label>Комментарий к генерации<textarea rows={2} maxLength={1999} value={plan.comment} onChange={e=>update('comment',e.target.value)} placeholder="Требования ко всему набору карточек"/></label>
   </Panel>
   <div className="tw-builder-bottom">
    <Panel title="Кому назначить" actions={<button id="training-add-students" onClick={()=>{setNames(plan.students.join('\n'));setStudentsOpen(true);}}>+ Добавить</button>}><label>Группа<input maxLength={160} value={plan.group} onChange={e=>update('group',e.target.value)} placeholder="Например: группа 2"/></label><p className="tw-muted">Режим «Обучение» или «Тестирование» применяется ко всему назначению.</p><ul className="tw-student-list">{plan.students.map(n=><li key={n}><span className="tw-student-name">▣ {n}</span><button aria-label={'Убрать '+n} onClick={()=>removeStudent(n)}>×</button></li>)}</ul>{!plan.students.length&&<p className="tw-muted">Можно указать одного обучающегося, несколько человек или всю учебную группу.</p>}</Panel>
    <Panel title="Состав назначения"><Metrics items={[["Карточек в каталоге",selected.length],["Выбрано для выдачи",assigned.length],["Утверждено выбранных",`${assignedApproved} / ${assigned.length}`],["Обучающихся",plan.students.length]]}/><p>{assigned.length===selected.length&&selected.length?'Будет выдан весь сценарий.':assigned.length?`Будет выдана выборка: ${assigned.length} из ${selected.length} карточек.`:'Карточки для выдачи пока не выбраны.'}</p><p className="tw-muted">Исходный сценарий остаётся в каталоге после назначения и может использоваться повторно.</p></Panel>
    <Panel title="Предпросмотр"><ol className="tw-preview-list">{assigned.map((t,i)=><li key={t.id}><strong>Карточка {i+1} из {assigned.length}</strong><span>{t.title}</span><button aria-label={'Предпросмотр карточки '+(i+1)} onClick={()=>setEdit(t.id)}>↗</button></li>)}</ol>{!assigned.length&&<p>Отметьте карточки в каталоге.</p>}</Panel>
   </div>
  </fieldset>
  <footer className="tw-footer tw-builder-footer"><span>Сценарий: {selected.length} карточек · к выдаче: {assigned.length} · эталоны: {approved} / {selected.length}</span><button id="training-save" disabled={busy} onClick={()=>{try{save(plan);setNotice('Сценарий сохранён в каталоге.');}catch{setError('Не удалось сохранить сценарий в браузере.');}}}>Сохранить сценарий</button><button id="training-generate" disabled={busy||!meta} onClick={generate}>Сгенерировать карточки</button><button disabled={!assigned.length||busy} onClick={()=>setPreview(true)}>Предпросмотр выдачи</button><button id="training-launch" className="tw-primary" disabled={busy||!plan.title.trim()||!plan.students.length||!assigned.length||assignedApproved!==assigned.length} onClick={()=>setLaunch(true)}>Назначить обучающимся</button><a href="/teacher">Закрыть</a></footer>
  {picker&&<Modal title="Добавить карточки в сценарий" onClose={()=>setPicker(false)}><div className="tw-picker">{tasks.map(t=><label key={t.id} className="tw-checkbox"><input type="checkbox" checked={plan.task_ids.includes(t.id)} disabled={!plan.task_ids.includes(t.id)&&plan.task_ids.length>=100} onChange={e=>e.target.checked?addToCatalog([t.id]):removeFromCatalog(t.id)}/><span>{t.title}<small>{t.status==='approved'?'Утверждён':'Черновик'}</small></span></label>)}{!tasks.length&&<p>Сохранённых карточек пока нет. Используйте кнопку «Сгенерировать карточки».</p>}</div><button className="tw-primary" onClick={()=>setPicker(false)}>Готово</button></Modal>}
  {studentsOpen&&<Modal title="Обучающиеся" onClose={()=>setStudentsOpen(false)}><label>Каждое имя с новой строки<textarea id="training-student-names" rows={8} maxLength={16100} value={names} onChange={e=>setNames(e.target.value)}/></label><p>Имя должно совпадать с именем в профиле обучающегося.</p><button className="tw-primary" onClick={addStudents}>Добавить в план</button></Modal>}
  {edit&&<TaskEditor id={edit} fields={fields} onClose={()=>setEdit('')} onUpdate={reload}/>} 
  {preview&&<Modal title={plan.title||'Предпросмотр сценария'} onClose={()=>setPreview(false)}><p>{plan.students.length} обучающихся · {assigned.length} карточек из {selected.length} · утверждено: {assignedApproved}</p><ol>{assigned.map(t=><li key={t.id}>{t.title}</li>)}</ol><p>После назначения карточки появятся у выбранных обучающихся как части сценария «{plan.title}».</p></Modal>}
  {launch&&<Modal title="Назначить сценарий?" onClose={()=>!busy&&setLaunch(false)}><p>Будет создано {plan.students.length*assigned.length} учебных работ: {assigned.length} карточек × {plan.students.length} обучающихся.</p><p>{assigned.length===selected.length?'Назначается весь сценарий.':`Назначаются выбранные карточки: ${assigned.length} из ${selected.length}.`}</p><p>{plan.mode==='testing'?'Тестирование: подсказки полностью отключены.':'Обучение: если обучающийся 10 секунд не выполняет полезных действий, система раскрывает одно эталонное поле и подталкивает к продолжению.'}</p><ul>{plan.students.map(n=><li key={n}>{n}</li>)}</ul>{error&&<p className="tw-error" role="alert">{error}</p>}<button id="training-launch-confirm" className="tw-primary" disabled={busy} onClick={launchPlan}>Назначить</button></Modal>}
 </div>;
}
