import { createRequire } from 'node:module';
import { spawn } from 'node:child_process';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const { chromium }=createRequire(import.meta.url)('playwright');
const server=spawn(process.env.AI_TEST_PYTHON||'python',['-u','-c',"exec(open('tests/ui_fixture.py', encoding='utf-8').read())"],{env:{...process.env,PYTHONUTF8:'1'}});
let out='',err='';server.stdout.on('data',b=>out+=b);server.stderr.on('data',b=>err+=b);
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 for(let i=0;i<100&&!out.includes('http://');i++)await new Promise(r=>setTimeout(r,50));
 const url=out.match(/http:\/\/127\.0\.0\.1:\d+/)?.[0];assert.ok(url,err);
 const page=await browser.newPage({viewport:{width:1440,height:1050}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.addInitScript(()=>{navigator.mediaDevices.getUserMedia=async()=>({getTracks:()=>[{stop(){}}]});window.SpeechRecognition=class{start(){this.onresult({results:[[{transcript:'Внутри есть люди?'}]]});this.onend();}abort(){};};});
 const idle=()=>page.waitForFunction(()=>document.body.getAttribute('aria-busy')==='false');
 await page.goto(url+'/training');await idle();
 assert.equal(await page.getByRole('button',{name:'Начать обучение',exact:true}).isDisabled(),true);
 await page.locator('[data-page=tasks]').click();await idle();
 await page.locator('#level').selectOption('hard');await page.locator('[data-cmd=sample]').click();await idle();
 await page.locator('#task-title').fill('Учебный пожар · тест интерфейса');await page.locator('#teacher-name').fill('Преподаватель');
 await page.locator('[data-cmd=approve]').click();await idle();
 assert.ok((await page.locator('#content').textContent()).includes('Карточка доступна'));
 await page.locator('[data-page=learn]').click();await idle();await page.locator('#student-name').fill('Ученик');
 await page.getByRole('button',{name:'Начать обучение',exact:true}).click();await idle();
 assert.equal(await page.locator('[data-cmd=hint]').isDisabled(),true);
 await page.locator('[data-cmd=mic]').click();await page.waitForFunction(()=>document.querySelector('#question').value==='Внутри есть люди?');
 await page.getByRole('button',{name:'Спросить',exact:true}).click();await idle();
 assert.ok((await page.locator('#chat').textContent()).includes('Я не видела'));
 await page.locator('#card-people').fill('Возможно, мужчина внутри');
 await page.locator('[data-cmd=save-card]').click();await idle();
 await fs.mkdir('test-output',{recursive:true});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'test-output/web-student.png',fullPage:true});
 await page.reload();await idle();await page.getByRole('button',{name:'Продолжить',exact:true}).click();await idle();
 assert.equal(await page.locator('#card-people').inputValue(),'Возможно, мужчина внутри');
 await page.locator('[data-cmd=submit]').click();await idle();
 assert.ok((await page.locator('#content').textContent()).includes('Ожидайте окончательного решения'));
 assert.ok(!(await page.locator('#content').textContent()).includes('Нужно уточнение.'));
 await page.locator('[data-page=works]').click();await idle();await page.getByRole('button',{name:'Рассмотреть',exact:true}).click();await idle();
 const fields=['address','incident','people','injured','floors','entrance','access'];
 for(const key of fields)await page.locator('#decision-'+key).selectOption('agree');
 await page.locator('#decision-people').selectOption('edit');await page.locator('#comment-people').fill('Неопределённость сохранена верно.');
 await page.locator('#grade').selectOption('4');await page.locator('#conclusion').fill('Решение преподавателя');
 await page.locator('[data-cmd=finalize]').click();await idle();
 await page.locator('[data-page=learn]').click();await idle();await page.getByRole('button',{name:'Посмотреть',exact:true}).click();await idle();
 assert.ok((await page.locator('#content').textContent()).includes('Оценка: 4'));
 // DDS uses a filled card, an actual call state and delivered-message tracking.
 await page.locator('[data-page=tasks]').click();await idle();
 await page.locator('#create-workflow').selectOption('dds');await page.locator('#level').selectOption('hard');
 await page.locator('[data-cmd=sample]').click();await idle();
 assert.ok(await page.locator('#dds-verification').isVisible());
 await page.locator('[data-cmd=approve]').click();await idle();
 await page.locator('[data-page=learn]').click();await idle();
 await page.locator('#learn-workflow').selectOption('dds');
 await page.getByRole('button',{name:'Начать обучение',exact:true}).click();await idle();
 assert.ok((await page.locator('#card-address').inputValue()).endsWith('12'));
 assert.equal(await page.locator('#question').isDisabled(),true);
 await page.locator('#card-address').fill('Учебный город, улица Лесная, 14');
 await page.locator('[data-cmd=connect-service]').click();await idle();
 await page.locator('#next-channel').selectOption('drop');await idle();
 await page.locator('#question').fill('Адрес Лесная 14, вода во дворе');
 await page.getByRole('button',{name:'Спросить',exact:true}).click();await idle();
 assert.equal(await page.locator('#question').isDisabled(),true);
 assert.ok((await page.locator('#chat').textContent()).includes('не доставлена'));
 await page.locator('[data-cmd=connect-service]').click();await idle();
 await page.locator('#question').fill('Повторяю: Лесная 14, повреждение трубы');
 await page.getByRole('button',{name:'Спросить',exact:true}).click();await idle();
 await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'test-output/web-dds.png',fullPage:true});
 await page.locator('[data-cmd=submit]').click();await idle();
 await page.locator('[data-page=works]').click();await idle();
 await page.getByRole('button',{name:'Рассмотреть',exact:true}).first().click();await idle();
 for(const key of [...fields,'action_validation','action_transmission','action_confirmation','action_recovery'])await page.locator('#decision-'+key).selectOption('agree');
 await page.locator('#grade').selectOption('4');await page.locator('#conclusion').fill('Проверены поля и действия ДДС');
 await page.locator('[data-cmd=finalize]').click();await idle();
 assert.ok((await page.locator('#content').textContent()).includes('Оценка: 4'));
 // Only whitelisted static files are served; mutation requires the page token.
 assert.equal((await page.request.get(url+'/data/sample.json')).status(),404);
 assert.equal((await page.request.post(url+'/api',{data:{action:'tasks'}})).status(),403);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-output/web-mobile.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.deepEqual(errors,[]);console.log('Browser UI: both workflows, DDS drop/reconnect, 11 teacher criteria, caller regression, persistence and mobile layout passed.');
}finally{server.kill();await browser.close();}
