import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import assert from 'node:assert/strict';
const {chromium}=createRequire(import.meta.url)('playwright');
const server=spawn(process.env.AI_TEST_PYTHON||'python',['-u','-c',"exec(open('tests/ui_fixture.py',encoding='utf-8').read())"],{env:{...process.env,PYTHONUTF8:'1'}});
let out='',err='';server.stdout.on('data',b=>out+=b);server.stderr.on('data',b=>err+=b);
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 for(let i=0;i<100&&!out.includes('http://');i++)await new Promise(r=>setTimeout(r,50));
 const url=out.match(/http:\/\/127\.0\.0\.1:\d+/)?.[0];assert.ok(url,err);
 const page=await browser.newPage({viewport:{width:1900,height:1024}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto(url+'/cards');await page.waitForFunction(()=>document.body.dataset.ready==='true');
 const generator=page.locator('#generate-form');
 assert.equal(await page.locator('#category option').count(),25);
 await generator.getByRole('button',{name:'жилой дом',exact:true}).click();
 await generator.getByRole('button',{name:'балкон',exact:true}).click();
 await generator.getByRole('button',{name:'открытое пламя',exact:true}).click();
 await page.screenshot({path:'test-output/making-react-desktop.png'});
 await page.locator('[data-category="17"]').click();
 assert.equal(await generator.getByRole('button',{name:'балкон',exact:true}).count(),0);
 await generator.getByRole('button',{name:'Человек в воде, на льдине',exact:true}).click();
 for(const text of ['Человек тонет (в настоящее время)','Человек утонул (ушел под воду и не выныривает)','Всплыл утопленник'])assert.equal(await generator.getByRole('button',{name:text,exact:true}).count(),1);
 await generator.getByRole('button',{name:'Всплыл утопленник',exact:true}).click();
 await page.locator('#generate').click();await page.waitForFunction(()=>!document.querySelector('#generate').disabled);
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('giik.card-workshop.v1')));
 assert.equal(saved.cards[0].content.class_ids[0],'17070500');
 await page.reload();await page.waitForFunction(()=>document.body.dataset.ready==='true');
 assert.equal(await page.locator('#category').inputValue(),'17');
 await page.locator('#composer > summary').click();
 assert.equal(await generator.getByRole('button',{name:'Всплыл утопленник',exact:true}).getAttribute('class'),'selected');
 const stored=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('giik.card-workshop.v1')));
 const beforeOpening=(await stored()).cards[0].content;
 await page.locator('[data-dock-service="102"]').click();
 assert.equal(await page.locator('[data-dock-service="102"]').getAttribute('aria-expanded'),'true');
 assert.equal(await page.locator('#dock-service-title').innerText(),'Служба 102 — МВД');
 assert.deepEqual((await stored()).cards[0].content,beforeOpening,'Opening service does not change card');
 await page.screenshot({path:'test-output/service-panel-desktop.png'});
 await page.keyboard.press('Escape');
 await page.locator('#dock-service-panel').waitFor({state:'hidden'});
 await page.locator('#dock-other-services').click();
 await page.locator('[data-service="102"]').uncheck();
 await page.getByRole('button',{name:'Применить состав',exact:true}).click();
 assert.equal(await page.locator('[data-dock-service="102"]').count(),0);
 await page.locator('#editor [data-flag="injured"]').selectOption('yes');
 assert.equal(await page.locator('[data-dock-service="ZEMP"]').count(),1);
 assert.equal(await page.locator('[data-dock-service="102"]').count(),0);
 await page.locator('#editor [data-flag="injured"]').selectOption('no');
 assert.equal(await page.locator('[data-dock-service="ZEMP"]').count(),0);
 await page.locator('#dock-other-services').click();
 await page.locator('[data-service="102"]').check();
 await page.getByRole('button',{name:'Применить состав',exact:true}).click();
 await page.locator('#dock-other-services').click();
 await page.getByPlaceholder('Название службы').fill('MOSVODOSTOK');
 await page.locator('[data-service="MOSVODOSTOK"]').check();
 await page.keyboard.press('Escape');
 await page.locator('#services-picker').waitFor({state:'hidden'});
 assert.equal(await page.locator('[data-dock-service="MOSVODOSTOK"]').count(),0,'Closing dialog cancels unapplied addition');
 await page.locator('#dock-other-services').click();
 await page.getByPlaceholder('Название службы').fill('MOSVODOSTOK');
 assert.equal(await page.locator('[data-service="MOSVODOSTOK"]').isChecked(),false);
 await page.locator('[data-service="MOSVODOSTOK"]').check();
 await page.getByRole('button',{name:'Применить состав',exact:true}).click();
 assert.equal(await page.locator('[data-dock-service="MOSVODOSTOK"]').count(),1);
 await page.locator('#dock-save').click();
 await page.reload();await page.waitForFunction(()=>document.body.dataset.ready==='true');
 assert.equal(await page.locator('[data-dock-service="MOSVODOSTOK"]').count(),1);
 const checkFixedPanels=async()=>{
  const bounds=await page.evaluate(()=>{
   const box=s=>{const r=document.querySelector(s).getBoundingClientRect();return {top:r.top,bottom:r.bottom};};
   return {shell:box('#teacher-shell'),header:box('.teacher-header'),nav:box('.teacher-sidebar'),dock:box('.services-dock'),height:innerHeight,scroll:scrollY};
  });
  assert.ok(bounds.scroll>100,'Page actually scrolled');
  assert.ok(Math.abs(bounds.shell.top)<1,'Shared shell stays at top');
  assert.ok(Math.abs(bounds.header.top)<1,'Header stays attached to shell');
  assert.ok(Math.abs(bounds.header.bottom-bounds.nav.top)<1,'Navigation stays attached to header');
  assert.ok(Math.abs(bounds.nav.bottom-bounds.shell.bottom)<1);
  assert.ok(Math.abs(bounds.dock.bottom-bounds.height)<1,'Services dock stays at viewport bottom');
 };
 await page.evaluate(()=>scrollTo(0,900));await checkFixedPanels();
 await page.screenshot({path:'test-output/making-react-scroll.png'});
 await page.locator('#dock-preview').click();
 assert.ok(await page.evaluate(()=>document.querySelector('#editor').getBoundingClientRect().top>=document.querySelector('#teacher-shell').getBoundingClientRect().bottom),'Card not covered by header');
 await page.locator('#choose-services').click();await page.locator('[data-service="103"]').check();
 await page.getByRole('button',{name:'Применить состав',exact:true}).click();
 await page.locator('#main-service').selectOption('103');
 await page.locator('#teacher').fill('Преподаватель');await page.locator('#open-reference').click();await page.locator('#generate-reference').click();await page.waitForFunction(()=>!document.querySelector('#generate').disabled);await page.locator('#reference-reviewed').check();await page.locator('#approve').click();await page.locator('#reopen').waitFor();
 assert.equal(await page.locator('[data-dock-service="102"]').isDisabled(),false);
 await page.locator('[data-dock-service="102"]').click();await page.locator('#dock-service-panel').waitFor();
 await page.keyboard.press('Escape');
 await page.locator('#dock-other-services').click();
 assert.equal(await page.locator('[data-service="103"]').isDisabled(),true);
 await page.keyboard.press('Escape');
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.evaluate(()=>scrollTo(0,900));await checkFixedPanels();
 await page.screenshot({path:'test-output/making-react-mobile-scroll.png'});
 await page.locator('[data-dock-service="101"]').click();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.screenshot({path:'test-output/service-panel-mobile.png'});
 await page.keyboard.press('Escape');
 await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'test-output/making-react-mobile.png'});
 assert.deepEqual(errors,[]);console.log('PASS: classifier, service tabs open without mutation, teacher applies/cancels composition, persistence, approved service viewing, desktop/mobile layout.');
}finally{server.kill();await browser.close();}
