import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import assert from 'node:assert/strict';
const {chromium}=createRequire(import.meta.url)('playwright');
const server=spawn(process.env.AI_TEST_PYTHON||'python',['-u','-c',"exec(open('tests/ui_fixture.py',encoding='utf-8').read())"],{env:{...process.env,PYTHONUTF8:'1'}});
let out='',err='';server.stdout.on('data',b=>out+=b);server.stderr.on('data',b=>err+=b);
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 for(let i=0;i<100&&!out.includes('http://');i++)await new Promise(r=>setTimeout(r,50));
 const url=out.match(/http:\/\/127\.0\.0\.1:\d+/)?.[0];assert.ok(url,err);
 const page=await browser.newPage({viewport:{width:1900,height:1120}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const ready=()=>page.waitForFunction(()=>document.body.dataset.journalReady==='true');
 await page.goto(url);await page.getByRole('link',{name:'Войти',exact:true}).click();await ready();
 await page.getByText('Пока нет карточек',{exact:true}).waitFor();
 await page.locator('#journal-new').click();await page.waitForFunction(()=>document.body.dataset.ready==='true');
 assert.equal(await page.locator('#composer').getAttribute('open'),'');
 await page.locator('#generate').click();await page.waitForFunction(()=>!document.querySelector('#generate').disabled);
 // A disposable set exercises dates, counts, statuses and pagination without user data.
 await page.evaluate(()=>{
  const state=JSON.parse(localStorage.getItem('giik.card-workshop.v1')),base=state.cards[0];
  state.cards=Array.from({length:15},(_,i)=>{const c=structuredClone(base);c.id='journal-'+i;c.number='К-'+String(i+1).padStart(4,'0');c.created_at=new Date(2026,8,i+1,12,0,0).toISOString();c.content.title='Карточка '+(i+1);c.content.fields.description=i===2?'Уникальное описание: гараж у реки':'Задымление гаража';c.content.fields.address_text='Учебный город, Лесная, '+(i+1);c.content.fields.district=i%2?'Северный':'Южный';c.status=i%3===0?'approved':'draft';c.review=c.status==='approved'?{teacher:'Тест',at:c.created_at}:null;c.reference.source_content=structuredClone(c.content);return c;});state.selected=state.cards[0].id;localStorage.setItem('giik.card-workshop.v1',JSON.stringify(state));
 });
 await page.goto(url+'/teacher');await ready();
 assert.match(await page.locator('#journal-count').innerText(),/15/);
 assert.equal(await page.locator('[data-card-row]').count(),10);
 assert.equal(await page.locator('[data-card-row]').first().getAttribute('data-card-row'),'journal-14');
 await page.locator('#journal-sort').click();assert.equal(await page.locator('[data-card-row]').first().getAttribute('data-card-row'),'journal-0');
 await page.getByRole('button',{name:'Следующая страница'}).click();assert.equal(await page.locator('[data-card-row]').count(),5);
 await page.locator('#journal-status').selectOption('approved');assert.equal(await page.locator('[data-card-row]').count(),5);
 await page.locator('#journal-district').selectOption('Южный');assert.equal(await page.locator('[data-card-row]').count(),3);
 await page.locator('#journal-reset').click();await page.locator('#journal-date').fill('2026-09-03');assert.equal(await page.locator('[data-card-row]').count(),1);
 await page.locator('#journal-reset').click();await page.locator('#journal-query').fill('уникальное');assert.equal(await page.locator('[data-card-row]').count(),1);
 await page.locator('.journal-number').click();await page.waitForFunction(()=>document.body.dataset.ready==='true');
 assert.equal(await page.locator('#card-title').inputValue(),'Карточка 3');
 await page.locator('.back-to-journal').click();await ready();
 await page.locator('#journal-query').fill('несуществующее');assert.equal(await page.locator('[data-card-row]').count(),0);
 await page.getByText('Ничего не найдено',{exact:true}).waitFor();await page.locator('#journal-reset').click();
 await page.locator('#journal-page-size').selectOption('25');assert.equal(await page.locator('[data-card-row]').count(),15);
 await page.locator('#journal-page-size').selectOption('10');
 await page.locator('.journal-expand').first().click();await page.locator('.journal-detail').waitFor();
 await page.screenshot({path:'test-output/journal-desktop.png',fullPage:true});
 await page.locator('#journal-new').click();await page.waitForFunction(()=>document.body.dataset.ready==='true');
 assert.equal(await page.locator('#composer').getAttribute('open'),'','New card action opens generator even with existing cards');
 await page.goto(url+'/teacher');await ready();
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.screenshot({path:'test-output/journal-mobile.png',fullPage:true});
 await page.locator('#journal-filter-toggle').click();assert.equal(await page.locator('#journal-filters').isVisible(),false);
 await page.locator('.teacher-menu').click();await page.locator('[data-section=settings]').click();
 await page.locator('#profile-input').fill('Преподаватель Тестов');await page.getByRole('button',{name:'Сохранить',exact:true}).click();
 await page.locator('.teacher-menu').click();await page.locator('[data-section=home]').click();await ready();
 assert.equal(await page.locator('#profile-name').innerText(),'Преподаватель Тестов');
 assert.equal(await page.locator('.teacher-sidebar').isVisible(),false);
 assert.deepEqual(errors,[]);console.log('PASS: journal entry, persisted cards, search, date/status/district filters, sort, pagination, card deep link, create, expansion, mobile and profile.');
}finally{server.kill();await browser.close();}
