"""Заявитель: статус и три телефона

Revision ID: 230154781e5b
Revises: 2b92687cd903
Create Date: 2026-09-23 02:15:04.252731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230154781e5b'
down_revision: Union[str, None] = '2b92687cd903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempt', sa.Column('entered_caller_phone', sa.String(length=32), nullable=True))
    op.add_column('scenario', sa.Column('caller_role', sa.Enum('PARTICIPANT', 'WITNESS', 'RELATIVE', name='callerrole', native_enum=False, length=32), nullable=True))
    op.add_column('scenario', sa.Column('caller_phone_aon', sa.String(length=32), nullable=True))
    op.add_column('scenario', sa.Column('caller_phone_stated', sa.String(length=32), nullable=True))
    op.add_column('scenario', sa.Column('caller_phone_onsite', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenario', 'caller_phone_onsite')
    op.drop_column('scenario', 'caller_phone_stated')
    op.drop_column('scenario', 'caller_phone_aon')
    op.drop_column('scenario', 'caller_role')
    op.drop_column('attempt', 'entered_caller_phone')
    # ### end Alembic commands ###
