"""Режим оператора 112: классификация по опросной карте

Revision ID: b6f959bd4017
Revises: d9871018aeb2
Create Date: 2026-09-16 16:03:33.251296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6f959bd4017'
down_revision: Union[str, None] = 'd9871018aeb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Обязательным колонкам нужно значение по умолчанию на уровне СУБД:
    # без него добавление в непустую таблицу прерывается. Существующие
    # сценарии относятся к режиму диспетчера — это их исходный смысл.
    op.add_column('attempt', sa.Column('chosen_group', sa.String(length=255), nullable=True))
    op.add_column(
        'attempt',
        sa.Column('chosen_path', sa.JSON(), nullable=False, server_default='[]'),
    )
    op.add_column('attempt', sa.Column('entered_address', sa.String(length=500), nullable=True))
    op.add_column('attempt', sa.Column('entered_description', sa.Text(), nullable=True))
    op.add_column(
        'scenario',
        sa.Column(
            'mode',
            sa.Enum(
                'DISPATCHER', 'OPERATOR', name='trainingmode', native_enum=False, length=32
            ),
            nullable=False,
            server_default='DISPATCHER',
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenario', 'mode')
    op.drop_column('attempt', 'entered_description')
    op.drop_column('attempt', 'entered_address')
    op.drop_column('attempt', 'chosen_path')
    op.drop_column('attempt', 'chosen_group')
    # ### end Alembic commands ###
