"""Исходы обращения, критерии успешности, обратная связь и справочная база

Revision ID: c0543e00778b
Revises: f00c158a97ad
Create Date: 2026-09-20 14:23:29.649689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0543e00778b'
down_revision: Union[str, None] = 'f00c158a97ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('media_type', sa.String(length=128), nullable=True),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('attempt', sa.Column('chosen_outcome', sa.Enum('CLASSIFY', 'REFER', 'REJECT', name='calloutcome', native_enum=False, length=32), nullable=True))
    op.add_column('attempt', sa.Column('chosen_referral_target', sa.String(length=255), nullable=True))
    op.add_column('evaluation', sa.Column('teacher_feedback', sa.Text(), nullable=True))
    op.add_column('evaluation', sa.Column('teacher_feedback_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('evaluation', sa.Column('teacher_feedback_by_id', sa.Integer(), nullable=True))
    # Имя ключу задаётся явно: безымянное ограничение автогенератор потом
    # не может ни найти, ни удалить, и откат миграции падает.
    op.create_foreign_key(
        'fk_evaluation_teacher_feedback_by', 'evaluation', 'app_user',
        ['teacher_feedback_by_id'], ['id'],
    )
    op.add_column('scenario', sa.Column('expected_outcome', sa.Enum('CLASSIFY', 'REFER', 'REJECT', name='calloutcome', native_enum=False, length=32), server_default='CLASSIFY', nullable=False))
    op.add_column('scenario', sa.Column('referral_target', sa.String(length=255), nullable=True))
    op.add_column('training_session', sa.Column('pass_score', sa.Float(), server_default='0.7', nullable=False))
    op.add_column('training_session', sa.Column('max_critical_violations', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_session', 'max_critical_violations')
    op.drop_column('training_session', 'pass_score')
    op.drop_column('scenario', 'referral_target')
    op.drop_column('scenario', 'expected_outcome')
    op.drop_constraint('fk_evaluation_teacher_feedback_by', 'evaluation', type_='foreignkey')
    op.drop_column('evaluation', 'teacher_feedback_by_id')
    op.drop_column('evaluation', 'teacher_feedback_at')
    op.drop_column('evaluation', 'teacher_feedback')
    op.drop_column('attempt', 'chosen_referral_target')
    op.drop_column('attempt', 'chosen_outcome')
    op.drop_table('training_material')
    # ### end Alembic commands ###
