"""Исходная схема учебного комплекса

Revision ID: d9871018aeb2
Revises: 
Create Date: 2026-09-16 15:42:06.430830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9871018aeb2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatch_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ekp_name', sa.String(length=255), nullable=True),
    sa.Column('uses_arm112', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=150), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'TEACHER', 'STUDENT', name='role', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['dispatch_service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_login'), 'app_user', ['login'], unique=True)
    op.create_table('scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'GENERATED', 'TICKET', name='scenariosource', native_enum=False, length=32), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('ekp_rule_number', sa.Integer(), nullable=True),
    sa.Column('incident_type', sa.String(length=255), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('caller', sa.String(length=255), nullable=False),
    sa.Column('target_service_id', sa.Integer(), nullable=False),
    sa.Column('expected_primary_status', sa.String(length=64), nullable=False),
    sa.Column('is_profile', sa.Boolean(), nullable=False),
    sa.Column('expects_progress_statuses', sa.Boolean(), nullable=False),
    sa.Column('required_comment_points', sa.JSON(), nullable=False),
    sa.Column('deadline_seconds', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('teacher_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['target_service_id'], ['dispatch_service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_ekp_rule_number'), 'scenario', ['ekp_rule_number'], unique=False)
    op.create_table('training_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('state', sa.Enum('DRAFT', 'ACTIVE', 'FINISHED', name='sessionstate', native_enum=False, length=32), nullable=False),
    sa.Column('deadline_seconds', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('card_status', sa.Enum('REGISTERED', 'NOT_NOTIFIED', 'REFUSED', 'UNFINISHED', 'COMPLETED', name='cardstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['training_session.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('violations', sa.JSON(), nullable=False),
    sa.Column('llm_pending', sa.Boolean(), nullable=False),
    sa.Column('llm_available', sa.Boolean(), nullable=False),
    sa.Column('llm_summary', sa.Text(), nullable=True),
    sa.Column('grammar_issues', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempt.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id')
    )
    op.create_table('status_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('elapsed_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_event')
    op.drop_table('evaluation')
    op.drop_table('attempt')
    op.drop_table('training_session')
    op.drop_index(op.f('ix_scenario_ekp_rule_number'), table_name='scenario')
    op.drop_table('scenario')
    op.drop_index(op.f('ix_app_user_login'), table_name='app_user')
    op.drop_table('app_user')
    op.drop_table('dispatch_service')
    # ### end Alembic commands ###
