"""Журнал аудита действий пользователей

Revision ID: eb144cdcfde7
Revises: b6f959bd4017
Create Date: 2026-09-16 16:22:12.443664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb144cdcfde7'
down_revision: Union[str, None] = 'b6f959bd4017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('action', sa.Enum('LOGIN', 'LOGIN_FAILED', 'USER_CREATED', 'USER_UPDATED', 'USER_BLOCKED', 'USER_UNBLOCKED', 'PASSWORD_CHANGED', 'SCENARIO_GENERATED', 'SCENARIO_APPROVED', 'SCENARIO_CORRECTED', 'SCENARIO_DELETED', name='auditaction', native_enum=False, length=48), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_login', sa.String(length=150), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_event_action'), 'audit_event', ['action'], unique=False)
    op.create_index(op.f('ix_audit_event_at'), 'audit_event', ['at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_event_at'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_action'), table_name='audit_event')
    op.drop_table('audit_event')
    # ### end Alembic commands ###
