"""Занятие: состав участников, сценарии и поток вызовов

Revision ID: f00c158a97ad
Revises: eb144cdcfde7
Create Date: 2026-09-16 16:35:17.233194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f00c158a97ad'
down_revision: Union[str, None] = 'eb144cdcfde7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_scenario',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['training_session.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'scenario_id')
    )
    op.create_table('session_student',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['training_session.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'student_id')
    )
    # Существующее занятие относится к режиму диспетчера, а поток вызовов
    # у него был мгновенным — сохраняем это как нулевой интервал.
    op.add_column(
        'training_session',
        sa.Column(
            'mode',
            sa.Enum('DISPATCHER', 'OPERATOR', name='trainingmode', native_enum=False, length=32),
            nullable=False,
            server_default='DISPATCHER',
        ),
    )
    op.add_column(
        'training_session',
        sa.Column('call_interval_seconds', sa.Integer(), nullable=False, server_default='20'),
    )
    # Норматив взятия карточки в работу переименован: прежнее deadline_seconds
    # не различало реакцию и обработку, а организаторы задали два норматива.
    op.alter_column('training_session', 'deadline_seconds', new_column_name='pickup_deadline_seconds')
    op.add_column(
        'training_session',
        sa.Column(
            'handling_deadline_seconds', sa.Integer(), nullable=False, server_default='180'
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_session', 'handling_deadline_seconds')
    op.alter_column('training_session', 'pickup_deadline_seconds', new_column_name='deadline_seconds')
    op.drop_column('training_session', 'call_interval_seconds')
    op.drop_column('training_session', 'mode')
    op.drop_table('session_student')
    op.drop_table('session_scenario')
    # ### end Alembic commands ###
