"""Адрес по частям

Revision ID: f7f77c2cb915
Revises: 230154781e5b
Create Date: 2026-09-23 08:42:59.383846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7f77c2cb915'
down_revision: Union[str, None] = '230154781e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempt', sa.Column('entered_address_parts', sa.JSON(), server_default='{}', nullable=False))
    op.add_column('scenario', sa.Column('address_parts', sa.JSON(), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenario', 'address_parts')
    op.drop_column('attempt', 'entered_address_parts')
    # ### end Alembic commands ###
